### ISSUE TITLE
crash in plot gui with experimental new storage

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1000]
Ran the poly case, clicked the plot button

```
Traceback (most recent call last):
  File "/prog/res/komodo/2020.09.rc2-py36/root/lib/python3.6/site-packages/ert_gui/tools/plot/plot_tool.py", line 15, in trigger
    plot_window = PlotWindow(self._config_file, self._storage_client, self.parent())
  File "/prog/res/komodo/2020.09.rc2-py36/root/lib/python3.6/site-packages/ert_gui/tools/plot/plot_window.py", line 41, in __init__
    self._key_definitions = self._api.all_data_type_keys()
  File "/prog/res/komodo/2020.09.rc2-py36/root/lib/python3.6/site-packages/ert_shared/storage/client.py", line 64, in all_data_type_keys
    ensembles = ref_request("{base}/ensembles".format(base=self._BASE_URI))
  File "/prog/res/komodo/2020.09.rc2-py36/root/lib/python3.6/site-packages/ert_shared/storage/client.py", line 30, in ref_request
    return resp.json()
  File "/prog/res/komodo/2020.09.rc2-py36/root/lib/python3.6/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/prog/res/komodo/2020.09.rc2-py36/root/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/prog/res/komodo/2020.09.rc2-py36/root/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/prog/res/komodo/2020.09.rc2-py36/root/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Error message: Program received signal:6

See file: /tmp/ert_abort_dump.jond.20200901-130753.log for more details of the crash.
Setting the environment variable "ERT_SHOW_BACKTRACE" will show the backtrace on stderr.
/prog/res/komodo/2020.09.rc2-py36/root/bin/python: line 5: 12091 Aborted                 (core dumped) $root/libexec/$prog "$@"```

**Comment by jondequinor** [comment]
Also seen in current stable (2020.08).

**Comment by oysteoh** [comment]
How did you run the polycase? I cannot reproduce running es_mda at least - everything succeeds and i'm able to plot directly afterwards running with new storage enabled

**Comment by sondreso** [comment]
I have only observed this error in the office, might be proxy related?

**Comment by jondequinor** [comment]
Ran `ert gui poly.ert --enable-new-storage` on `ert@master(8f2e7181123c53555520b1d3359b15c893b3b5e3)`, then pressed "Start simulation" immediately. When it completed, I clicked the plot button.

**Comment by oysteoh** [comment]
I will give it a go on my workstation 👍

**Comment by jondequinor** [comment]
Might be proxy yes, I have not disabled proxy for ERT, maybe I should?

**Comment by sondreso** [comment]
Worth a try to see if that fixes the problem, but we should try to handle this a little more gracefully!

**Comment by oysteoh** [comment]
i will investigate - but atm it's slightly cumbersome debugging working from home.... 👍
