### ISSUE TITLE
New storage: 'KeyManager' object has no attribute 'gen_kw_priors'

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#1027]
```
Exception in thread ert_gui_simulation_thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/private/zom/env/venv/lib64/python3.6/site-packages/ert_gui/simulation/run_dialog.py", line 161, in run
    self._run_model.startSimulations( self._simulations_argments )
  File "/private/zom/env/venv/lib64/python3.6/site-packages/ert_shared/models/base_run_model.py", line 71, in startSimulations
    run_context = self.runSimulations(arguments)
  File "/private/zom/env/venv/lib64/python3.6/site-packages/ert_shared/models/single_test_run.py", line 17, in runSimulations
    return self.runSimulations__( arguments  , "Running single realisation test ...")
  File "/private/zom/env/venv/lib64/python3.6/site-packages/ert_shared/models/ensemble_experiment.py", line 36, in runSimulations__
    dump_to_new_storage()
  File "/private/zom/env/venv/lib64/python3.6/site-packages/ert_shared/feature_toggling.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/private/zom/env/venv/lib64/python3.6/site-packages/ert_shared/storage/extraction_api.py", line 231, in dump_to_new_storage
    priors = _extract_and_dump_priors(rdb_api=rdb_api) if reference is None else []
  File "/private/zom/env/venv/lib64/python3.6/site-packages/ert_shared/storage/extraction_api.py", line 268, in _extract_and_dump_priors
    gen_kw_priors = facade.gen_kw_priors()
  File "/private/zom/env/venv/lib64/python3.6/site-packages/ert_shared/libres_facade.py", line 222, in gen_kw_priors
    return self._enkf_main.getKeyManager().gen_kw_priors()
AttributeError: 'KeyManager' object has no attribute 'gen_kw_priors'
```

**Comment by jondequinor** [comment]
Could you add information about how to reproduce?

**Comment by oysteoh** [comment]
@dotfloat have you seen this error again? I cannot reproduce. `KeyManager` for sure has the `gen_kw_priors()`. With regards to the line reference 222 in `libres_facade.py` i cannot find this. Are you sure you was operating on a new `ert` version?

**Comment by dotfloat** [comment]
Not sure. I reckon we can close this issue.
