### ISSUE TITLE
Plotting errors:

### ISSUE THREAD

**Issue by stefoss23** [equinor/ert#106]
There are many ValueErrors when creating plots. 

The following procedure results in ValueError exceptions:

1) Start gui_test
2) press Start Simulation button (single realization test run)
3) select Yes
4) Wait until simulation is completed
5) press Create Plot button

As well a printing a curve, multiple ValueError messages are printed. Also selecting different plots results in the same curve( FGOR plot = TIME plot):

Traceback (most recent call last):
  File "/private/stefos/ert/ert/build/lib/python2.7/site-packages/ert_gui/tools/plot/data_type_keys_list_model.py", line 46, in data
    if self.keyManager().isKeyWithObservations(item):
  File "/private/stefos/ert/install/lib/python2.7/site-packages/res/enkf/key_manager.py", line 157, in isKeyWithObservations
    return key in self.allDataTypeKeysWithObservations()
  File "/private/stefos/ert/install/lib/python2.7/site-packages/res/enkf/key_manager.py", line 151, in allDataTypeKeysWithObservations
    self.__all_keys_with_observations = self.summaryKeysWithObservations() + self.genDataKeysWithObservations()
  File "/private/stefos/ert/install/lib/python2.7/site-packages/res/enkf/key_manager.py", line 115, in genDataKeysWithObservations
    report_step = obs_vector.activeStep()
  File "/private/stefos/ert/install/lib/python2.7/site-packages/res/enkf/observations/obs_vector.py", line 113, in activeStep
    raise ValueError("The activeStep() method can *ONLY* be called for obervations with one active step")

**Comment by stefoss23** [comment]
And, this has been fixed in the waiting-to-be-merged libres pr 293.

**Comment by ManInFez** [comment]
293 was merged! closing issue :)
