### ISSUE TITLE
Running pytest twice simultaneously

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#1281]
We don't have the ability to isolate Jenkins runs and this could give us false-positive errors due to us trying to bind to the same address. 

```
WARNING:root:The new ensemble evaluator is experimental! The new evaluator will offer the user an expressive, high-level configuration system in YAML, as well as evaluating ensembles in a concurrent, cloud-ready and distributed way.
Exception in thread ert_ee_run_server:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zohar/Equinor/ert/ert_shared/ensemble_evaluator/evaluator.py", line 197, in _run_server
    asyncio.get_event_loop().run_until_complete(server_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/zohar/Equinor/ert/ert_shared/ensemble_evaluator/evaluator.py", line 171, in evaluator_server
    async with websockets.serve(
  File "/home/zohar/Equinor/ert/venv/lib/python3.8/site-packages/websockets/server.py", line 947, in __aenter__
    return await self
  File "/home/zohar/Equinor/ert/venv/lib/python3.8/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8765): address already in use
```

I have written the following for the Storage server, which we could make nicer and bring up as the only way to bind to an available ERT port:
https://github.com/equinor/ert/blob/b27c10f82bee09ba3134506e2302cc5848d22afa/ert_shared/storage/main.py#L43-L63

**Comment by markusdregi** [comment]
Is this still an issue @dotfloat?

**Comment by dotfloat** [comment]
I think ERT now uses unused ports for the testing. @sondreso can you close this issue if that is the case?
