### ISSUE TITLE
When plotting an response which exists in one ensemble, then add a second ensemble without this

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#1364]
I'm not entirely sure it could / should happen that a response is available in one ensemble but not another. Nevertheless - if you have selected one response, then add another ensemble to your chart which does not have this, there is printed a stacktrace in the console. 

```
ERROR:webviz_app:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/dash/dash.py", line 1059, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/dash/dash.py", line 994, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/ertviz/controllers/multi_response_controller.py", line 155, in update_graph
    for realization in plot._realization_plots:
AttributeError: 'NoneType' object has no attribute '_realization_plots'

```

**Comment by oysteoh** [comment]
wrong project
