### ISSUE TITLE
Illegal field in snapshot recursive_merge

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1385]
**Describe the bug**
IES with default options fails on the first iteration due to

```
All 100 active jobs complete and data loaded.

Iter 0 --> 1
Wd: 14.22  2.50  0.55 

Traceback (most recent call last):
  File "/private/jond/work/ert/ert_gui/simulation/tracker_worker.py", line 30, in consume_and_emit
    for event in self._tracker.track():
  File "/private/jond/work/ert/ert_shared/status/tracker/legacy.py", line 101, in track
    yield from self._retroactive_update_event()
  File "/private/jond/work/ert/ert_shared/status/tracker/legacy.py", line 208, in _retroactive_update_event
    None, ({}, -1), iter_, queue_snapshot=changes
  File "/private/jond/work/ert/ert_shared/status/tracker/legacy.py", line 280, in _create_partial_snapshot
    str(iens), status=queue_status_to_real_state(change_enum)
  File "/private/jond/work/ert/ert_shared/ensemble_evaluator/entity/snapshot.py", line 76, in update_real
    self._apply_update({ids.REALS: {real_id: real}})
  File "/private/jond/work/ert/ert_shared/ensemble_evaluator/entity/snapshot.py", line 118, in _apply_update
    self._snapshot.merge(update)
  File "/private/jond/work/ert/ert_shared/ensemble_evaluator/entity/snapshot.py", line 295, in merge
    self._data = recursive_update(self._data, update)
  File "/private/jond/work/ert/ert_shared/ensemble_evaluator/entity/tool.py", line 15, in recursive_update
    left = left.set(k, recursive_update(d_val, v, check_key))
  File "/private/jond/work/ert/ert_shared/ensemble_evaluator/entity/tool.py", line 9, in recursive_update
    raise ValueError(f"Illegal field {k}")
ValueError: Illegal field 32735
Aborted (core dumped)

```

**To Reproduce**
You most likely need the refactor-out-queue-from-gui branch
1. Run default ERT IES

**Expected behavior**
This should probably not crash like that

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: stable+pip install -e from git
 - Python version: 3.6
 - Remote/HPC execution involved: no

**Comment by jondequinor** [comment]
`32735` is the first part of the tuple returned from doing `enumerate(run_context)`, i.e. the `iens` in libres terms.

**Comment by jondequinor** [comment]
Happens for ES MDA as well.
