### ISSUE TITLE
Gather resources in <workspace>/bin fails

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1429]
**Describe the bug**
When setting up the SPE1 example I wanted to gather all the scripts in `<workspace>/steps/bin` or something similar. However this fails with

```
(env) glados:polynomial mfane$ rm -rf .ert; ert3 init; ert3 run evaluation
An exception occurred while starting the ensemble evaluation
Traceback (most recent call last):
  File "/Users/mfane/Development/ert/ert_shared/ensemble_evaluator/prefect_ensemble/prefect_ensemble.py", line 288, in _evaluate
    self.run_flow(ee_id, dispatch_url, input_files)
  File "/Users/mfane/Development/ert/ert_shared/ensemble_evaluator/prefect_ensemble/prefect_ensemble.py", line 318, in run_flow
    flow = self.get_flow(ee_id, dispatch_url, input_files, realization_range)
  File "/Users/mfane/Development/ert/ert_shared/ensemble_evaluator/prefect_ensemble/prefect_ensemble.py", line 226, in get_flow
    + self.store_resources(step["resources"]),
  File "/Users/mfane/Development/ert/ert_shared/ensemble_evaluator/prefect_ensemble/prefect_ensemble.py", line 326, in store_resources
    stored_resources = [storage.store(res) for res in resources]
  File "/Users/mfane/Development/ert/ert_shared/ensemble_evaluator/prefect_ensemble/prefect_ensemble.py", line 326, in <listcomp>
    stored_resources = [storage.store(res) for res in resources]
  File "/Users/mfane/Development/ert/ert_shared/ensemble_evaluator/prefect_ensemble/storage_driver.py", line 27, in store
    shutil.copyfile(self._run_path / local_name, storage_uri)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mfane/Development/ert/examples/polynomial/.ert/tmp/evaluation/.my_storage/global/bin/poly.py'
Task exception was never retrieved
```

**To Reproduce**
1. `pip install ert`
2. `cd examples/polynomial; mkdir bin; mv poly.py bin/`
3. Replace `poly.py` with `bin/poly.py` in `stages.yml`
4. `ert3 init; ert3 run evaluation`

**Expected behavior**
Running in the exact same manner as before changing the workspace.

**Enviromment**
 - OS: MacOS
 - ERT/Komodo Release: master
 - Python version: 3.7
 - Remote/HPC execution involved: no

**Comment by dotfloat** [comment]
Do we expect the working directory to be the user's `$PWD`, or where the config scripts are located? Seems a bit ambigious.

**Comment by markusdregi** [comment]
I would expect the path given in the `stages.yml` file to be interpreted relative to the workspace root (which as of now is the same as the location of the `stages.yml` file).
