### ISSUE TITLE
Build fails on mac with python 3.7 in test_engine.py

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#1459]
This seems to happen some of the times in the tests test_export_uniform_polynomial and test_export_uniform_polynomial_evaluation
```
2021-02-25T12:26:32.8666040Z =================================== FAILURES ===================================
2021-02-25T12:26:32.8666590Z __________________ test_export_uniform_polynomial_evaluation ___________________
2021-02-25T12:26:32.8666980Z 
2021-02-25T12:26:32.8669510Z workspace = local('/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-runner/pytest-0/test_export_uniform_polynomial0/polynomial')
2021-02-25T12:26:32.8671980Z uniform_ensemble = EnsembleConfig(validate_all=True, validate_assignment=True, extra='forbid', allow_mutation=False, arbitrary_types_allo...tation=False, arbitrary_types_allowed=True, source='stochastic.uniform_coefficients', record='coefficients')], size=10)
2021-02-25T12:26:32.8674710Z stages_config = StagesConfig(__root__=[Step(validate_all=True, validate_assignment=True, extra='forbid', allow_mutation=False, arbitra...ue, extra='forbid', allow_mutation=False, arbitrary_types_allowed=True, name='poly', location=PosixPath('poly.py'))])])
2021-02-25T12:26:32.8677040Z evaluation_experiment_config = ExperimentConfig(validate_all=True, validate_assignment=True, extra='forbid', allow_mutation=False, arbitrary_types_allowed=True, type='evaluation', algorithm=None)
2021-02-25T12:26:32.8678160Z uniform_parameters_file = None
2021-02-25T12:26:32.8678470Z 
2021-02-25T12:26:32.8678910Z     def test_export_uniform_polynomial_evaluation(
2021-02-25T12:26:32.8679410Z         workspace,
2021-02-25T12:26:32.8679820Z         uniform_ensemble,
2021-02-25T12:26:32.8680210Z         stages_config,
2021-02-25T12:26:32.8680650Z         evaluation_experiment_config,
2021-02-25T12:26:32.8681150Z         uniform_parameters_file,
2021-02-25T12:26:32.8681500Z     ):
2021-02-25T12:26:32.8682120Z         uni_dir = workspace / ert3.workspace.EXPERIMENTS_BASE / "uniform_evaluation"
2021-02-25T12:26:32.8682840Z         uni_dir.ensure(dir=True)
2021-02-25T12:26:32.8683270Z         ert3.engine.run(
2021-02-25T12:26:32.8683700Z             uniform_ensemble,
2021-02-25T12:26:32.8684090Z             stages_config,
2021-02-25T12:26:32.8684540Z             evaluation_experiment_config,
2021-02-25T12:26:32.8684980Z             workspace,
2021-02-25T12:26:32.8685360Z >           "uniform_evaluation",
2021-02-25T12:26:32.8685720Z         )
2021-02-25T12:26:32.8685920Z 
2021-02-25T12:26:32.8686440Z /Users/runner/work/ert/ert/tests/ert3/engine/integration/test_engine.py:210: 
2021-02-25T12:26:32.8687030Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2021-02-25T12:26:32.8687530Z /Users/runner/work/ert/ert/ert3/engine/_run.py:139: in run
2021-02-25T12:26:32.8688250Z     _evaluate(ensemble, stages_config, workspace_root, experiment_name)
2021-02-25T12:26:32.8688980Z /Users/runner/work/ert/ert/ert3/engine/_run.py:124: in _evaluate
2021-02-25T12:26:32.8690100Z     workspace_root, experiment_name, parameters, ensemble, stages_config
2021-02-25T12:26:32.8691120Z /Users/runner/work/ert/ert/ert3/evaluator/_evaluator.py:162: in evaluate
2021-02-25T12:26:32.8691920Z     results = _fetch_results(ee_config, ensemble_config, stages_config)
2021-02-25T12:26:32.8692470Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2021-02-25T12:26:32.8692710Z 
2021-02-25T12:26:32.8694370Z ee_config = {'executor': 'local', 'input_files': {0: (PosixPath('/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-o...ial/.ert/tmp/uniform_evaluation/.my_storage/3/coefficients.json'),), ...}, 'max_retries': 0, 'max_running': 10000, ...}
2021-02-25T12:26:32.8696870Z ensemble = EnsembleConfig(validate_all=True, validate_assignment=True, extra='forbid', allow_mutation=False, arbitrary_types_allo...tation=False, arbitrary_types_allowed=True, source='stochastic.uniform_coefficients', record='coefficients')], size=10)
2021-02-25T12:26:32.8699590Z stages_config = StagesConfig(__root__=[Step(validate_all=True, validate_assignment=True, extra='forbid', allow_mutation=False, arbitra...ue, extra='forbid', allow_mutation=False, arbitrary_types_allowed=True, name='poly', location=PosixPath('poly.py'))])])
2021-02-25T12:26:32.8700670Z 
2021-02-25T12:26:32.8701140Z     def _fetch_results(ee_config, ensemble, stages_config):
2021-02-25T12:26:32.8701820Z         _assert_single_stage_forward_model(stages_config, ensemble)
2021-02-25T12:26:32.8702300Z     
2021-02-25T12:26:32.8702590Z         results = []
2021-02-25T12:26:32.8703150Z         ee_storage = storage_driver_factory(ee_config["storage"], ee_config["run_path"])
2021-02-25T12:26:32.8703830Z         for iens in range(ee_config["realizations"]):
2021-02-25T12:26:32.8704460Z             spath = pathlib.Path(ee_storage.get_storage_path(iens))
2021-02-25T12:26:32.8705040Z             realization_results = {}
2021-02-25T12:26:32.8705390Z     
2021-02-25T12:26:32.8705870Z             stage_name = ensemble.forward_model.stages[0]
2021-02-25T12:26:32.8706500Z             stage = stages_config.step_from_key(stage_name)
2021-02-25T12:26:32.8707060Z             for output_elem in stage.output:
2021-02-25T12:26:32.8707610Z >               with open(spath / output_elem.location) as f:
2021-02-25T12:26:32.8709510Z E               FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-runner/pytest-0/test_export_uniform_polynomial0/polynomial/.ert/tmp/uniform_evaluation/.my_storage/1/output.json'
2021-02-25T12:26:32.8710600Z 
2021-02-25T12:26:32.8711180Z /Users/runner/work/ert/ert/ert3/evaluator/_evaluator.py:119: FileNotFoundError
2021-02-25T12:26:32.8712370Z ------------------------------ Captured log call -------------------------------
2021-02-25T12:26:32.8713170Z ERROR    websockets.server:server.py:193 Error in connection handler
2021-02-25T12:26:32.8713800Z Traceback (most recent call last):
2021-02-25T12:26:32.8715190Z   File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
2021-02-25T12:26:32.8716080Z     message = await self.read_message()
2021-02-25T12:26:32.8717450Z   File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/websockets/protocol.py", line 895, in read_message
2021-02-25T12:26:32.8718400Z     frame = await self.read_data_frame(max_size=self.max_size)
2021-02-25T12:26:32.8719820Z   File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/websockets/protocol.py", line 971, in read_data_frame
2021-02-25T12:26:32.8720700Z     frame = await self.read_frame(max_size)
2021-02-25T12:26:32.8722040Z   File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/websockets/protocol.py", line 1051, in read_frame
2021-02-25T12:26:32.8722920Z     extensions=self.extensions,
2021-02-25T12:26:32.8724230Z   File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/websockets/framing.py", line 105, in read
2021-02-25T12:26:32.8725300Z     data = await reader(2)
2021-02-25T12:26:32.8726250Z   File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/asyncio/streams.py", line 677, in readexactly
2021-02-25T12:26:32.8727210Z     raise IncompleteReadError(incomplete, n)
2021-02-25T12:26:32.8728150Z asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
2021-02-25T12:26:32.8728810Z 
2021-02-25T12:26:32.8729390Z The above exception was the direct cause of the following exception:
2021-02-25T12:26:32.8729840Z 
2021-02-25T12:26:32.8730200Z Traceback (most recent call last):
2021-02-25T12:26:32.8731570Z   File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/websockets/server.py", line 191, in handler
2021-02-25T12:26:32.8732410Z     await self.ws_handler(self, path)
2021-02-25T12:26:32.8733230Z   File "/Users/runner/work/ert/ert/ert_shared/ensemble_evaluator/evaluator.py", line 234, in connection_handler
2021-02-25T12:26:32.8734070Z     await self.handle_dispatch(websocket, path)
2021-02-25T12:26:32.8734940Z   File "/Users/runner/work/ert/ert/ert_shared/ensemble_evaluator/evaluator.py", line 218, in handle_dispatch
2021-02-25T12:26:32.8735660Z     async for msg in websocket:
2021-02-25T12:26:32.8736970Z   File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/websockets/protocol.py", line 439, in __aiter__
2021-02-25T12:26:32.8737800Z     yield await self.recv()
2021-02-25T12:26:32.8739830Z   File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/websockets/protocol.py", line 509, in recv
2021-02-25T12:26:32.8740750Z     await self.ensure_open()
2021-02-25T12:26:32.8742300Z   File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
2021-02-25T12:26:32.8743240Z     raise self.connection_closed_exc()
2021-02-25T12:26:32.8744330Z websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2021-02-25T12:26:32.8745450Z =============================== warnings summary ===============================
2021-02-25T12:26:32.8746730Z /Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/marshmallow/fields.py:198: 11 tests with warnings
2021-02-25T12:26:32.8748930Z   /Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/marshmallow/fields.py:198: RemovedInMarshmallow4Warning: Passing field metadata as a keyword arg is deprecated. Use the explicit `metadata=...` argument instead.
2021-02-25T12:26:32.8750410Z     RemovedInMarshmallow4Warning,
```

**Comment by sondreso** [comment]
I'm thinking that this is most likely due to a crash in the unix step. The above log shows that the evaluator experiences an abnormal connection close from one of the dispatchers, and my guess would be that the client in prefect is closed due to an uncaught exception. The actual crash is caused when the evaluator tries to load the result from the output file, which does not exist (probably because the step crashed). Do you have a link to the entire run? I suspect there might be more log statements during the actual test that might help us.

**Comment by sondreso** [comment]
https://github.com/equinor/ert/runs/1988376386?check_suite_focus=true

**Comment by sondreso** [comment]
What I have found so far: 

The errors in the original post are side effects from errors in the execution of the step. The log in my above comment reveals the following during test execution:
```
[2021-02-26 15:00:30+0000] ERROR - prefect.TaskRunner | Unexpected error: OSError(9, 'Bad file descriptor')
ERROR:prefect.TaskRunner:Unexpected error: OSError(9, 'Bad file descriptor')
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/runner/work/ert/ert/ert_shared/ensemble_evaluator/prefect_ensemble/unix_step.py", line 129, in run
  File "/Users/runner/work/ert/ert/ert_shared/ensemble_evaluator/prefect_ensemble/unix_step.py", line 129, in run
    ee_client.send(to_json(event).decode())
    ee_client.send(to_json(event).decode())
  File "/Users/runner/work/ert/ert/ert_shared/ensemble_evaluator/prefect_ensemble/client.py", line 41, in send
  File "/Users/runner/work/ert/ert/ert_shared/ensemble_evaluator/prefect_ensemble/client.py", line 41, in send
    self.loop.run_until_complete(self._send(msg))
    self.loop.run_until_complete(self._send(msg))
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 475, in run_until_complete
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 475, in run_until_complete
    self.run_forever()
    self.run_forever()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 442, in run_forever
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 442, in run_forever
    self._run_once()
    self._run_once()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 1426, in _run_once
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 1426, in _run_once
    event_list = self._selector.select(timeout)
    event_list = self._selector.select(timeout)
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/selectors.py", line 577, in select
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/selectors.py", line 577, in select
    kev_list = self._kqueue.control(None, max_ev, timeout)
    kev_list = self._kqueue.control(None, max_ev, timeout)
OSError: [Errno 9] Bad file descriptor
OSError: [Errno 9] Bad file descriptor


During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:


Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/prefect/engine/runner.py", line 48, in inner
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
    new_state = method(self, state, *args, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/prefect/engine/task_runner.py", line 869, in get_task_run_state
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/prefect/engine/task_runner.py", line 869, in get_task_run_state
    logger=self.logger,
    logger=self.logger,
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/prefect/utilities/executors.py", line 299, in run_task_with_timeout
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/prefect/utilities/executors.py", line 299, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
    return task.run(*args, **kwargs)  # type: ignore
  File "/Users/runner/work/ert/ert/ert_shared/ensemble_evaluator/prefect_ensemble/unix_step.py", line 147, in run
  File "/Users/runner/work/ert/ert/ert_shared/ensemble_evaluator/prefect_ensemble/unix_step.py", line 147, in run
    ee_client.send(to_json(event).decode())
    ee_client.send(to_json(event).decode())
  File "/Users/runner/work/ert/ert/ert_shared/ensemble_evaluator/prefect_ensemble/client.py", line 13, in __exit__
  File "/Users/runner/work/ert/ert/ert_shared/ensemble_evaluator/prefect_ensemble/client.py", line 13, in __exit__
    self.loop.run_until_complete(self.websocket.close())
    self.loop.run_until_complete(self.websocket.close())
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 475, in run_until_complete
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 475, in run_until_complete
    self.run_forever()
    self.run_forever()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 442, in run_forever
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 442, in run_forever
    self._run_once()
    self._run_once()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 1426, in _run_once
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 1426, in _run_once
    event_list = self._selector.select(timeout)
    event_list = self._selector.select(timeout)
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/selectors.py", line 577, in select
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/selectors.py", line 577, in select
    kev_list = self._kqueue.control(None, max_ev, timeout)
    kev_list = self._kqueue.control(None, max_ev, timeout)
OSError: [Errno 9] Bad file descriptor
OSError: [Errno 9] Bad file descriptor
```

This line seems to be the source of the first `OSError`:
https://github.com/equinor/ert/blob/20c1d0eb44e6e48fca04453a48405c38be788a5e/ert_shared/ensemble_evaluator/prefect_ensemble/client.py#L41

The propagation of the exception eventually hits the `__exit__` function in the context started here:

https://github.com/equinor/ert/blob/20c1d0eb44e6e48fca04453a48405c38be788a5e/ert_shared/ensemble_evaluator/prefect_ensemble/unix_step.py#L121

This function attempts to close the websocket. But as we already know from above, this involves a broken file descriptor, leading to the second `OSError` in the log above: 

https://github.com/equinor/ert/blob/20c1d0eb44e6e48fca04453a48405c38be788a5e/ert_shared/ensemble_evaluator/prefect_ensemble/client.py#L13

From what I have gathered from searching on the internet this OSError seems to come from forking combined with event loops on mac. Since the Prefect ensemble is using multiprocessing, this is not unlikely. (https://stackoverflow.com/a/45468294). 

The original line that originally called send on the prefect client seems to vary between this line: 
https://github.com/equinor/ert/blob/20c1d0eb44e6e48fca04453a48405c38be788a5e/ert_shared/ensemble_evaluator/prefect_ensemble/unix_step.py#L147
and this line:
https://github.com/equinor/ert/blob/20c1d0eb44e6e48fca04453a48405c38be788a5e/ert_shared/ensemble_evaluator/prefect_ensemble/unix_step.py#L114

But I cannot guarantee that other send lines can/have not triggered this error. 

I have not been able to find the reason why all of this happens. I have some ideas for how to mitigate this (Catching the `OSError` in the `run_until_complete` call and guard the closing of the websocket in the same manner, specifying retries > 0 in prefect), but I think we should try to fix the underlying cause.
