### ISSUE TITLE
Illegal field 46 in smoother run

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1476]
**Describe the bug**
ERT crashes

**To Reproduce**
1. smoother run

**Expected behavior**
It should not crash

**Enviromment**
 - ERT/Komodo Release: `testing` release at this date

**Additional context**
Traceback

 ```
[046:0000-0000] FAILED COMPLETELY.
1 active job(s) failed.
Traceback (most recent call last):
  File "/prog/res/komodo/2021.03.rc4-py36-rhel7/root/lib/python3.6/site-packages/ert_gui/simulation/tracker_worker.py", line 30, in consume_and_emit
    for event in self._tracker.track():
  File "/prog/res/komodo/2021.03.rc4-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/status/tracker/legacy.py", line 101, in track
    yield from self._retroactive_update_event()
  File "/prog/res/komodo/2021.03.rc4-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/status/tracker/legacy.py", line 199, in _retroactive_update_event
    partial = self._create_partial_snapshot(None, ({}, -1), iter_)
  File "/prog/res/komodo/2021.03.rc4-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/status/tracker/legacy.py", line 259, in _create_partial_snapshot
    str(iens), status=queue_status_to_real_state(change_enum)
  File "/prog/res/komodo/2021.03.rc4-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/entity/snapshot.py", line 86, in update_real
    self._apply_update({ids.REALS: {real_id: real}})
  File "/prog/res/komodo/2021.03.rc4-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/entity/snapshot.py", line 128, in _apply_update
    self._snapshot.merge(update)
  File "/prog/res/komodo/2021.03.rc4-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/entity/snapshot.py", line 300, in merge
    self._data = recursive_update(self._data, update)
  File "/prog/res/komodo/2021.03.rc4-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/entity/tool.py", line 15, in recursive_update
    left = left.set(k, recursive_update(d_val, v, check_key))
  File "/prog/res/komodo/2021.03.rc4-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/entity/tool.py", line 9, in recursive_update
    raise ValueError(f"Illegal field {k}")
ValueError: Illegal field 46
Aborted (core dumped)
```

**Comment by eivindsm** [comment]
Test case provided at: /scratch/oompf/eism/ert/model/hm_analysis.ert

**Comment by eivindsm** [comment]
Further details: more investigation on my side reveals that realization nr 46 did not finish successfully in the prior ensemble.

**Comment by sondreso** [comment]
I can reproduce this error, but it only seems to happen if exactly one realisation fails

**Comment by sondreso** [comment]
The problem is that the iter is updated on the run model way before the queue is updated. This means that the tracker detects a change in the iter but when it sets a new iteration in `_iter_queue` in the Legacy Tracker it uses the old queue, since this has not been changed yet. This causes the evaluator to crash since it will produce updates for the failed realisation in iteration 1, even though it should not exist.
