### ISSUE TITLE
ERT Installation Not Working - Permission Error

### ISSUE THREAD

**Issue by OPMUSER** [equinor/ert#1537]
**Describe the bug**
ERT installation not working due to a permission error.

**To Reproduce**
1. `pip install ert`
2. `ert -h`

**Expected behavior**
Should list the help options.

**Screenshots**
NA

**Enviromment**
 - OS: Unbuntu 20-04 LTS (VirtualBox VM)
 - ERT - Don't Know
 - Python 3.8.5
 - Remote/HPC execution involved: no

**Additional context**
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.8/logging/config.py", line 744, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/api-log.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/david/.local/bin/ert", line 5, in <module>
    main()
  File "/home/david/.local/lib/python3.8/site-packages/ert_shared/main.py", line 389, in main
    import ert_logging  # Only use ert logger config when running ERT
  File "/home/david/.local/lib/python3.8/site-packages/ert_logging/__init__.py", line 10, in <module>
    logging.config.dictConfig(yaml.safe_load(conf_file))
  File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'apifile'


```

**Comment by markusdregi** [comment]
Thank you for reporting your problem @OPMUSER 👍🏻 

It appears `ert` tries to log to a file for which you do not have write access to... Could you try to reproduce the problem making sure that your current position is one for which you have write access to?
