### ISSUE TITLE
Setting number or realizations different to config crashes storage

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1567]
**Describe the bug**

Running an experiment and in gui setting number or realization different to what is stated in config file produce the following error message:

```python

Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/prog/res/komodo/2021.03.01-py36-rhel7/root/lib/python3.6/site-packages/ert_gui/simulation/run_dialog.py", line 252, in run
    self._run_model.startSimulations(self._simulations_argments)
  File "/prog/res/komodo/2021.03.01-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/models/base_run_model.py", line 79, in startSimulations
    run_context = self.runSimulations(arguments)
  File "/prog/res/komodo/2021.03.01-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/models/ensemble_experiment.py", line 55, in runSimulations
    return self.runSimulations__(arguments, "Running ensemble experiment...")
  File "/prog/res/komodo/2021.03.01-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/models/ensemble_experiment.py", line 24, in runSimulations__
    ensemble_id = post_ensemble_data()
  File "/prog/res/komodo/2021.03.01-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/feature_toggling.py", line 78, in wrapper
    return func(*args, **kwargs)
  File "/prog/res/komodo/2021.03.01-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/storage/extraction.py", line 267, in post_ensemble_data
    raise RuntimeError(response.text)
RuntimeError: {"detail":"Length of Ensemble.parameters[0].values must be 100, got 20"}
```

**To Reproduce**
Set number or realizations in the GUI different to config

**Expected behavior**
Not crash 

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: 2021.03.01
 - Python version: 3.6
 - Remote/HPC execution involved: yes

**Additional context**

**Comment by sondreso** [comment]
This issue is no longer relevant
