### ISSUE TITLE
EE certificate issue in HM-tutorial

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1754]
**Describe the bug**
```
Exception in thread ert_ee_run_server:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/evaluator.py", line 212, in _run_server
    loop.run_until_complete(self.evaluator_server(self._done))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/evaluator.py", line 183, in evaluator_server
    max_size=2 ** 26,
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib64/python3.6/site-packages/websockets/legacy/server.py", line 1053, in __aenter__
    return await self
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib64/python3.6/site-packages/websockets/legacy/server.py", line 1071, in __await_impl__
    server = await self._create_server()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1082, in create_server
    sock.listen(backlog)
OSError: [Errno 98] Address already in use

Exception in thread ert_cli_simulation_thread:
Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib64/python3.6/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 820, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 846, in _create_connection_transport
    yield from waiter
  File "/usr/lib64/python3.6/asyncio/sslproto.py", line 505, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/models/base_run_model.py", line 86, in start_simulations_thread
    self.startSimulations(arguments=arguments)
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/models/base_run_model.py", line 91, in startSimulations
    run_context = self.runSimulations(arguments)
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/models/ensemble_experiment.py", line 56, in runSimulations
    return self.runSimulations__(arguments, "Running ensemble experiment...")
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/models/ensemble_experiment.py", line 32, in runSimulations__
    run_context, ee_config
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/models/base_run_model.py", line 358, in run_ensemble_evaluator
    ee_id=str(uuid.uuid1()).split("-")[0],
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/evaluator.py", line 236, in run_and_get_successful_realizations
    with self.run() as mon:
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/evaluator.py", line 217, in run
    self._ensemble.evaluate(self._config, self._ee_id)
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/entity/ensemble_legacy.py", line 80, in evaluate
    cert=self._config.cert,
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/utils.py", line 71, in wait_for_evaluator
    connection_timeout=connection_timeout,
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/utils.py", line 34, in attempt_connection
    timeout=timeout,
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib64/python3.6/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib64/python3.6/site-packages/aiohttp/client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib64/python3.6/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib64/python3.6/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib64/python3.6/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib64/python3.6/site-packages/aiohttp/connector.py", line 1032, in _create_direct_connection
    client_error=client_error,
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib64/python3.6/site-packages/aiohttp/connector.py", line 973, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 10.217.112.231:51822 ssl:<ssl.SSLContext object at 0x7f90dcbd85f8> [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)]

```

**To Reproduce**
TBD

**Enviromment**
 - https://ci.equinor.com/komodo/job/komodo-test-hm-tutorial/556/consoleFull

**Additional context**
After merging of libres and ERT

**Comment by sondreso** [comment]
Issue has not re-appeared since first report, closing this.
