### ISSUE TITLE
Flaky ert3 test test_run_once_polynomial_evaluation

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1780]
From https://github.com/equinor/ert/runs/2836602912

```
FAILED tests/ert3/engine/integration/test_engine.py::test_run_once_polynomial_evaluation
= 1 failed, 700 passed, 2 skipped, 2 xfailed, 176 warnings in 981.07s (0:16:21) =
[2021-06-16 07:25:15+0000] ERROR - prefect.TaskRunner | Task '4': Exception encountered during task execution!
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/prefect/engine/task_runner.py", line 865, in get_task_run_state
    logger=self.logger,
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/prefect/utilities/executors.py", line 323, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/entity/unix_step.py", line 102, in run
    ev_source=self._step.get_source(self._ee_id),
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/client.py", line 81, in send_event
    self.send(cloudevents.http.to_json(event).decode())
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/client.py", line 68, in send
    self.loop.run_until_complete(self._send(msg))
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/client.py", line 55, in _send
    self.websocket = await self.get_websocket()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/client.py", line 48, in get_websocket
    self.url, ssl=self._ssl_context, extra_headers=self._extra_headers
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 798, in create_connection
    raise exceptions[0]
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 785, in create_connection
    yield from self.sock_connect(sock, address)
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
TimeoutError: [Errno 60] Connect call failed ('10.79.1.15', 51820)
[2021-06-16 07:25:15+0000] ERROR - prefect.TaskRunner | Task '3': Exception encountered during task execution!
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/prefect/engine/task_runner.py", line 865, in get_task_run_state
    logger=self.logger,
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/prefect/utilities/executors.py", line 323, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/entity/unix_step.py", line 102, in run
    ev_source=self._step.get_source(self._ee_id),
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/client.py", line 81, in send_event
    self.send(cloudevents.http.to_json(event).decode())
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/client.py", line 68, in send
    self.loop.run_until_complete(self._send(msg))
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/client.py", line 55, in _send
    self.websocket = await self.get_websocket()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/client.py", line 48, in get_websocket
    self.url, ssl=self._ssl_context, extra_headers=self._extra_headers
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 798, in create_connection
    raise exceptions[0]
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 785, in create_connection
    yield from self.sock_connect(sock, address)
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
TimeoutError: [Errno 60] Connect call failed ('10.79.1.15', 51820)
[2021-06-16 07:25:15+0000] ERROR - prefect.TaskRunner | Task '5': Exception encountered during task execution!
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/prefect/engine/task_runner.py", line 865, in get_task_run_state
    logger=self.logger,
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/prefect/utilities/executors.py", line 323, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/entity/unix_step.py", line 102, in run
    ev_source=self._step.get_source(self._ee_id),
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/client.py", line 81, in send_event
    self.send(cloudevents.http.to_json(event).decode())
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/client.py", line 68, in send
    self.loop.run_until_complete(self._send(msg))
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/client.py", line 55, in _send
    self.websocket = await self.get_websocket()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/client.py", line 48, in get_websocket
    self.url, ssl=self._ssl_context, extra_headers=self._extra_headers
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 798, in create_connection
    raise exceptions[0]
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 785, in create_connection
    yield from self.sock_connect(sock, address)
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
TimeoutError: [Errno 60] Connect call failed ('10.79.1.15', 51820)
Error: The operation was canceled.

```

**Comment by sondreso** [comment]
This has not resurfaced since the original report, closing this as the code has changed quite substantially since June. We should re-open if this happens again.
