### ISSUE TITLE
ensemble_evaluator verification tests are flaky

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1819]
**Describe the bug**

```
  Traceback (most recent call last):
    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.9/threading.py", line 892, in run
      self._target(*self._args, **self._kwargs)
    File "/work/ert/ert_shared/ensemble_evaluator/narratives/narrative.py", line 412, in _sync_listener
      self._loop.run_until_complete(self._mock_listener(on_connect))
    File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
      return future.result()
    File "/work/ert/ert_shared/ensemble_evaluator/narratives/narrative.py", line 399, in _mock_listener
      async with websockets.connect(self._uri) as websocket:
    File "/work/foo/lib/python3.9/site-packages/websockets/legacy/client.py", line 604, in __aenter__
      return await self
    File "/work/foo/lib/python3.9/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
      transport, protocol = await self._create_connection()
    File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
      raise exceptions[0]
    File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
      sock = await self._connect_sock(
    File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
      await self.sock_connect(sock, address)
    File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
      return await fut
    File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
      raise OSError(err, f'Connect call failed {address}')
  ConnectionRefusedError: [Errno 111] Connect call failed ('172.17.0.2', 44081)

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

```

**To Reproduce**
1. `pytest -sxv --count=1000 tests/ensemble_evaluator/test_ensemble_evaluator.py::test_verify_monitor_failing_ensemble`

**Expected behavior**
The tests should pass

**Enviromment**
 - OS: Ubuntu 20.04
 - ERT/Komodo Release: HEAD
 - Python version: 3.9

**Additional context**
Seems to only affect python 3.9

**Comment by jondequinor** [comment]
I thought maybe this was a case of the health check endpoint becoming available before the websocket is up, but couldn't repro with this https://gist.github.com/jondequinor/db69913aa1261f50f0b402ac3085dc60 on ubuntu @ python3.9
