### ISSUE TITLE
Improved error handling / feedback to users from shell forward models

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#1896]
Forward model components, move_file, copy_file etc could be more verbose when encountering  common issues such as missing files. Example from move_file, after user has messed up and <FROM> is missing:
Traceback (most recent call last):
  File "/prog/res/komodo/2020.02.rc3-py27/root/share/ert/forward-models/shell/script/move_file", line 10, in <module>
    move_file(src, target)
  File "/prog/res/komodo/2020.02.rc3-py27/root/lib/python2.7/site-packages/res/fm/shell/__init__.py", line 10, in move_file
    Shell.moveFile(src_file , target)
  File "/prog/res/komodo/2020.02.rc3-py27/root/lib/python2.7/site-packages/res/fm/shell/shell.py", line 91, in moveFile
    raise IOError("Input argument %s is not an existing file" % src_file )
IOError: Input argument relperm.inc is not an existing file

I suggest that a helpful and human comprehensible message is propagated to stdout

**Comment by markusdregi** [comment]
The forward models could also write an confirming success message to stdout upon success.

**Comment by oyvindeide** [comment]
Think the solution looks good, but maybe the traceback is not needed in `stdout`?
