### ISSUE TITLE
phase_count variable in iterated_ensemble_smoother.py

### ISSUE THREAD

**Issue by geirev** [equinor/ert#264]
**I think there is introduced a bug in ert related to iterated_ensemble_smoother.**

Traceback (most recent call last):
  File "/private/geve/ERT/installation/lib/python2.7/site-packages/ert_gui/simulation/simulation_panel.py", line 107, in runSimulation
    dialog = RunDialog(run_model(), self)
  File "/private/geve/ERT/installation/lib/python2.7/site-packages/ert_gui/simulation/models/iterated_ensemble_smoother.py", line 10, in __init__
    super(IteratedEnsembleSmoother, self).__init__("Iterated Ensemble Smoother", getQueueConfig() , phase_count=2)
TypeError: __init__() got multiple values for keyword argument 'phase_count'

**I assume it is related to the update in the attached diff.**
[diffs.txt](https://github.com/equinor/ert/files/2952053/diffs.txt)

**Comment by joakim-hove** [comment]
Possible fix here: https://github.com/equinor/ert/pull/265
