### ISSUE TITLE
Flakyness in coverage test:

### ISSUE THREAD

**Issue by joakim-hove** [equinor/ert#3023]
I have repeatedly got this:
```Python
Error:       raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/ert_tests/ert3/algorithms/test_fast.py::test_single_evaluation[distribution0]
  /opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object _LegacyEnsemble.setup_timeout_callback.<locals>.send_timeout_message at 0x7fb67bd2e840>
  
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/asyncio/queues.py", line 166, in get
      await getter
  GeneratorExit
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/ert_shared/ensemble_evaluator/ensemble/legacy.py", line 62, in send_timeout_message
      timeout_cloudevent = await timeout_queue.get()
    File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/asyncio/queues.py", line 168, in get
      getter.cancel()  # Just in case getter is not done yet.
    File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
      self._check_closed()
    File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
```
on the coverage test.

**Comment by BjarneHerland** [comment]
Can you point to a PR or two where this occurs? Or is this with local testing?

**Comment by jondequinor** [comment]
In `_cancel` in the legacy ensemble, we do not cancel `send_timeout_future`, which is most likely the source of this exception.
