### ISSUE TITLE
Failing test_ensemble_evaluator_run_and_get_successful_realizations_connection_closed_no_recover

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#3137]
**Describe the bug**
Possible flaky test

**Expected behavior**
Tests passing

**Enviromment**
 - Github actions unit tests
 - OS: [macos-latest]
 - Python version 3.6

**Additional context**

Failing github actions: https://github.com/equinor/ert/runs/5627923157
```
=================================== FAILURES ===================================
_ test_ensemble_evaluator_run_and_get_successful_realizations_connection_closed_no_recover[10-5] _

make_ee_config = <function make_ee_config.<locals>._ee_config at 0x141082158>
num_realizations = 10, num_failing = 5

    @pytest.mark.parametrize("num_realizations, num_failing", [(10, 5), (10, 10)])
    def test_ensemble_evaluator_run_and_get_successful_realizations_connection_closed_no_recover(
        make_ee_config, num_realizations, num_failing
    ):
        ee_config = make_ee_config(use_token=False, generate_cert=False)
        ensemble = AutorunTestEnsemble(iter=1, reals=num_realizations, steps=1, jobs=2)
        for i in range(num_failing):
            ensemble.addFailJob(real=i, step=0, job=1)
        ee = EnsembleEvaluator(ensemble, ee_config, 0, ee_id="0")
        with patch.object(
            _Monitor,
            "track",
            side_effect=[get_connection_closed_excpetion()] * 2
            + [ConnectionRefusedError("Connection error")]
            + [dummy_iterator("DUMMY TRACKING ITERATOR")]
            + [get_connection_closed_excpetion()] * 2
            + [ConnectionRefusedError("Connection error")] * 3
            + [
                "DUMMY TRACKING ITERATOR2"
            ],  # This should not be reached, hence we assert call_count == 9
        ) as mock:
            num_successful = ee.run_and_get_successful_realizations()
            assert mock.call_count == 9
>       assert num_successful == num_realizations - num_failing
E       assert 0 == 5
E         +0
E         -5

ert_tests/ensemble_evaluator/test_ensemble_evaluator.py:338: AssertionError
------------------------------ Captured log call -------------------------------
ERROR    websockets.server:server.py:295 Error in connection handler
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/websockets/legacy/protocol.py", line 750, in transfer_data
    message = await self.read_message()
  File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/websockets/legacy/protocol.py", line 819, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/websockets/legacy/protocol.py", line 895, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/websockets/legacy/protocol.py", line 975, in read_frame
    extensions=self.extensions,
  File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/websockets/legacy/framing.py", line 55, in read
    data = await reader(2)
  File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/asyncio/streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/websockets/legacy/server.py", line 293, in handler
    await self.ws_handler(self, path)
  File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/evaluator.py", line 168, in connection_handler
    await self.handle_client(websocket, path)
  File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/ert_shared/ensemble_evaluator/evaluator.py", line 117, in handle_client
    async for message in websocket:
  File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/websockets/legacy/protocol.py", line 356, in __aiter__
    yield await self.recv()
  File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/websockets/legacy/protocol.py", line 421, in recv
    await self.ensure_open()
  File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by BjarneHerland** [comment]
Also saw this [here](https://github.com/equinor/ert/runs/5665752475?check_suite_focus=true) but I believe it was fixed by https://github.com/equinor/ert/commit/32b4350c0694418d12042905c1af6da189827000

**Comment by BjarneHerland** [comment]
Not fixed - see  https://github.com/equinor/ert/runs/5679288527?check_suite_focus=true

**Comment by BjarneHerland** [comment]
https://github.com/equinor/ert/runs/5677479268?check_suite_focus=true

**Comment by lars-petter-hauge** [comment]
Another failure https://ci.equinor.com/scout/job/komodo_testing/job/ert-custom-script-pr/11135/console

**Comment by sondreso** [comment]
> I'm primed for fixing this. @sondreso ok?
Go, go, go!

**Comment by jondequinor** [comment]
This is actually a mix of 
`test_ensemble_evaluator_run_and_get_successful_realizations_connection_closed_no_recover`
and 
`test_ensemble_evaluator_run_and_get_successful_realizations_connection_closed_recover`

I suggest changing the name of these tests.
