### ISSUE TITLE
GUI - error message

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#317]
Stack trace from user clicking around in the GUI after all the realizations had finished:

```
Traceback (most recent call last):
 File "/project/res/komodo/2019.04.01/root/lib/python2.7/site-packages/ert_gui/simulation/run_dialog.py", line 166, in updateRunStatus
   if self.checkIfRunFinished():
 File "/project/res/komodo/2019.04.01/root/lib/python2.7/site-packages/ert_gui/simulation/run_dialog.py", line 155, in checkIfRunFinished
   self.update_realizations_view()
 File "/project/res/komodo/2019.04.01/root/lib/python2.7/site-packages/ert_gui/simulation/run_dialog.py", line 300, in update_realizations_view
   for (index, successful) in enumerate(completed):
TypeError: 'NoneType' object is not iterable
```

**Comment by ManInFez** [comment]
This has been resolved in previous commit:

https://github.com/equinor/ert/commit/f3eaf7e4bce3a115a4cac7b726ae26a233d3fdde
