### ISSUE TITLE
Ert hangs on exit, possibly because it can't log

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#3369]
**Describe the bug**
After running a case in St. John, and having killed the simulation before it finished, upon exiting ert, there was a stack trace, and no exit.
```

Exception in thread FMUAzureLogHandler Worker:
Traceback (most recent call last):
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.6/ssl.py", line 971, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 833, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 590, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='norwaywest-0.in.applicationinsights.azure.com', port=443): Read timed out. (read timeout=10.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/opencensus/ext/azure/common/transport.py", line 88, in _transmit
    allow_redirects=False,
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='norwaywest-0.in.applicationinsights.azure.com', port=443): Read timed out. (read timeout=10.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/opencensus/ext/azure/log_exporter/__init__.py", line 138, in run
    dst._export(batch)
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/opencensus/ext/azure/log_exporter/__init__.py", line 86, in _export
    self._transmit_from_storage()
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/opencensus/ext/azure/common/transport.py", line 51, in _transmit_from_storage
    result = self._transmit(envelopes)
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/opencensus/ext/azure/common/transport.py", line 92, in _transmit
    'Request time out. Ingestion may be backed up. Retrying.')
  File "/usr/lib64/python3.6/logging/__init__.py", line 1320, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib64/python3.6/site-packages/ert_gui/tools/event_viewer/panel.py", line 24, in emit
    self.append_log_statement.emit(msg)
RuntimeError: wrapped C/C++ object of type GUILogHandler has been deleted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib/python3.6/site-packages/opencensus/ext/azure/log_exporter/__init__.py", line 140, in run
    logger.exception('Unhandled exception from exporter.')
  File "/usr/lib64/python3.6/logging/__init__.py", line 1343, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1337, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/prog/res/komodo/2022.05.00-py36-rhel7/root/lib64/python3.6/site-packages/ert_gui/tools/event_viewer/panel.py", line 24, in emit
    self.append_log_statement.emit(msg)
RuntimeError: wrapped C/C++ object of type GUILogHandler has been deleted
```

**To Reproduce**
1. Log on to St John
2. Source komodo stable (2022.05.00-py36)
3. `ert gui my_config.ert` (ask me or @oysteoh  for exact path if needed)
4. Run experiment with only real 0 enabled
5. Stop simulation before it finishes
6. Close windows

**Expected behavior**
Ert exits

**Screenshots**

**Enviromment**
 - RHEL7
 - ERT/Komodo Release: komodo stable (2022.05.00-py36)
 - Remote/HPC execution involved: yes

**Comment by sondreso** [comment]
The lifecycle of the logger has been adjusted, and should have solved this bug. Feel free to reopen if it happens again 🙂
