### ISSUE TITLE
Exception on on exit 

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#340]
Exiting ert creates an exception:

```
Exception TypeError: 'super() argument 1 must be type, not None' in <bound method EnkfFsManager.__del__ of EnkfFsManager() at 0x55dac9e06a90> ignored
Exception AttributeError: "'NoneType' object has no attribute 'PY2'" in <object repr() failed> ignored
```

**Comment by MohamedElsuezy** [comment]
any work around for this ?
I have been trying to run gui but this error appears

**Comment by markusdregi** [comment]
Is this still relevant?

**Comment by andreabrambilla** [comment]
I still regularly see this error when closing ert gui. It happens only when closing, so possibly not a very high priority issue for our users

**Comment by jondequinor** [comment]
Not sure if this is the same issue, but here is a reliable way of reproducing:

1. Run Ert GUI
1. Select simulation mode: "Ensemble Experiment"
1. Focus/click the `Active realizations` input box
1. Exit

You get

```
Traceback (most recent call last):
  File "/data/work/ert/ert_gui/ertwidgets/stringbox.py", line 78, in stringBoxChanged
    self._model.setValue(text)
  File "/data/work/ert/ert_gui/ertwidgets/models/activerealizationsmodel.py", line 41, in setValue
    if active_realizations is None or active_realizations.strip() == "" or active_realizations == self.getDefaultValue():
  File "/data/work/ert/ert_gui/ertwidgets/models/activerealizationsmodel.py", line 54, in getDefaultValue
    size = getRealizationCount()
  File "/data/work/ert/ert_gui/ertwidgets/models/ertmodel.py", line 12, in getRealizationCount
    return ERT.enkf_facade.get_ensemble_size()
AttributeError: 'NoneType' object has no attribute 'get_ensemble_size'
```

**Comment by jondequinor** [comment]
Not sure how it relates to https://github.com/equinor/ert/issues/534

**Comment by markusdregi** [comment]
Spawned a new dedicated issue #555
