### ISSUE TITLE
Killing simulations when realizations are down

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#341]
A user reports errors when trying to kill simulations in the _GUI_ for a run where he also logged in to the grid and killed some of the realizations prior to this.

```
CTraceback (most recent call last):
 File "/project/res/komodo/2019.04.00/root/lib/python2.7/site-packages/ert_gui/simulation/run_dialog.py", line 234, in killJobs
   if self._run_model.killAllSimulations():
 File "/project/res/komodo/2019.04.00/root/lib/python2.7/site-packages/ert_gui/simulation/models/base_run_model.py", line 22, in dispatch
   return method( self, *args , **kwargs)
 File "/project/res/komodo/2019.04.00/root/lib/python2.7/site-packages/ert_gui/simulation/models/base_run_model.py", line 92, in killAllSimulations
   self._job_queue.killAllJobs()
 File "/project/res/komodo/2019.04.00/root/lib/python2.7/site-packages/res/job_queue/queue.py", line 217, in killAllJobs
   time.sleep(0.1)
KeyboardInterrupt
```

**Comment by markusdregi** [comment]
Could be that some user feedback when you start killing realizations would be beneficial here.

**Comment by jondequinor** [comment]
Should it also be possible to reproduce locally by running the poly case with some sleep in it, killing one "manually"?

**Comment by markusdregi** [comment]
In the hope of a better future.
