### ISSUE TITLE
installing in `editable` mode doesn't work anymore

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#3760]
**Describe the bug**
Installing ert in editable mode, for development, and then trying to run it produces an error.

**To reproduce**
Steps to reproduce the behaviour:
* follow the instructions in the readme to the dot for installing ert for development
* navigate to some test data, e.g. `test-data/local/snake_oil`
* run `ert vis --experimental-mode snake_oil.ert`
* see a stacktrace (see below) that finishes with

```
ModuleNotFoundError: No module named 'res._lib'
```
**Expected behaviour**
Webviz-ert starts up in a browser

**Environment**
 - OS: Ubuntu 22.04 LTS
 - ERT/Komodo release: commit 39db40af55c2bf69bd5
 - Python version: 3.10.4
 - Remote/HPC execution involved: no

**Additional context**

Before the install I prepared a clean environment by:

- cloning ert from github into an empty directory
- creating a new virtual environment

The complete stack trace is:

```
$ ert vis --experimental-mode snake_oil.ert                                                                                                        12:57:02
Traceback (most recent call last):
  File "/home/val/code/py-venvs/equinor/ert-test/bin/ert", line 5, in <module>
    from ert_shared.main import main
  File "/home/val/code/equinor/ert-test/src/ert_shared/__init__.py", line 7, in <module>
    from ert_shared.hook_implementations.jobs import (
  File "/home/val/code/equinor/ert-test/src/ert_shared/hook_implementations/__init__.py", line 4, in <module>
    from .workflows import legacy_ertscript_workflow
  File "/home/val/code/equinor/ert-test/src/ert_shared/hook_implementations/workflows/__init__.py", line 4, in <module>
    from .export_misfit_data import ExportMisfitDataJob
  File "/home/val/code/equinor/ert-test/src/ert_shared/hook_implementations/workflows/export_misfit_data.py", line 5, in <module>
    from ert.exceptions import StorageError
  File "/home/val/code/equinor/ert-test/src/ert/__init__.py", line 2, in <module>
    from .libres_facade import LibresFacade
  File "/home/val/code/equinor/ert-test/src/ert/libres_facade.py", line 7, in <module>
    from ert.analysis import ESUpdate, SmootherSnapshot
  File "/home/val/code/equinor/ert-test/src/ert/analysis/__init__.py", line 1, in <module>
    from ._es_update import ErtAnalysisError, ESUpdate, SmootherSnapshot
  File "/home/val/code/equinor/ert-test/src/ert/analysis/_es_update.py", line 8, in <module>
    from ert.analysis import _ies as ies
  File "/home/val/code/equinor/ert-test/src/ert/analysis/_ies/__init__.py", line 3, in <module>
    import res
  File "/home/val/code/equinor/ert-test/src/res/__init__.py", line 64, in <module>
    class ResPrototype(Prototype):
  File "/home/val/code/equinor/ert-test/src/res/__init__.py", line 65, in ResPrototype
    lib = _load_lib()
  File "/home/val/code/equinor/ert-test/src/res/__init__.py", line 35, in _load_lib
    import res._lib
ModuleNotFoundError: No module named 'res._lib'

**Comment by valentin-krasontovitsch** [comment]
Perhaps related, @oysteoh is reporting seeing the following since ab7224e2b1f8af5a3b0cad501b8db082cb162562 [formatted with line-breaks for readability]: 

```
The script                                                                                                                                                              
  '/datadisk/virtualenvs/3.8/lib64/python3.8/site-packages/ert_shared/share/ert/workflows/jobs/internal-gui/scripts/csv_export.py'
  caused an error during load:
ImportError: cannot import name 'ErtPlugin' from 'res.enkf'                                                                               
  (/datadisk/virtualenvs/3.8/lib64/python3.8/site-packages/res/enkf/__init__.py)
The script                                                                                                                                                                       
  '/datadisk/virtualenvs/3.8/lib64/python3.8/site-packages/ert_shared/share/ert/workflows/jobs/internal-gui/scripts/gen_data_rft_export.py'
  caused an error during load:
ImportError: cannot import name 'ErtPlugin' from 'res.enkf'                                                                               
(/datadisk/virtualenvs/3.8/lib64/python3.8/site-packages/res/enkf/__init__.py)  

```

**Comment by oysteoh** [comment]
Above mentioned errors is present due to this commit `ab7224e2b1f8af5a3b0cad501b8db082cb162562`

**Comment by sondreso** [comment]
Solved by https://github.com/equinor/ert/pull/3771
