### ISSUE TITLE
Problem going from iteration 0 to iteration 1

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#4459]

**Comment by frode-aarstad** [comment]
From yammer: 
https://web.yammer.com/main/org/statoil.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjAzODYzNzAzOTAxNzk4NCJ9
```

Hi, I am running an assisted history matching with FIELD parameters. It has been working fine for a long time and I have not done any changes. Yesterday I got this error in the transition between iter-0 and iter-1. Any idea what might have caused it and what I can do to prevent it?

 

Exception in thread ert_gui_simulation_thread:

Traceback (most recent call last):

  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner

    self.run()

  File "/prog/res/komodo/2022.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/simulation/run_dialog.py", line 277, in run

    self._run_model.startSimulations(

  File "/prog/res/komodo/2022.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/models/base_run_model.py", line 186, in startSimulations

    run_context = self.runSimulations(

  File "/prog/res/komodo/2022.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/models/multiple_data_assimilation.py", line 172, in runSimulations

    update_id = self.update(

  File "/prog/res/komodo/2022.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/models/multiple_data_assimilation.py", line 200, in update

    self.facade.smoother_update(run_context)

  File "/prog/res/komodo/2022.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/libres_facade.py", line 49, in smoother_update

    self._es_update.smootherUpdate(prior_context)

  File "/prog/res/komodo/2022.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/analysis/_es_update.py", line 367, in smootherUpdate

    analysis_ES(

  File "/prog/res/komodo/2022.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/analysis/_es_update.py", line 151, in analysis_ES

    temp_storage = _create_temporary_parameter_storage(

  File "/prog/res/komodo/2022.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/analysis/_es_update.py", line 125, in _create_temporary_parameter_storage

    matrix = source_fs.load_parameter(

  File "/prog/res/komodo/2022.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/enkf_fs.py", line 131, in load_parameter

    return update.load_parameter(

KeyError: 'No parameter: aps_Below_Top_Garn_GRF1 in storage'

```

Additional info:

` It was on st-linrgsn192.st.statoil.no. My last successful run was 30.11.2022.`
