### ISSUE TITLE
Ert crashes when the button to configure the analysis module is pressed

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#457]
Ert crashes when the button to configure the analysis module is pressed. (Main window -> Run Analysis ->  Small cogwheel)

```
Traceback (most recent call last):
  File "/private/sonso/repos/ert/ert_gui/ertwidgets/analysismoduleselector.py", line 70, in showVariablesPopup
    variable_dialog = AnalysisModuleVariablesPanel(self.getSelectedAnalysisModuleName())
  File "/private/sonso/repos/ert/ert_gui/ertwidgets/analysismodulevariablespanel.py", line 61, in __init__
    analysis_module_variables_model)
  File "/private/sonso/repos/ert/ert_gui/ertwidgets/analysismodulevariablespanel.py", line 111, in createSpinBox
    spinner.setMaximum(analysis_module_variables_model.getVariableMaximumValue(variable_name))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
```

**Comment by markusdregi** [comment]
This is Python 3 and related to missing site-config.

**Comment by markusdregi** [comment]
@sondreso Is this a duplicate of https://github.com/equinor/ert/issues/451

**Comment by sondreso** [comment]
Unsure, should at least be investigated!

**Comment by sondreso** [comment]
Closing this since #451 was closed.
