### ISSUE TITLE
When getting utf-8 codec errors it would be nice to know which file caused the problem

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#4580]
Example from a case with character `å` in the DATA_FILE (cf. [slack message](https://equinor.slack.com/archives/C01MCMWD075/p1673011940419479) [INTERNAL LINK])
``` 
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/simulation/run_dialog.py", line 277, in run
    self._run_model.startSimulations(
  File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/models/base_run_model.py", line 186, in startSimulations
    run_context = self.runSimulations(
  File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/models/single_test_run.py", line 24, in runSimulations
    return self.runSimulations__(
  File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/models/ensemble_experiment.py", line 99, in runSimulations__
    self.ert().createRunPath(run_context)
  File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/enkf_main.py", line 457, in createRunPath
    Path(source_file).read_text("utf-8"),
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/pathlib.py", line 1237, in read_text
    return f.read()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 331: invalid continuation byte
```

**Comment by berland** [comment]
It has been evaluated before whether this exception should be catched, but always downvoted. It would require catching this a tremendous amount of places, and seemingly the problem is steadily going away after the switch to Python 3. Multiple hits with discussions are to be found on Yammer: https://web.yammer.com/main/org/statoil.com/search/threads?search=%22utf-8%22
