### ISSUE TITLE
Qt components released before end of usage

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4584]
**Describe the bug**
Running ensemble experiment and clicking `Done` after the simulations complete causes the GUI to fail with:
```
  File "/.../ert/src/ert/gui/simulation/simulation_panel.py", line 169, in runSimulation
    self.run_button.setText("Start simulation")
RuntimeError: wrapped C/C++ object of type QToolButton has been deleted
[1]    10902 abort      ert gui poly.ert
```

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui my_config.ert`
3. Run ensemble experiment 
4. Click `Done` after simulations finish

**Expected behaviour**
Dont crash

**Comment by oyvindeide** [comment]
PEBCAK, closing

**Comment by oyvindeide** [comment]
Maybe not PEBCAK after all, also reproduced by @ManInFez, what happens is that the main window closes when Run Simulations is clicked, then when clicking the Done button afterwards has no reference anymore.

**Comment by DanSava** [comment]
Was not able to reproduce with a clean `poly_example` on the latest changes in the `main` branch

**Comment by andreas-el** [comment]
Stacktrace:
```
--------------------------------------------------------------------------------
  File "/private/andrli/project/ert/src/ert/gui/tools/plot/plot_widget.py", line 74, in updatePlot
    self._canvas.draw()
  File "/private/andrli/project/testenv/lib64/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 411, in draw
    super().draw()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/private/andrli/project/testenv/lib64/python3.8/site-packages/matplotlib/backend_bases.py", line 3039, in _wait_cursor_for_draw_cm
    self.canvas.set_cursor(self._last_cursor)
  File "/private/andrli/project/testenv/lib64/python3.8/site-packages/matplotlib/backends/backend_qt.py", line 248, in set_cursor
    self.setCursor(_api.check_getitem(cursord, cursor=cursor))
Exception type: RuntimeError
wrapped C/C++ object of type FigureCanvasQTAgg has been deleted
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/andrli/project/ert/src/ert/gui/tools/plot/plot_window.py", line 118, in currentPlotChanged
    index = self._central_tab.indexOf(plot_widget)
RuntimeError: wrapped C/C++ object of type QTabWidget has been deleted
Aborted (core dumped)
```
