### ISSUE TITLE
JobQueue failing to connect to evaluation server (unable to publish changes)

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#4708]
**Describe the bug**

The `JobQueue` instance is not able to connect to the Evaluation server and fails on: L372`src/ert/_c_wrappers/job_queue/queue.py:async def _publish_changes` 

Once this fails all jobs will be cancelled and ERT quits with :
```
Simulation failed! All realizations failed!
Connection to websocket wss://<ip>:<port>/dispatch failed, unable to publish changes
connection handler failed
connection handler failed
unexpected exception in queue
```

**To reproduce**
The issue does not seem to be easily reproduced, neither locally nor in the environment used by the user.

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: [e.g. 2.18 or 2020.12.00]
 - Python version
 - Remote/HPC execution involved: [yes|no]

**Additional context**

The ert run started 10:35:04 and the first iteration was successful. The next run started 17:47:57 and logs demonstrate that the server was setup and dispatchers on the node were able to connect. The Batcher also handled requests as they were entering during the time of connection issues that the `JobQueue` experienced. Multiple 

Adding excerpts of the log:

```
2023-01-13 10:35:04,751 - ert.cli.model_factory - MainThread - INFO - Initiating experiment
...
2023-01-13 17:47:57,254 - websockets.server - ert_ee_run_server - INFO - server listening
2023-01-13 17:49:13,024 - websockets.server - ert_ee_run_server - INFO - connection open
2023-01-13 17:49:13,049 - websockets.server - ert_ee_run_server - INFO - connection open
2023-01-13 17:49:13,095 - websockets.server - ert_ee_run_server - INFO - connection open
2023-01-13 17:49:13,278 - websockets.server - ert_ee_run_server - INFO - connection closed
2023-01-13 17:49:13,505 - websockets.server - ert_ee_run_server - INFO - connection open
2023-01-13 17:49:14,381 - websockets.server - ert_ee_run_server - INFO - connection closed
2023-01-13 17:50:09,937 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - INFO - Connection to websocket wss://<ip>:<port>/dispatch was closed, retry in 3 seconds.
2023-01-13 17:50:23,463 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - INFO - Connection to websocket wss://<ip>:<port>/dispatch was closed, retry in 4 seconds.
2023-01-13 17:50:37,544 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - INFO - Connection to websocket wss://<ip>:<port>/dispatch was closed, retry in 8 seconds.
2023-01-13 17:50:56,051 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - INFO - Connection to websocket wss://<ip>:<port>/dispatch was closed, retry in 16 seconds.
2023-01-13 17:51:22,122 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - INFO - Connection to websocket wss://<ip>:<port>/dispatch was closed, retry in 32 seconds.
2023-01-13 17:52:04,264 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - INFO - Connection to websocket wss://<ip>:<port>/dispatch was closed, retry in 60 seconds.
2023-01-13 17:53:14,684 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - INFO - Connection to websocket wss://<ip>:<port>/dispatch was closed, retry in 60 seconds.
2023-01-13 17:54:24,769 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - INFO - Connection to websocket wss://<ip>:<port>/dispatch was closed, retry in 60 seconds.
2023-01-13 17:55:34,905 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - INFO - Connection to websocket wss://<ip>:<port>/dispatch was closed, retry in 60 seconds.
2023-01-13 17:56:45,031 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - INFO - Connection to websocket wss://<ip>:<port>/dispatch was closed, retry in 60 seconds.
2023-01-13 17:57:55,971 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - ERROR - Connection to websocket wss://<ip>:<port>/dispatch failed, unable to publish changes
```

305 accounts of: `2023-01-13 17:50:22,481 - websockets.server - ert_ee_run_server - INFO - connection failed (400 Bad Request)` was present. Some also occurred on the first iteration, typically in the beginning of the run.

During the time where `JobQueue` is unable to connect, the `Batcher` processes events from the cluster, hence the `JobRunner` on the compute nodes are able to connect. There were not observed connection errors from the 
```
2023-01-13 17:55:33,197 - ert.ensemble_evaluator.dispatch - ert_ee_run_server - DEBUG - processed 1000 events in 0.011312s. 2863 left in queue
2023-01-13 17:55:52,419 - ert.ensemble_evaluator.dispatch - ert_ee_run_server - DEBUG - processed 1000 events in 0.001412s. 3205 left in queue
2023-01-13 17:56:03,860 - ert.ensemble_evaluator.dispatch - ert_ee_run_server - DEBUG - processed 1000 events in 0.001654s. 2740 left in queue


```
Multiple connection issues towards the evaluationserver was observed in the first iteration as well, but eventually the `JobQueue` was able to connect and publish changes. (note the timestamps on the records, meaning that the `JobQueue` has published information in between the retries.
```
2023-01-13 10:37:51,253 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - INFO - Connection to websocket wss://<ip>:<port>/dispatch was closed, retry in 3 seconds.
Traceback (most recent call last):
  File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/job_queue/queue.py", line 402, in _publish_changes
    async with connect(
  File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/websockets/legacy/client.py", line 633, in __aenter__
    return await self
  File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
2023-01-13 10:38:40,063 - ert._c_wrappers.job_queue.queue - LegacyEnsemble - INFO - Connection to websocket wss://<ip>:<port>/dispatch was closed, retry in 4 seconds.
```

**Comment by lars-petter-hauge** [comment]
The reconnection issues was to a large degree contributed by an ill configured cluster node. The continuous establishing and closing of the server could be a contributing effect, it should be reduced with https://github.com/equinor/ert/issues/3437
