### ISSUE TITLE
Segfault when no HISTORY_SOURCE and no REFCASE

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#4758]
Reproducible qith the snake_oil test-data, just remove the aforementioned keywords.
```
(testenv) andrli@be-lx919901 ~/project/ert (main)$ git diff
diff --git a/test-data/snake_oil/snake_oil.ert b/test-data/snake_oil/snake_oil.ert
index 3a36f1b..1f8f0eb 100644
--- a/test-data/snake_oil/snake_oil.ert
+++ b/test-data/snake_oil/snake_oil.ert
@@ -13,8 +13,8 @@ ENSPATH <STORAGE>/ensemble
 ECLBASE SNAKE_OIL_FIELD
 SUMMARY *
 
-HISTORY_SOURCE REFCASE_HISTORY
-REFCASE refcase/SNAKE_OIL_FIELD
+--HISTORY_SOURCE REFCASE_HISTORY
+--REFCASE refcase/SNAKE_OIL_FIELD
 
 TIME_MAP refcase/time_map.txt
 OBS_CONFIG observations/observations.txt
```

No feedback when crashing:

```
(testenv) andrli@be-lx919901 ~/project/ert (main)$ export ERT_SHOW_BACKTRACE=1
(testenv) andrli@be-lx919901 ~/project/ert (main)$ ert gui test-data/snake_oil/snake_oil.ert 
** Warning: Cannot expand * due to missing refcase file. Provide refcase file or add fully expanded SUMMARY key to configuration
Segmentation fault (core dumped)
```

**Comment by andreas-el** [comment]
```
(testenv) andrli@be-lx919901 ~/project/ert (main)$ ert gui test-data/snake_oil/snake_oil.ert 
** Warning: Cannot expand * due to missing refcase file. Provide refcase file or add fully expanded SUMMARY key to configuration
Fatal Python error: Segmentation fault

Current thread 0x00007f288c9b0740 (most recent call first):
  File "/private/andrli/project/ert/src/ert/_c_wrappers/enkf/enkf_obs.py", line 119 in load
  File "/private/andrli/project/ert/src/ert/_c_wrappers/enkf/enkf_main.py", line 169 in __init__
  File "/private/andrli/project/ert/src/ert/gui/main.py", line 106 in _start_initial_gui_window
  File "/private/andrli/project/ert/src/ert/gui/main.py", line 41 in run_gui
  File "/private/andrli/project/ert/src/ert/__main__.py", line 202 in run_gui_wrapper
  File "/private/andrli/project/ert/src/ert/__main__.py", line 564 in main
  File "/private/andrli/project/testenv/bin/ert", line 33 in <module>
Segmentation fault (core dumped)
(testenv) andrli@be-lx919901 ~/project/ert (main)$ 
```

**Comment by andreas-el** [comment]
Stacktrace
```
#0  0x00007fffefbff9a0 in ecl_sum_get_smspec () from /private/andrli/project/testenv/lib64/python3.8/site-packages/ecl/.libs/libecl.so
#1  0x00007fffef170579 in read_history_from_ecl_summary (history=REFCASE_HISTORY, summary_key=0x35fd010 "FOPR", value=0x36014f0, valid=0x3601550, refcase=0x0)
    at /private/andrli/project/ert/src/clib/lib/enkf/obs_vector.cpp:447
#2  0x00007fffef170a70 in obs_vector_load_from_HISTORY_OBSERVATION (obs_vector=0x34917b0, conf_instance=0x34dbf50, 
    obs_time=std::vector of length 2000, capacity 2000 = {...}, history=REFCASE_HISTORY, std_cutoff=9.9999999999999995e-07, refcase=0x0)
    at /private/andrli/project/ert/src/clib/lib/enkf/obs_vector.cpp:511
#3  0x00007fffef14afa3 in handle_history_observation (enkf_obs=0x3489cf0, enkf_conf=0x34a3b50, num_reports=2000, std_cutoff=9.9999999999999995e-07)
    at /private/andrli/project/ert/src/clib/lib/enkf/enkf_obs.cpp:454
#4  0x00007fffef14c349 in (anonymous namespace)::enkf_obs_load (enkf_obs=..., 
    config_file=0x300ea28 "/private/andrli/project/ert/test-data/snake_oil/observations/observations.txt", std_cutoff=9.9999999999999995e-07)
    at /private/andrli/project/ert/src/clib/lib/enkf/enkf_obs.cpp:1027
```
