### ISSUE TITLE
No REFCASE and no TIMEMAP crashes Ert

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#4801]
Ert fails when handling observations and got no refcase and no timemap available.
Reproducible below with snake_oil

```
(2022.12.05-py38) (testenv) andrli@be-lx919901 ~/project/ert (main)$ ert gui test-data/snake_oil/snake_oil.ert 
** Warning: Cannot expand * due to missing refcase file. Provide refcase file or add fully expanded SUMMARY key to configuration
ERT crashed unexpectedly with "Incorrect observations file: /private/andrli/project/ert/test-data/snake_oil/observations/observations.txt: Missing REFCASE or TIMEMAP".
See logfile(s) for details:
   /private/andrli/project/ert/logs/ert-log-2023-02-03T1603.txt
Exception in thread FMUAzureLogHandler Worker:
Traceback (most recent call last):
  File "/prog/res/komodo/2022.12.05-py38-rhel7/root/lib/python3.8/site-packages/opencensus/ext/azure/common/processor.py", line 56, in apply_telemetry_processors
    if processor(envelope) is False:
  File "/prog/res/komodo/2022.12.05-py38-rhel7/root/lib/python3.8/site-packages/fmu_azure_logging/fmu_azure_log_handler.py", line 82, in _redact_properties
    sanitize(envelope, mapping=SENSITIVE_DATA_MAPPING)
  File "/prog/res/komodo/2022.12.05-py38-rhel7/root/lib/python3.8/site-packages/fmu_azure_logging/fmu_azure_log_handler.py", line 43, in sanitize
```

``` diff
(2022.12.05-py38) (testenv) andrli@be-lx919901 ~/project/ert (main)$ git diff
diff --git a/test-data/snake_oil/snake_oil.ert b/test-data/snake_oil/snake_oil.ert
index 3a36f1b..6a5df68 100644
--- a/test-data/snake_oil/snake_oil.ert
+++ b/test-data/snake_oil/snake_oil.ert
@@ -13,10 +13,10 @@ ENSPATH <STORAGE>/ensemble
 ECLBASE SNAKE_OIL_FIELD
 SUMMARY *
 
-HISTORY_SOURCE REFCASE_HISTORY
-REFCASE refcase/SNAKE_OIL_FIELD
+-- HISTORY_SOURCE REFCASE_HISTORY
+-- REFCASE refcase/SNAKE_OIL_FIELD
 
-TIME_MAP refcase/time_map.txt
+-- TIME_MAP refcase/time_map.txt
 OBS_CONFIG observations/observations.txt
 
 INSTALL_JOB SNAKE_OIL_SIMULATOR jobs/SNAKE_OIL_SIMULATOR
(2022.12.05-py38) (testenv) andrli@be-lx919901 ~/project/ert (main)$ 
```

**Comment by DanSava** [comment]
The issue is already solved in the `main` branch probably by https://github.com/equinor/ert/pull/4833
