### ISSUE TITLE
Crash in enkf_fs_refactor branch if reducing ensemble size

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4824]
**Describe the bug**
Running ensemble experiment first, then test run crashes ert with:
```
Exception in thread ert_cli_simulation_thread:
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data/work/ert/ert/src/ert/shared/models/base_run_model.py", line 174, in start_simulations_thread
    self.startSimulations(
  File "/data/work/ert/ert/src/ert/shared/models/base_run_model.py", line 185, in startSimulations
    run_context = self.runSimulations(
  File "/data/work/ert/ert/src/ert/shared/models/ensemble_smoother.py", line 49, in runSimulations
    self.ert().sample_prior(prior_context.sim_fs, prior_context.active_realizations)
  File "/data/work/ert/ert/src/ert/_c_wrappers/enkf/enkf_main.py", line 535, in sample_prior
    storage.save_gen_kw(
  File "/data/work/ert/ert/src/ert/_c_wrappers/enkf/enkf_fs.py", line 183, in save_gen_kw
    self._storage.save_gen_kw(
  File "/data/work/ert/ert/src/ert/storage/__init__.py", line 52, in save_gen_kw
    ds.to_netcdf(self.mount_point / "gen-kw.nc", mode=mode, engine="scipy")
  File "/data/work/venv/ert_38/lib64/python3.8/site-packages/xarray/core/dataset.py", line 1912, in to_netcdf
    return to_netcdf(  # type: ignore  # mypy cannot resolve the overloads:(
  File "/data/work/venv/ert_38/lib64/python3.8/site-packages/xarray/backends/api.py", line 1232, in to_netcdf
    dump_to_store(
  File "/data/work/venv/ert_38/lib64/python3.8/site-packages/xarray/backends/api.py", line 1279, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/data/work/venv/ert_38/lib64/python3.8/site-packages/xarray/backends/common.py", line 269, in store
    self.set_dimensions(variables, unlimited_dims=unlimited_dims)
  File "/data/work/venv/ert_38/lib64/python3.8/site-packages/xarray/backends/common.py", line 340, in set_dimensions
    raise ValueError(
ValueError: Unable to update size for existing dimension'iens' (100 != 1)
```

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui poly.ert`
3. Run ensemble experiment
4. Run test-run (without changing case)

**Expected behaviour**
Either run as expected or a good error message.

**Comment by oyvindeide** [comment]
Suggested approach:
Save one netcdf file for each realization instead of a single file. Puts it more in line with the other responses and parameter types.

**Comment by pinkwah** [comment]
This thing may get worked-around in my PR, as I save `ensemble_size` together with the case directory.

**Comment by oyvindeide** [comment]
All right, though the suggested solution might be relevant after all, might rephrase a bit.

**Comment by JHolba** [comment]
Followed the steps to reproduce. No crash. No new cases are made. Graphs look ok.
