### ISSUE TITLE
Logging a config file with non-utf8 characters may crash ert

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4922]
Although the parser can handle non-utf8 characters, logging will fail with a DecodingException:
```
ERT crashed unexpectedly with "'utf-8' codec can't decode byte 0xe5 in position 971: invalid continuation byte"
Traceback (most recent call last):
File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/__main__.py", line 548, in main
args.func(args)
File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/__main__.py", line 195, in run_gui_wrapper
run_gui(args)
File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/gert_main.py", line 36, in run_gui
res_config = ResConfig(args.config)
File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/res_config.py", line 96, in __init__
self._alloc_from_content(
File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/res_config.py", line 196, in _alloc_from_content
self._log_config_file(user_config_file)
File "/prog/res/komodo/2022.11.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/res_config.py", line 136, in _log_config_file
for line in file_obj:
File "/opt/rh/rh-python38/root/usr/lib64/python3.8/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 971: invalid continuation byte
```

**Comment by oyvindeide** [comment]
Did you find the reason for this? Was maybe related to reading non-utf-8 files from windows?

**Comment by eivindjahren** [comment]
@oyvindeide Did not find exactly what is going on no, but the issue still stands that these logging statements shouldn't crash ert.

**Comment by DanSava** [comment]
I think this is also sort of an fmu-logging issue I noticed in `opencensus/ext/azure/common/transport.py` the following code snippet:

```python
            start_time = time.time()
            headers = {
                'Accept': 'application/json',
                'Content-Type': 'application/json; charset=utf-8',
            }
            endpoint = self.options.endpoint
            if self.options.credential:
                token = self.options.credential.get_token(_MONITOR_OAUTH_SCOPE)
                headers["Authorization"] = "Bearer {}".format(token.token)
            endpoint += '/v2.1/track'
            response = requests.post(
                url=endpoint,
                data=json.dumps(envelopes),
                headers=headers,
                timeout=self.options.timeout,
                proxies=json.loads(self.options.proxies),
                allow_redirects=False,
            )
```

the above snippet is part of the `_transmit(self, envelopes):` method.  So I am thinking that if there are non utf-8 characters that are part of the config when it is logged then this piece of code might cause the error above 🤷‍♂.

**Comment by eivindjahren** [comment]
@DanSava I think the problem is actually that the `_log_config_file` tries to read the file as utf8 and iterate over the lines.

**Comment by DanSava** [comment]
Could not reproduce the reported error: 

Using the following changed poly.ert file:

```
JOBNAME poly_%d

QUEUE_SYSTEM LOCAL
QUEUE_OPTION LOCAL MAX_RUNNING 50

RUNPATH poly_out/realization-<IENS>/iter-<ITER>

OBS_CONFIG observations
TIME_MAP time_map

NUM_REALIZATIONS 100
MIN_REALIZATIONS 1

GEN_KW COEFFS coeff.tmpl coeffs.json coeff_priors
GEN_DATA POLY_RES RESULT_FILE:poly_%d.out REPORT_STEPS:0 INPUT_FORMAT:ASCII
DEFINE 𝒱Ѡ𝓧ƳȤѧᖯć𝗱ễ𝑓𝙜Ⴙ𝞲𝑗𝒌ļ ০Ρ𝗤Ɍ𝓢ȚЦ𝒱Ѡ𝓧ƳȤѧᖯć𝗱ễ𝑓𝙜Ⴙ𝞲𝑗𝒌ļṃŉо𝞎𝒒ᵲꜱ𝙩ừ𝗏ŵ𝒙𝒚ź/?~АḂⲤ𝗗𝖤𝗙ꞠꓧȊ𝐉𝜥ꓡ𝑀𝑵Ǭ
INSTALL_JOB poly_eval POLY_EVAL
SIMULATION_JOB poly_eval
০Ρ𝗤Ɍ𝓢ȚЦ𝒱Ѡ𝓧ƳȤѧᖯć𝗱ễ𝑓𝙜Ⴙ𝞲𝑗𝒌ļṃŉо𝞎𝒒ᵲꜱ𝙩ừ𝗏ŵ𝒙𝒚ź/?~АḂⲤ𝗗𝖤𝗙ꞠꓧȊ𝐉𝜥ꓡ𝑀𝑵Ǭ
```
ert runs without any issue. We get some warnings like:

```

```

**Comment by DanSava** [comment]
Adding random bytes to a file and then trying to read it with an `utf-8` encoding will fail with the reported error. But it is unclear how a random byte might get into a text file. 

We can guard against this and convert the `UnicodeDecodeError` to a `ConfigValidationError` and display it in the suggestor that might be more useful for the users
