### ISSUE TITLE
Unhandled  timeout

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4926]
```
Connection to websocket wss://10.217.147.86:51834/dispatch was closed, retry in 3 seconds.
Traceback (most recent call last):
File "/prog/res/komodo/2023.02.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/job_queue/queue.py", line 389, in _publish_changes
async with connect(
File "/prog/res/komodo/2023.02.01-py38-rhel7/root/lib64/python3.8/site-packages/websockets/legacy/client.py", line 633, in __aenter__
return await self
File "/prog/res/komodo/2023.02.01-py38-rhel7/root/lib64/python3.8/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/tasks.py", line 501, in wait_for
raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```

**Comment by eivindjahren** [comment]
This can be closed with https://github.com/equinor/ert/issues/6270
