### ISSUE TITLE
ERT crashed unexpectedly with "expected str, bytes or os.PathLike object, not NoneType"

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#4947]
Picked this up from the logs - probably something we should look into and at least. 

```
ERT crashed unexpectedly with "expected str, bytes or os.PathLike object, not NoneType"
Traceback (most recent call last):
  File "/prog/res/komodo/2023.02.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/__main__.py", line 564, in main
    args.func(args)
  File "/prog/res/komodo/2023.02.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/cli/main.py", line 33, in run_cli
    res_config = ResConfig(args.config)
  File "/prog/res/komodo/2023.02.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/res_config.py", line 56, in __init__
    self._alloc_from_content(
  File "/prog/res/komodo/2023.02.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/res_config.py", line 207, in _alloc_from_content
    self._alloc_from_dict(config_content_dict)
  File "/prog/res/komodo/2023.02.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/res_config.py", line 220, in _alloc_from_dict
    self.ensemble_config = EnsembleConfig.from_dict(config_dict=config_dict)
  File "/prog/res/komodo/2023.02.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/ensemble_config.py", line 352, in from_dict
    ens_config = cls(
  File "/prog/res/komodo/2023.02.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/ensemble_config.py", line 202, in __init__
    node = self.gen_data_node(gene_data)
  File "/prog/res/komodo/2023.02.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/ensemble_config.py", line 246, in gen_data_node
    return EnkfConfigNode.create_gen_data_full(
  File "/prog/res/komodo/2023.02.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/config/enkf_config_node.py", line 250, in create_gen_data_full
    if os.path.isabs(result_file) or "%d" not in result_file:
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/posixpath.py", line 62, in isabs
    s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by oysteoh** [comment]
I guess we still could provide a better feedback when this happens?
