### ISSUE TITLE
Initializing from scratch / existing without doing anything else first crashed ERT

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#5000]
**Describe the bug**
Initializing from scratch / existing without doing anything else first crashed ERT with the following:

```
Traceback (most recent call last):
  File "/Users/fedacuric/git/ert/src/ert/gui/ertwidgets/__init__.py", line 23, in wrapper
    res = func(*arg)
  File "/Users/fedacuric/git/ert/src/ert/gui/tools/manage_cases/case_init_configuration.py", line 116, in initializeFromScratch
    self.ert.sample_prior(
  File "/Users/fedacuric/git/ert/src/ert/_c_wrappers/enkf/enkf_main.py", line 539, in sample_prior
    ensemble.save_gen_kw(
AttributeError: 'NoneType' object has no attribute 'save_gen_kw'
```

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui poly.ert`
3. `Manage cases` -> `Initialize from scratch` -> `Initialize`

**Expected behaviour**
Not crash

**Comment by oyvindeide** [comment]
Fixed in: https://github.com/equinor/ert/pull/5005
