### ISSUE TITLE
Verify that detailed widget exist for iteration

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#504]
In `detailed_progress.py`:

```
301   def set_progress(self, progress, iteration):
302         self.progress = progress
303         for i in progress: #create all detailed views if they havent been constructed yet
304             if self.iterations.widget(i):
305                 continue
306             detailed_progress_widget = DetailedProgress(self.state_colors, self)
307             detailed_progress_widget.clicked.connect(self.show_selection)
308             detailed_progress_widget.set_progress(progress[i], i)
309             detailed_progress_widget.show()
310             self.iterations.addTab(detailed_progress_widget, "Realizations for iteration {}".format(i))
311 
312         current_progress_widget = self.iterations.widget(iteration)
313         current_progress_widget.set_progress(progress[iteration], iteration)

```
Verify that the widget in `self.iterations` exist.

Current failure

```
Traceback (most recent call last):
  File "/project/res/komodo/2019.07.02/root/lib/python2.7/site-packages/ert_gui/simulation/run_dialog.py", line 221, in updateRunStatus
    if self.checkIfRunFinished():
  File "/project/res/komodo/2019.07.02/root/lib/python2.7/site-packages/ert_gui/simulation/run_dialog.py", line 191, in checkIfRunFinished
    self.hideKillAndShowDone()
  File "/project/res/komodo/2019.07.02/root/lib/python2.7/site-packages/ert_gui/simulation/run_dialog.py", line 286, in hideKillAndShowDone
    self.detailed_progress.set_progress(*self._run_model.getDetailedProgress())
  File "/project/res/komodo/2019.07.02/root/lib/python2.7/site-packages/ert_gui/simulation/detailed_progress.py", line 313, in set_progress
    current_progress_widget.set_progress(progress[iteration], iteration)
AttributeError: 'NoneType' object has no attribute 'set_progress'
```

**Comment by ManInFez** [comment]
Should be fixed by https://github.com/equinor/ert/commit/90c8560687089e25da404e2d629d665d78b1fedb

Reopen if issue reappears.
