### ISSUE TITLE
Lifetime of CopyableLabel can be too short under certain conditions

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#5049]
```
tests/unit_tests/gui/model/test_job_list.py::test_no_cross_talk
  /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-154
  
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/threading.py", line 1254, in run
      self.function(*self.args, **self.kwargs)
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/ert/gui/ertwidgets/copyablelabel.py", line 72, in restore_text
      self.copy_button.setIcon(QIcon(icon_path))
  RuntimeError: wrapped C/C++ object of type QPushButton has been deleted
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
```

Likely it should be created with parent setl to the main window

**Comment by eivindjahren** [comment]
> Maybe just a check for this in restore_text, something like this:
> 
> ```
> def restore_text():
>     if self.copy_button.isVisible():
>         self.copy_button.setIcon(QIcon(icon_path))
> ```

Yes, the culprit is that the timer triggers after the object is destroyed, but `isVisible` doesn't solve this. Probably we will have to replace timer with a slot mechanism which can be disconnected.
