### ISSUE TITLE
ValueError encountered in enkf_obs.py

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#5085]
```
ERT crashed unexpectedly with "Internal error when looking up report: 1"
Traceback (most recent call last):
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/__main__.py", line 564, in main
    args.func(args)
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/__main__.py", line 202, in run_gui_wrapper
    run_gui(args)
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/main.py", line 40, in run_gui
    window, ens_path = _start_initial_gui_window(args, log_handler)
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/main.py", line 92, in _start_initial_gui_window
    ert = EnKFMain(ert_config)
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/enkf_main.py", line 161, in __init__
    self._observations = EnkfObs(
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/enkf_obs.py", line 32, in __init__
    c_ptr = _clib.enkf_obs.alloc(
ValueError: Internal error when looking up report: 1
```

**Comment by andreas-el** [comment]
Not relevant anymore
