### ISSUE TITLE
Empty single value keywords will result in index error

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#5106]
For the keywords `ANALYSIS_SELECT`, `STD_CUTOFF`, `ENKF_ALPHA`, `MAX_SUBMIT`, `NUM_CPU`, `MAX_RUNTIME`, `ITER_COUNT`, `UPDATE_LOG_PATH`, `MIN_REALIZATIONS`, `ITER_CASE`, `GEN_KW_TAG_FORMAT`, `RANDOM_SEED`, `WORKFLOW_JOB_DIRECTORY`,
`INSTALL_JOB_DIRECTORY`, and `LICENSE_PATH`, giving no arguments will result in the following index error:

```
ERT crashed unexpectedly with "Expected 0 <= index < 0, was 0 <= -1 < 0"
Traceback (most recent call last):
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/__main__.py", line 564, in main
    args.func(args)
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/__main__.py", line 202, in run_gui_wrapper
    run_gui(args)
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/main.py", line 40, in run_gui
    window, ens_path = _start_initial_gui_window(args, log_handler)
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/main.py", line 86, in _start_initial_gui_window
    suggestions += ErtConfig.make_suggestion_list(args.config)
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/ert_config.py", line 214, in make_suggestion_list
    return DeprecationMigrationSuggester(
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/_deprecation_migration_suggester.py", line 66, in suggest_migrations
    defines = config_content_as_dict(content, {}).get("DEFINE", [])
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/_config_content_as_dict.py", line 89, in config_content_as_dict
    content_dict[key] = item.getValue()
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/config/config_content.py", line 159, in getValue
    node = self[item_index]
  File "/prog/res/komodo/2023.03.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/config/config_content.py", line 149, in __getitem__
    raise IndexError(
IndexError: Expected 0 <= index < 0, was 0 <= -1 < 0
```

**Comment by DanSava** [comment]
Is it possible to get the config file that generated this error?

**Comment by eivindjahren** [comment]
I'll try
