### ISSUE TITLE
qstat_proxy invalidates its cache file too soon

### ISSUE THREAD

**Issue by berland** [equinor/ert#5118]
qstat_proxy regards a 10 second old cached file as invalid:

https://github.com/equinor/ert/blob/0275b48a5aa6aad26a1c106644ec77b8d593ec52/src/ert/_c_wrappers/job_queue/qstat_proxy.sh#L28

This has been observed to fail during nightly testing of the hm-tutorial:
https://github.com/equinor/komodo-releases/actions/runs/4469431299/jobs/7867160925#step:7:223
```
** Warning: failed to get job status for job:6231 from file:/tmp/ert-qstat-std-31060-172399
Tue, 21 Mar 2023 08:10:16 GMT
Exception in thread Thread-89:
Tue, 21 Mar 2023 08:10:16 GMT
Traceback (most recent call last):
Tue, 21 Mar 2023 08:10:16 GMT
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
Tue, 21 Mar 2023 08:10:16 GMT
    self.run()
Tue, 21 Mar 2023 08:10:16 GMT
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
Tue, 21 Mar 2023 08:10:16 GMT
    self._target(*self._args, **self._kwargs)
Tue, 21 Mar 2023 08:10:16 GMT
  File "/prog/komodo/2023.03.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/job_queue/job_queue_node.py", line 249, in _job_monitor
Tue, 21 Mar 2023 08:10:16 GMT
    raise AssertionError(
Tue, 21 Mar 2023 08:10:16 GMT
AssertionError: Unexpected job status type after running job: JOB_QUEUE_STATUS_FAILURE
```

Logging into the node that ran the job:
```
[f_scout_ci@s034-lcatop02 ~]$ cat /tmp/ert-qstat-std-31060-172399
qstat_proxy: proxyfile /tmp/f_scout_ci-ert-qstat was too old (22 seconds). Giving up!
```

The timeout in the cache file should be in sync with the timeout in:
https://github.com/equinor/ert/blob/0275b48a5aa6aad26a1c106644ec77b8d593ec52/src/clib/lib/include/ert/job_queue/torque_driver.hpp#L28

**Comment by berland** [comment]
Perhaps they should not be synced, but the error message from the qstat_proxy should not be attempted parsed by the qstat parser in ert. qstat_proxy.sh writes this error message to stdout.

**Comment by berland** [comment]
The qstat_proxy should exit with return code 1 even if it outputs to stdout. Whenever the return code is 1, it should try to rerun the qstat command. In order to parse the stdout even if the return code is 1, we need to exceed the timeout. This should be proven by looking at the torque debug log file (should be available next time this fails, https://github.com/equinor/komodo-releases/pull/3523)

**Comment by berland** [comment]
This should be solved in a different manner, by ensuring that the torque driver interprets a non-existing or an empty file as a failure condition, similar to a nonzero return code.
