### ISSUE TITLE
FIELD with INIT_FILES and no extension causes crash

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#5211]
**Describe the bug**

`FIELD PORO  PARAMETER  PORO.GRDECL  INIT_FILES:../../eclipse/Priors/poro/PORO_%d  MIN:0.001234`

gives:

```console
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/private/fcur/git/ert/src/ert/gui/simulation/run_dialog.py", line 275, in run
    self._run_model.startSimulations(
  File "/private/fcur/git/ert/src/ert/shared/models/base_run_model.py", line 181, in startSimulations
    run_context = self.runSimulations(
  File "/private/fcur/git/ert/src/ert/shared/models/single_test_run.py", line 31, in runSimulations
    return self.runSimulations__(
  File "/private/fcur/git/ert/src/ert/shared/models/ensemble_experiment.py", line 136, in runSimulations__
    self.ert().sample_prior(
  File "/private/fcur/git/ert/src/ert/_c_wrappers/enkf/enkf_main.py", line 471, in sample_prior
    data_transformed = field_transform(data, trans)
UnboundLocalError: local variable 'data' referenced before assignment
```

Need to think through `def sample_prior` a bit.

**Comment by SakshiT25** [comment]
Hey @dafeda, I would like to work on this issue. Please guide me on how to proceed with it.

**Comment by frode-aarstad** [comment]
We should probably decide if we want to allow specifying fields with no extension. Then decide if this is something the parser should pick up on

**Comment by frode-aarstad** [comment]
Still an issue but gives an exception informative error message but does not crash
