### ISSUE TITLE
starting ert with absolute path fails with valueerror

### ISSUE THREAD

**Issue by JHolba** [equinor/ert#5272]
**Describe the bug**
Starting ert with an absolute path to the configuration file causes failure both in gui and cli.

**To reproduce**
Steps to reproduce the behaviour:
1. ert test_run <absolute_path>

**Expected behaviour**
Either it should work or it should give a better error message.

**Traceback**
❯ ert test_run /home/holba/eqn/test-data/snake_oil/snake_oil.ert
Warning: ERT is running in an existing runpath
Exception in thread ert_cli_simulation_thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/holba/eqn/ert/src/ert/shared/models/base_run_model.py", line 170, in start_simulations_thread
    self.startSimulations(
  File "/home/holba/eqn/ert/src/ert/shared/models/base_run_model.py", line 181, in startSimulations
    run_context = self.runSimulations(
  File "/home/holba/eqn/ert/src/ert/shared/models/single_test_run.py", line 31, in runSimulations
    return self.runSimulations__(
  File "/home/holba/eqn/ert/src/ert/shared/models/ensemble_experiment.py", line 148, in runSimulations__
    self.ert().createRunPath(prior_context)
  File "/home/holba/eqn/ert/src/ert/_c_wrappers/enkf/enkf_main.py", line 447, in createRunPath
    _generate_parameter_files(
  File "/home/holba/eqn/ert/src/ert/_c_wrappers/enkf/enkf_main.py", line 166, in _generate_parameter_files
    _generate_gen_kw_parameter_file(
  File "/home/holba/eqn/ert/src/ert/_c_wrappers/enkf/enkf_main.py", line 99, in _generate_gen_kw_parameter_file
    gen_kw_dict = fs.load_gen_kw_as_dict(key, realization)
  File "/home/holba/eqn/ert/src/ert/storage/local_ensemble.py", line 218, in load_gen_kw_as_dict
    priors = {p["key"]: p for p in self.experiment.gen_kw_info[key]}
  File "/home/holba/eqn/ert/src/ert/storage/local_experiment.py", line 58, in gen_kw_info
    raise ValueError("No GEN_KW in experiment")
ValueError: No GEN_KW in experiment
Simulations failed with the following error: No GEN_KW in experiment

No GEN_KW in experiment

**Comment by JHolba** [comment]
closing this at it seems to work in main branch now
