### ISSUE TITLE
Requesting active realisations when ERT is closing down

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#546]
The following error has been observed multiple times:

```
Traceback (most recent call last):
  File "/private/jond/work/py2-rgs.1/lib/python2.7/site-packages/ert_gui/ertwidgets/stringbox.py", line 78, in stringBoxChanged
    self._model.setValue(text)
  File "/private/jond/work/py2-rgs.1/lib/python2.7/site-packages/ert_gui/ertwidgets/models/activerealizationsmodel.py", line 41, in setValue
    if active_realizations is None or active_realizations.strip() == "" or active_realizations == self.getDefaultValue():
  File "/private/jond/work/py2-rgs.1/lib/python2.7/site-packages/ert_gui/ertwidgets/models/activerealizationsmodel.py", line 54, in getDefaultValue
    size = getRealizationCount()
  File "/private/jond/work/py2-rgs.1/lib/python2.7/site-packages/ert_gui/ertwidgets/models/ertmodel.py", line 12, in getRealizationCount
    return ERT.enkf_facade.get_ensemble_size()
AttributeError: 'NoneType' object has no attribute 'get_ensemble_size'
```

It is most likely a consequence of this:
https://github.com/equinor/ert/commit/b9af47e021a8ee82c07f9aa6100c8b44493f921b

**Comment by jondequinor** [comment]
The run models are by design racy, difficult to use. I propose a "fix" for this is to properly design the new authority on experiments, as proposed by https://github.com/equinor/ert/issues/1250
