### ISSUE TITLE
Flow simulator is configured erroneously

### ISSUE THREAD

**Issue by berland** [equinor/ert#5517]
**Describe the bug**
Reported by user at https://equinor.slack.com/archives/CDPJULWR4/p1685555744123089

The installed forward model `FLOW` does not run:

Whenever I try to execute it I receive the following error message:
```
>> /prog/res/komodo/2023.05.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/flow.py opm/model/BLA_HIST-0 -n 4
Traceback (most recent call last):
  File "/prog/res/komodo/2023.05.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/flow.py", line 8, in <module>
    config = FlowConfig()
  File "/prog/res/komodo/2023.05.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/ecl_config.py", line 197, in __init__
    super().__init__(config_file, simulator_name="flow")
  File "/prog/res/komodo/2023.05.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/ecl_config.py", line 80, in __init__
    with open(config_file, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/prog/res/komodo/2023.05.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/flow_config.yml'
```
I'm defining the job as follow:
`FORWARD_MODEL FLOW(<VERSION>=<SIMULATOR_VERSION>)`
where `<SIMULATOR_VERSION>` is a variable to choose a specific version of OPM Flow.

**Expected behaviour**
Flow running.

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: 2023.05.01
 - Python version: 3.8
 - Remote/HPC execution involved: [yes|no]

**Comment by eivindjahren** [comment]
One part here is the bad default value which points to a file which has been removed.

**Comment by berland** [comment]
Reproduction of the error message reported by user:
```
$ source /prog/res/komodo/2023.05.01-py38-rhel7
$ cd /prog/res/komodo/2023.05.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/
$ python -c "from ecl_config import FlowConfig; FlowConfig()"
```

**Comment by berland** [comment]
It seems that if parallel computation is triggered (maybe trough the `PARALLEL` keyword in the DATA file), it will still crash
with 
```
<error>
  <time>10:21:29</time>
  <job>FLOW</job>
  <reason>Process exited with status code 1</reason>
  <stderr>
Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/flow.py", line 9, in <module>
    run(config, [arg for arg in sys.argv[1:] if len(arg) > 0])
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/ecl_run.py", line 479, in run
    sim = config.mpi_sim(version=options.version)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/ecl_config.py", line 161, in mpi_sim
    return self._get_sim(version, Keys.mpi)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/ecl_config.py", line 137, in _get_sim
    binaries: Dict[str, str] = self._config[Keys.versions][version][exe_type]
KeyError: 'mpi'
</stderr>
  <stderr_file>/scratch/roncador/bla/ert/dmva/sens_23_1_0_v0/realization-0/iter-0/FLOW.stderr.10</stderr_file>
</error>
```

Context:
https://app.slack.com/client/T02JL00JU/CDPJULWR4/thread/CDPJULWR4-1685555744.123089
