### ISSUE TITLE
JOB_QUEUE_STATUS_FAILURE reoccuring when driver ignores zero return value

### ISSUE THREAD

**Issue by berland** [equinor/ert#5548]
**Describe the bug**
The reliability of the torque driver regressed after merging 7f6cfb2427752b4443e5e846f85f94255a11fb83 and e379e400fa59ee2758f4413d8be72b34f58b4961

The symptoms are as in https://github.com/equinor/komodo-releases/actions/runs/5195011382/jobs/9367649980 with the errors

```
** Warning: failed to get job status for job:46462 from file:/tmp/ert-qstat-std-3744-932899
** Warning: failed to get job status for job:46461 from file:/tmp/ert-qstat-std-3744-369642
** Warning: failed to get job status for job:46463 from file:/tmp/ert-qstat-std-3744-166045
** Warning: failed to get job status for job:46460 from file:/tmp/ert-qstat-std-3744-312729
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/prog/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/job_queue/job_queue_node.py", line 256, in _job_monitor
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/prog/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/job_queue/job_queue_node.py", line 256, in _job_monitor
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    raise AssertionError(
AssertionError: Unexpected job status type after running job: JOB_QUEUE_STATUS_FAILURE
```

Looking at those four files in `/tmp` we get:

```
[f_scout_ci@s034-lcatop02 ~]$ cat /tmp/ert-qstat-std-3744-932899 /tmp/ert-qstat-std-3744-369642 /tmp/ert-qstat-std-3744-166045 /tmp/ert-qstat-std-3744-312729
qstat_proxy: proxyfile /tmp/f_scout_ci-ert-qstat was too old (71 seconds). Giving up!
qstat_proxy: proxyfile /tmp/f_scout_ci-ert-qstat was too old (71 seconds). Giving up!
qstat_proxy: proxyfile /tmp/f_scout_ci-ert-qstat was too old (71 seconds). Giving up!
qstat_proxy: proxyfile /tmp/f_scout_ci-ert-qstat was too old (71 seconds). Giving up!
```
This output (from the qstat proxy) should not be attempted parsed by the driver, it should pick up the nonzero return value (which should be sent in this situation) and retry. 

Then there is possibly a related issue exposed by this error. The qstat proxy invalidates its cache file after only 10 seconds, so that we see 71 seconds here might indicate that there is too much waiting going on in the driver between retries.

**Expected behaviour**

**Screenshots**

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: main
 - Python version: 3.8
 - Remote/HPC execution involved: yes

**Comment by berland** [comment]
More info:
```
[f_scout_ci@s034-lcatop02 ~]$ ls -l /tmp/ert-qstat-std-3744-932899 /tmp/ert-qstat-std-3744-369642 /tmp/ert-qstat-std-3744-166045 /tmp/ert-qstat-std-3744-312729 
-rw-------. 1 f_scout_ci f_scout_ci 86 Jun  7 04:10 /tmp/ert-qstat-std-3744-166045
-rw-------. 1 f_scout_ci f_scout_ci 86 Jun  7 04:10 /tmp/ert-qstat-std-3744-312729
-rw-------. 1 f_scout_ci f_scout_ci 86 Jun  7 04:10 /tmp/ert-qstat-std-3744-369642
-rw-------. 1 f_scout_ci f_scout_ci 86 Jun  7 04:10 /tmp/ert-qstat-std-3744-932899
```

and the associated torque debug log at the same time:
```
2023-06-07T02:08:05.865825Z qstat failed for job 46462, retrying in 2 seconds
2023-06-07T02:08:05.916696Z qstat failed for job 46463, retrying in 2 seconds
2023-06-07T02:08:07.526838Z qstat failed for job 46459, retrying in 2 seconds
2023-06-07T02:08:07.864906Z qstat failed for job 46460, retrying in 4 seconds
2023-06-07T02:08:07.873728Z qstat failed for job 46461, retrying in 4 seconds
2023-06-07T02:08:07.924811Z qstat failed for job 46462, retrying in 4 seconds
2023-06-07T02:08:07.987756Z qstat failed for job 46463, retrying in 4 seconds
2023-06-07T02:08:09.587806Z qstat failed for job 46459, retrying in 4 seconds
2023-06-07T02:08:11.956362Z qstat failed for job 46461, retrying in 8 seconds
2023-06-07T02:08:11.993600Z qstat failed for job 46462, retrying in 8 seconds
2023-06-07T02:08:12.051831Z qstat failed for job 46463, retrying in 8 seconds
2023-06-07T02:08:13.456746Z qstat failed for job 46460, retrying in 8 seconds
2023-06-07T02:08:13.672766Z qstat failed for job 46459, retrying in 8 seconds
2023-06-07T02:08:20.076616Z qstat failed for job 46462, retrying in 16 seconds
2023-06-07T02:08:20.118085Z qstat failed for job 46463, retrying in 16 seconds
2023-06-07T02:08:21.533418Z qstat failed for job 46460, retrying in 16 seconds
2023-06-07T02:08:21.580204Z qstat failed for job 46461, retrying in 16 seconds
2023-06-07T02:08:21.743250Z qstat failed for job 46459, retrying in 16 seconds
2023-06-07T02:08:36.193748Z qstat failed for job 46463, retrying in 32 seconds
2023-06-07T02:08:37.608393Z qstat failed for job 46460, retrying in 32 seconds
2023-06-07T02:08:37.640722Z qstat failed for job 46461, retrying in 32 seconds
2023-06-07T02:08:37.804346Z qstat failed for job 46459, retrying in 32 seconds
2023-06-07T02:08:37.935252Z qstat failed for job 46462, retrying in 32 seconds
2023-06-07T02:09:09.669523Z qstat failed for job 46460, retrying in 64 seconds
2023-06-07T02:09:09.702710Z qstat failed for job 46461, retrying in 64 seconds
2023-06-07T02:09:09.871463Z qstat failed for job 46463, retrying in 64 seconds
2023-06-07T02:09:09.875997Z qstat failed for job 46459, retrying in 64 seconds
2023-06-07T02:09:10.001382Z qstat failed for job 46462, retrying in 64 seconds
2023-06-07T02:10:20.472575Z qstat failed for job 46460, no (more) retries
2023-06-07T02:10:20.472696Z qstat failed for job 46462, no (more) retries
2023-06-07T02:10:20.473112Z qstat failed for job 46461, no (more) retries
2023-06-07T02:10:20.473389Z qstat failed for job 46463, no (more) retries
2023-06-07T02:10:22.022510Z qstat failed for job 46459, no (more) retries
```
