### ISSUE TITLE
Exception on Exit

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#555]
Noted by @jondequinor in #534:

> ... here is a reliable way of reproducing:
> 
> 1. Run Ert GUI
> 1. Select simulation mode: "Ensemble Experiment"
> 1. Focus/click the `Active realizations` input box
> 1. Exit
> 
> You get
> 
> ```
> Traceback (most recent call last):
>   File "/data/work/ert/ert_gui/ertwidgets/stringbox.py", line 78, in stringBoxChanged
>     self._model.setValue(text)
>   File "/data/work/ert/ert_gui/ertwidgets/models/activerealizationsmodel.py", line 41, in setValue
>     if active_realizations is None or active_realizations.strip() == "" or active_realizations == self.getDefaultValue():
>   File "/data/work/ert/ert_gui/ertwidgets/models/activerealizationsmodel.py", line 54, in getDefaultValue
>     size = getRealizationCount()
>   File "/data/work/ert/ert_gui/ertwidgets/models/ertmodel.py", line 12, in getRealizationCount
>     return ERT.enkf_facade.get_ensemble_size()
> AttributeError: 'NoneType' object has no attribute 'get_ensemble_size'
> ```

**Comment by markusdregi** [comment]
This was introduced by: https://github.com/equinor/ert/pull/531 as an attempt to resolve: https://github.com/equinor/ert/pull/531
