### ISSUE TITLE
Increasing number of parameters causes ert to crash

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#5565]
Increasing number of parameters between runs causes ert to crash, to reproduce:

1. Open poly example
2. Run ensemble experiment
3. Close ert
4. Open coeff_priors and add a new parameter (for example COEFF_D)
5. Add said parameter to coeff.tmpl
6. Open ert again
7. Run ensemble experiment

Error:

```
Exception in thread ert_gui_simulation_thread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/path/to/ert/src/ert/gui/simulation/run_dialog.py", line 254, in run
    self._run_model.startSimulations(
  File "/path/to/ert/src/ert/run_models/base_run_model.py", line 211, in startSimulations
    run_context = self.runSimulations(
  File "/path/to/ert/src/ert/run_models/ensemble_experiment.py", line 184, in runSimulations
    return self.runSimulations__(
  File "/path/to/ert/src/ert/run_models/ensemble_experiment.py", line 143, in runSimulations__
    self.ert().sample_prior(
  File "/path/to/ert/ert/src/ert/_c_wrappers/enkf/enkf_main.py", line 300, in sample_prior
    config_node.load(Path(), realization_nr, ensemble)
  File "/path/to/ert/src/ert/_c_wrappers/enkf/config/gen_kw_config.py", line 84, in load
    ensemble.save_gen_kw(
  File "/path/to/ert/src/ert/storage/local_ensemble.py", line 557, in save_gen_kw
    ds.to_netcdf(output_path / "gen-kw.nc", mode=mode, engine="scipy")
  File "/path/to/venv/ert/lib/python3.9/site-packages/xarray/core/dataset.py", line 1904, in to_netcdf
    return to_netcdf(  # type: ignore  # mypy cannot resolve the overloads:(
  File "/path/to/venv/ert/lib/python3.9/site-packages/xarray/backends/api.py", line 1231, in to_netcdf
    dump_to_store(
  File "/path/to/venv/ert/lib/python3.9/site-packages/xarray/backends/api.py", line 1278, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/path/to/venv/ert/lib/python3.9/site-packages/xarray/backends/common.py", line 269, in store
    self.set_dimensions(variables, unlimited_dims=unlimited_dims)
  File "/path/to/venv/ert/lib/python3.9/site-packages/xarray/backends/common.py", line 340, in set_dimensions
    raise ValueError(
ValueError: Unable to update size for existing dimension'COEFFS_keys' (4 != 3)
```

Would expect that ert checks the parameters in existing storage that they are not equal to the ones in the config and gives a warning when overwriting an existing case.

**Comment by pinkwah** [comment]
Can't reproduce. Possibly fixed by changes in how gen_kw is stored. Closing.
