### ISSUE TITLE
check_non_utf_chars  IndexError: list index out of range

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#5605]
From the logs i found this error message

```
ERT crashed unexpectedly with "list index out of range"
Traceback (most recent call last):
File "/prog/res/komodo/2023.05.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/config/config_parser.py", line 94, in check_non_utf_chars
f.read()
File "/opt/rh/rh-python38/root/usr/lib64/python3.8/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 9339-9340: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/prog/res/komodo/2023.05.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/__main__.py", line 564, in main
args.func(args)
File "/prog/res/komodo/2023.05.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/__main__.py", line 202, in run_gui_wrapper
run_gui(args)
File "/prog/res/komodo/2023.05.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/main.py", line 53, in run_gui
window, ens_path = _start_initial_gui_window(args, log_handler)
File "/prog/res/komodo/2023.05.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/main.py", line 101, in _start_initial_gui_window
ert_config = ErtConfig.from_file(args.config)
File "/prog/res/komodo/2023.05.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/ert_config.py", line 84, in from_file
user_config_dict = ErtConfig.read_user_config(
File "/prog/res/komodo/2023.05.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/ert_config.py", line 248, in read_user_config
user_config_content = user_config_parser.parse(
File "/prog/res/komodo/2023.05.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/config/config_parser.py", line 129, in parse
self.check_non_utf_chars(config_file)
File "/prog/res/komodo/2023.05.02-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/config/config_parser.py", line 97, in check_non_utf_chars
hex_str = error_words[error_words.index("byte") + 1]
IndexError: list index out of range
```

**Comment by oysteoh** [comment]
Old parser error, fixed in the new one. Closing.
