### ISSUE TITLE
(Linting/gathering of observation parsing errors) Unexpected characters lark parser

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#5716]
Looking through the logs this one showed up. I guess this shouldn't crash ERT but give an meaningful linting error?

````
ERT crashed unexpectedly with "No terminal matches 'i' in the current parser context, at line 1 col 1

include update_cum.obs;
^
Expected one of: 
	* SUMMARY_OBSERVATION
	* HISTORY_OBSERVATION
	* GENERAL_OBSERVATION
"
Traceback (most recent call last):
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/__main__.py", line 599, in main
    args.func(args, context.plugin_manager)
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/__main__.py", line 199, in run_gui_wrapper
    run_gui(args, ert_plugin_manager)
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/main.py", line 52, in run_gui
    window, ens_path, ensemble_size, parameter_config = _start_initial_gui_window(
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/main.py", line 132, in _start_initial_gui_window
    ert = EnKFMain(ert_config)
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/enkf_main.py", line 143, in __init__
    self._observations = EnkfObs.from_ert_config(config)
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/enkf/enkf_obs.py", line 533, in from_ert_config
    conf_instance = _NewParserAdapter(parse(obs_config_file))
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/parsing/new_observations_parser.py", line 95, in parse
    os.path.dirname(filename), _parse_content(f.read(), filename)
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/parsing/new_observations_parser.py", line 108, in _parse_content
    observations_parser.parse(content)
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib/python3.8/site-packages/lark/lark.py", line 645, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib/python3.8/site-packages/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib/python3.8/site-packages/lark/parsers/earley.py", line 266, in parse
    to_scan = self._parse(lexer, columns, to_scan, start_symbol)
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib/python3.8/site-packages/lark/parsers/xearley.py", line 146, in _parse
    to_scan = scan(i, to_scan)
  File "/prog/res/komodo/2023.06.01-py38-rhel7/root/lib/python3.8/site-packages/lark/parsers/xearley.py", line 119, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan},
lark.exceptions.UnexpectedCharacters: No terminal matches 'i' in the current parser context, at line 1 col 1

include update_cum.obs;
^
Expected one of: 
	* SUMMARY_OBSERVATION
	* HISTORY_OBSERVATION
	* GENERAL_OBSERVATION

```

**Comment by yngve-sk** [comment]
I think this error makes sense as it is from the observations parser. From the docs:

Also note that the special keyword include can be used to read an external file. This can be very useful if you want to change the standard configuration for a lot of observations in one go. For example, consider the following code:
```
HISTORY_OBSERVATION WOPR:P1 { include "hist_obs_wells.txt"; };
```

so the include is only meant to appear inside the observation entries

**Comment by eivindjahren** [comment]
Is the `include` part still relevant? I am not sure the old parser actually did this. If we are not supporting `include` we should indicate that in the documentation.
