### ISSUE TITLE
Compile error on python3.11

### ISSUE THREAD

**Issue by ajikmr** [equinor/ert#5720]
Hello.

Code is working on system with python 3.9. But when I install on system with python 3.11, it throws error. Following is the error thrown. I tried building using scipt/build as well. Gives same error.

Steps to reproduce the behaviour:
0. git clone https://github.com/equinor/ert.git && cd ert
1. `pip install -e .`
2. `ert --help`

**Environment**
 - OS: ubuntu20.04
 - ERT/Komodo release: Latest from github
 - Python version: 3.11
 - Remote/HPC execution involved: yes (just running on a system on cloud)

**Additional context**
Error:
Traceback (most recent call last):
  File "/home/xxxxxxx/bin/ert", line 33, in <module>
    sys.exit(load_entry_point('ert', 'console_scripts', 'ert')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxxxx/bin/ert", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxxxx/anaconda3/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxxxx/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/xxxxxxx/ert/src/ert/__init__.py", line 1, in <module>
    from .data import MeasuredData
  File "/home/xxxxxxx/ert/src/ert/data/__init__.py", line 13, in <module>
    from ._measured_data import MeasuredData
  File "/home/xxxxxxx/ert/src/ert/data/_measured_data.py", line 15, in <module>
    from ert.storage import EnsembleReader
  File "/home/xxxxxxx/ert/src/ert/storage/__init__.py", line 6, in <module>
    from ert.storage.local_ensemble import LocalEnsembleAccessor, LocalEnsembleReader
  File "/home/xxxxxxx/ert/src/ert/storage/local_ensemble.py", line 15, in <module>
    from ert._c_wrappers.enkf.enums import RealizationStateEnum
  File "/home/xxxxxxx/ert/src/ert/_c_wrappers/enkf/__init__.py", line 3, in <module>
    from .config import (
  File "/home/xxxxxxx/ert/src/ert/_c_wrappers/enkf/config/__init__.py", line 3, in <module>
    from .gen_data_config import GenDataConfig
  File "/home/xxxxxxx/ert/src/ert/_c_wrappers/enkf/config/gen_data_config.py", line 11, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/xxxxxxx/anaconda3/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/xxxxxxx/anaconda3/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxxxx/anaconda3/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxxxx/anaconda3/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'sortedcontainers.sortedlist.SortedList'> for field report_steps is not allowed: use default_factory

**Comment by sondreso** [comment]
Hi!
ERT did not support Python 3.11, but this was fixed in https://github.com/equinor/ert/pull/5789. So you should now be able to install ERT in your environment with Python 11. 
There is a beta release available as well, if you do not want to compile the program yourself. You can install it with the command `pip install ert==5.1.0-b9`
