### ISSUE TITLE
Comparison with old parser is failing

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#5768]
```
Traceback (most recent call last):
File ".../ert/gui/main.py", line 90, in _log_difference_with_old_parser
if ert_config != ert_config_new:
File ".../ert/_c_wrappers/enkf/ert_config.py", line 80, in __eq__
return all(
File ".../ert/_c_wrappers/enkf/ert_config.py", line 81, in <genexpr>
attr in ignore_attrs or getattr(self, attr) == getattr(other, attr)
File ".../ert/_c_wrappers/enkf/ensemble_config.py", line 539, in __eq__
if self[par] != other[par]:
File ".../ert/_c_wrappers/enkf/config/summary_config.py", line 32, in __eq__
or self.refcase.case != other.refcase.case
AttributeError: 'NoneType' object has no attribute 'case'
```

**Comment by oysteoh** [comment]
Think this duplicates #5711
