### ISSUE TITLE
storage service complain about non-existing file in gui test

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#6043]
Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
      self.run()
    File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ert/services/_base_service.py", line 145, in run
      self._set_conn_info(conn_info)
    File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/ert/services/_base_service.py", line 341, in set_conn_info
      with open(path, "w", encoding="utf-8") as f:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-runner/pytest-0/test_that_loading_gui_creates_0/poly_example/storage/storage_server.json'

**Comment by eivindjahren** [comment]
Closing as I have not seen such a failure in a while.
