### ISSUE TITLE
Unpin Pylint

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#6229]
The Pylint version `3.0.0` released on 2 oktober seem to fail on Ert.

Look into why this is and resolve the issue.

```
Run script/pylint
  script/pylint
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.5/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.5/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.5/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.5/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.5/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.5/x64/lib
************* Module ert.storage.local_ensemble
src/ert/storage/local_ensemble.py:231:4: R0913: Too many arguments (9/5) (too-many-arguments)
************* Module ert.storage.local_storage
src/ert/storage/local_storage.py:247:4: R0913: Too many arguments (6/5) (too-many-arguments)

------------------------------------
Your code has been rated at 10.00/10

Traceback (most recent call last):
Running: pylint /home/runner/work/ert/ert/src/ert --ignore-paths /home/runner/work/ert/ert/src/ert/gui,/home/runner/work/ert/ert/src/ert/logging,/home/runner/work/ert/ert/src/ert/analysis/_es_update.py,/home/runner/work/ert/ert/src/ert/data,/home/runner/work/ert/ert/src/_ert_job_runner,/home/runner/work/ert/ert/src/ert/shared,/home/runner/work/ert/ert/src/ert/__main__.py,/home/runner/work/ert/ert/src/ert/cli,/home/runner/work/ert/ert/src/ert/ensemble_evaluator,/home/runner/work/ert/ert/src/ert/services,/home/runner/work/ert/ert/src/ert/dark_storage,/home/runner/work/ert/ert/src/ert/callbacks.py
  File "/home/runner/work/ert/ert/script/pylint", line 134, in <module>
    main()
  File "/home/runner/work/ert/ert/script/pylint", line 116, in main
    call(
  File "/home/runner/work/ert/ert/script/pylint", line 112, in call
    subprocess.check_call(["pylint", *args])
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pylint', PosixPath('/home/runner/work/ert/ert/src/ert'), '--ignore-paths', '/home/runner/work/ert/ert/src/ert/gui,/home/runner/work/ert/ert/src/ert/logging,/home/runner/work/ert/ert/src/ert/analysis/_es_update.py,/home/runner/work/ert/ert/src/ert/data,/home/runner/work/ert/ert/src/_ert_job_runner,/home/runner/work/ert/ert/src/ert/shared,/home/runner/work/ert/ert/src/ert/__main__.py,/home/runner/work/ert/ert/src/ert/cli,/home/runner/work/ert/ert/src/ert/ensemble_evaluator,/home/runner/work/ert/ert/src/ert/services,/home/runner/work/ert/ert/src/ert/dark_storage,/home/runner/work/ert/ert/src/ert/callbacks.py']' returned non-zero exit status 8.
Error: Process completed with exit code 1.
```

**Comment by andreas-el** [comment]
Relates to https://github.com/equinor/ert/pull/6228

**Comment by andreas-el** [comment]
Won't do due to being replaced by ruff.
