### ISSUE TITLE
Gen_kw error when sampling priors

### ISSUE THREAD

**Issue by xjules** [equinor/ert#6293]
**Describe the bug**
When running JS case, we get the following error seemingly when sampling priors:
```python
Exception in thread ert_gui_simulation_thread:
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/prog/res/komodo/2023.09.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/simulation/run_dialog.py", line 254, in run
    self._run_model.startSimulations(
  File "/prog/res/komodo/2023.09.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/run_models/base_run_model.py", line 219, in startSimulations
    run_context = self.runSimulations(
  File "/prog/res/komodo/2023.09.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/run_models/multiple_data_assimilation.py", line 123, in runSimulations
    self.ert().sample_prior(
  File "/prog/res/komodo/2023.09.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/enkf_main.py", line 309, in sample_prior
    ds = config_node.sample_or_load(
  File "/prog/res/komodo/2023.09.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/config/gen_kw_config.py", line 48, in sample_or_load
    return self.read_from_runpath(Path(), real_nr)
  File "/prog/res/komodo/2023.09.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/config/gen_kw_config.py", line 86, in read_from_runpath
    "transformed_values": ("names", self.transform(parameter_value)),
  File "/prog/res/komodo/2023.09.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/config/gen_kw_config.py", line 163, in transform
    array[index] = tf.calc_func(array[index], list(tf.parameter_list.values()))
  File "/prog/res/komodo/2023.09.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/config/gen_kw_config.py", line 329, in trans_normal
    return x * _std + _mean
TypeError: can't multiply sequence by non-int of type 'float'
```

**To reproduce**
Steps to reproduce the behaviour:
source 2023.09.00 or 2023.09.01 and run JS case (ert gui 23p14p0pdev_history.ert) in `resmod/ff/users/jholba/23.14.0.dev/ert/model` located in JS porject folder.

**Expected behaviour**
It shouldn't crash.

**Screenshots**

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: 2023.09.01
 - Python version: 3.8
 - Remote/HPC execution involved: yes

**Additional context**

**Comment by xjules** [comment]
It seems that the problem is linked to the way the csv was created in the first place. Then when this is read, the values are not floats but strings. Check here: https://github.com/equinor/ert/blob/866a308977c176ad3b605f0a432603fa1b687816/src/ert/config/gen_kw_config.py#L173
