### ISSUE TITLE
Flaky test: `INTERNALERROR> KeyError: <WorkerController gw8>`

### ISSUE THREAD

**Issue by kwinkunks** [equinor/ert#6367]
Test initially failed on prem only (passed 1st time on Azure): https://github.com/equinor/komodo-releases/actions/runs/6554423915/job/17802667109

Passed on re-run: https://github.com/equinor/komodo-releases/actions/runs/6554423915/job/17809292546

Error was:

```
unit_tests/cli/test_integration_cli.py::test_that_running_ies_with_different_steplength_produces_different_result 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/main.py", line 271, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/main.py", line 325, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/pluggy/_callers.py", line 152, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/pluggy/_result.py", line 114, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/xdist/dsession.py", line 122, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/xdist/dsession.py", line 145, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/xdist/dsession.py", line 270, in worker_collectionfinish
INTERNALERROR>     self.sched.schedule()
INTERNALERROR>   File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/xdist/scheduler/loadscope.py", line 339, in schedule
INTERNALERROR>     self._reschedule(node)
INTERNALERROR>   File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/xdist/scheduler/loadscope.py", line 321, in _reschedule
INTERNALERROR>     self._assign_work_unit(node)
INTERNALERROR>   File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/xdist/scheduler/loadscope.py", line 259, in _assign_work_unit
INTERNALERROR>     worker_collection = self.registered_collections[node]
INTERNALERROR> KeyError: <WorkerController gw8>
```

**Comment by jonathan-eq** [comment]
I think this happens when a test runner crashes for some other reasons. Further down in the logs I found "QThread: Destroyed while thread is still running"

**Comment by jonathan-eq** [comment]
This should be covered by https://github.com/equinor/ert/issues/6348

**Comment by eivindjahren** [comment]
I think we can close this as we haven't experienced it in a long while.
