### ISSUE TITLE
Manage cases will crash under certain conditions

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#6610]
Do the following while running snake_oil:

[reproducing steps](https://github.com/equinor/ert/assets/32731672/38dcb17e-f131-42d0-9a8a-f67fa6a2b683)

Error message: 
```
Traceback (most recent call last):
  File "/home/eivind/Projects/ert/src/ert/gui/ertwidgets/__init__.py", line 13, in wrapper
    res = func(*arg)
          ^^^^^^^^^^
  File "/home/eivind/Projects/ert/src/ert/gui/tools/manage_cases/case_init_configuration.py", line 115, in initializeFromScratch
    sample_prior(
  File "/home/eivind/Projects/ert/src/ert/enkf_main.py", line 208, in sample_prior
    ds = config_node.sample_or_load(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eivind/Projects/ert/src/ert/config/gen_kw_config.py", line 186, in sample_or_load
    parameter_value = self._sample_value(
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/eivind/Projects/ert/src/ert/config/gen_kw_config.py", line 335, in _sample_value
    parameter_values.append(values[realization])
                            ~~~~~~^^^^^^^^^^^^^
IndexError: index 1 is out of bounds for axis 0 with size 1
Aborted (core dumped)
```

**Comment by eivindjahren** [comment]
This does not reproduce in the new "manage experiments" panel.
