### ISSUE TITLE
Workflow `EXPORT_MISFIT_DATA` raises due to missing dependency

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#6703]
```
The script 'ExportMisfitDataJob' caused an error while running:
Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
Traceback (most recent call last):
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/tables/__init__.py", line 70, in <module>
    from .file import File, open_file, copy_file
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/tables/file.py", line 36, in <module>
    from .group import Group, RootGroup
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/tables/group.py", line 17, in <module>
    from .leaf import Leaf
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/tables/leaf.py", line 7, in <module>
    import cpuinfo
ModuleNotFoundError: No module named 'cpuinfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/config/ert_script.py", line 99, in initializeAndRun
    return self.run(*arguments)
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/hook_implementations/workflows/export_misfit_data.py", line 37, in run
    misfit.to_hdf(target_file, key="misfit", mode="w")
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/pandas/core/generic.py", line 2799, in to_hdf
    pytables.to_hdf(
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/pandas/io/pytables.py", line 298, in to_hdf
    with HDFStore(
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/pandas/io/pytables.py", line 559, in __init__
    tables = import_optional_dependency("tables")
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/pandas/compat/_optional.py", line 144, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.
```

**Comment by andreas-el** [comment]
The stavanger nodes seem to have py-cpuinfo ancient version. Also that package is not listed if i create a komodoenv, even if it was listed prior to creating the environment.

The version listed is also from 2015.

Installing `py-cpuinfo` seems to resolve the issue.
