### ISSUE TITLE
ContextBool is not JSON serializable when dumping 

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#6713]
**Describe the bug**
Error occurs when dumping file from `write_simulation_arguments`
```
json.dump(dataclasses.asdict(info), f)
```

`ContextBool` has an override of `__eq__` but this is not picked up by json.encode:

```
    def _iterencode(o, _current_indent_level):
        if isinstance(o, str):
            yield _encoder(o)
        elif o is None:
            yield 'null'
        elif o is True:
            yield 'true'
        elif o is False:
            yield 'false'
       ...
```

We can't really override `is` behavior

```
Traceback (most recent call last):
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/gui/simulation/simulation_panel.py", line 185, in runSimulation
    experiment.write_simulation_arguments(model.simulation_arguments)
  File "/prog/res/komodo/2023.11.00-py38-rhel7/root/lib64/python3.8/site-packages/ert/storage/local_experiment.py", line 203, in write_simulation_arguments
    json.dump(dataclasses.asdict(info), f)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ContextBool is not JSON serializable
Abort (core dumped)
```

**Comment by eivindjahren** [comment]
What are the steps to reproduce? Is this still an issue?
