### ISSUE TITLE
Fix failing unit_tests/ensemble_evaluator/test_ensemble_legacy.py::test_run_and_cancel_legacy_ensemble

### ISSUE THREAD

**Issue by xjules** [equinor/ert#6885]
**Describe the bug**
The following test fails, but only when running it as github workflow:
```python
@pytest.mark.timeout(60)
@pytest.mark.scheduler
    def test_run_and_cancel_legacy_ensemble(
        tmpdir, make_ensemble_builder, monkeypatch, try_queue_and_scheduler
    ):
        num_reals = 2
        custom_port_range = range(1024, 65535)
        with tmpdir.as_cwd():
            ensemble = make_ensemble_builder(
                monkeypatch, tmpdir, num_reals, 2, job_sleep=40
            ).build()
            config = EvaluatorServerConfig(
                custom_port_range=custom_port_range,
                custom_host="127.0.0.1",
                use_token=False,
                generate_cert=False,
            )
    
            evaluator = EnsembleEvaluator(ensemble, config, 0)
    
            evaluator._start_running()
            with Monitor(config) as mon:
                cancel = True
                with contextlib.suppress(
                    ConnectionClosed
                ):  # monitor throws some variant of CC if dispatcher dies
>                   for _ in mon.track():

unit_tests/ensemble_evaluator/test_ensemble_legacy.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/ensemble_evaluator/monitor.py:95: in track
    for message in duplexer.receive():
/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/ensemble_evaluator/sync_ws_duplexer.py:126: in receive
    event = asyncio.run_coroutine_threadsafe(
/opt/rh/rh-python38/root/usr/lib64/python3.8/concurrent/futures/_base.py:439: in result
    self._condition.wait(timeout)
self = <Condition(<unlocked _thread.RLock object owner=0 count=0 at 0x7f1aad32b450>, 0)>
timeout = None

    def wait(self, timeout=None):
        """Wait until notified or until a timeout occurs.
    
        If the calling thread has not acquired the lock when this method is
        called, a RuntimeError is raised.
    
        This method releases the underlying lock, and then blocks until it is
        awakened by a notify() or notify_all() call for the same condition
        variable in another thread, or until the optional timeout occurs. Once
        awakened or timed out, it re-acquires the lock and returns.
    
        When the timeout argument is present and not None, it should be a
        floating point number specifying a timeout for the operation in seconds
        (or fractions thereof).
    
        When the underlying lock is an RLock, it is not released using its
        release() method, since this may not actually unlock the lock when it
        was acquired multiple times recursively. Instead, an internal interface
        of the RLock class is used, which really unlocks it even when it has
        been recursively acquired several times. Another internal interface is
        then used to restore the recursion level when the lock is reacquired.
    
        """
        if not self._is_owned():
            raise RuntimeError("cannot wait on un-acquired lock")
        waiter = _allocate_lock()
        waiter.acquire()
        self._waiters.append(waiter)
        saved_state = self._release_save()
        gotit = False
        try:    # restore state no matter what (e.g., KeyboardInterrupt)
            if timeout is None:
>               waiter.acquire()
E               Failed: Timeout >60.0s

/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py:302: Failed
```

**To reproduce**
It fails on gh action workflows both on PR runs and komodo tests. See examples:
ert-PR: https://github.com/equinor/ert/actions/runs/7208911337/job/19638817158
komodo: https://github.com/equinor/komodo-releases/actions/runs/7391951454/job/20110678281

**Expected behaviour**
The test should pass.

**Screenshots**

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: bleeding (constantly), PR (flaky behaviour)
 - Python version
 - Remote/HPC execution involved: [yes|no]

**Comment by berland** [comment]
When running on local iron with pytest-repeat, this fails in roughly 1% of the invocations.

**Comment by berland** [comment]
Stacktrace when failing: 
```
  /home/berland/venv/dec23/lib/python3.10/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread LegacyEnsemble
  
  Traceback (most recent call last):
    File "/home/berland/projects/ert/src/ert/scheduler/job.py", line 101, in _submit_and_run_once
      await self.started.wait()
    File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
      await fut
  asyncio.exceptions.CancelledError
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/berland/projects/ert/src/ert/scheduler/job.py", line 151, in __call__
      await self._submit_and_run_once(sem)
    File "/home/berland/projects/ert/src/ert/scheduler/job.py", line 136, in _submit_and_run_once
      await self.driver.kill(self.iens)
    File "/home/berland/projects/ert/src/ert/scheduler/local_driver.py", line 27, in kill
      await self._tasks[iens]
  asyncio.exceptions.CancelledError
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/berland/projects/ert/src/ert/ensemble_evaluator/_builder/_legacy.py", line 231, in _evaluate_inner
      result = await queue.execute(min_required_realizations)
    File "/home/berland/projects/ert/src/ert/scheduler/scheduler.py", line 170, in execute
      await task
  asyncio.exceptions.CancelledError
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.10/threading.py", line 953, in run
      self._target(*self._args, **self._kwargs)
    File "/home/berland/projects/ert/src/ert/ensemble_evaluator/_builder/_legacy.py", line 154, in _evaluate
      get_event_loop().run_until_complete(
    File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
      return future.result()
  asyncio.exceptions.CancelledError
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

```

**Comment by berland** [comment]
On line 136 we call kill() from the driver when handling the cancellation, but this causes another CancellationError which we don't handle.

**Comment by xjules** [comment]
The test is now passing, but something has been unleashed.
```sh
ERROR: (  1.011s) 	Killing job in /tmp/f_scout_ci/actions-runner-02/_temp/pytest_tmp_dir/pytest-of-f_scout_ci/pytest-0/popen-gw0/test_run_and_cancel_legacy_ens0/real_1 (ThreadStatus.STOPPING).
   ERROR: (  0.000s) 	a dispatcher abruptly closed a websocket: no close frame received or sent
```
Check https://github.com/equinor/komodo-releases/actions/runs/7458667472/job/20294751346

**Comment by jonathan-eq** [comment]
Do you think this is the root cause of the previous problem?

**Comment by xjules** [comment]
Just update on the error logs when enabling them while running pytest:
---
`pytest -k using_job_queue --log-cli-level=DEBUG tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py::test_run_and_cancel_legacy_ensemble`

```
ERROR    ert.job_queue.job_queue_node:job_queue_node.py:247 Killing job in /tmp/pytest-of-jparu/pytest-101/test_run_and_cancel_legacy_ens0/real_1 (ThreadStatus.STOPPING).
ERROR    ert.ensemble_evaluator.evaluator:evaluator.py:308 a dispatcher abruptly closed a websocket: no close frame received or sent
ERROR    ert.job_queue.job_queue_node:job_queue_node.py:247 Killing job in /tmp/pytest-of-jparu/pytest-101/test_run_and_cancel_legacy_ens0/real_0 (ThreadStatus.STOPPING).
ERROR    ert.ensemble_evaluator.evaluator:evaluator.py:308 a dispatcher abruptly closed a websocket: no close frame received or sent
```
---
`pytest -k using_scheduler --log-cli-level=DEBUG tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py::test_run_and_cancel_legacy_ensemble`

```
ERROR    ert.scheduler.job:job.py:186 Realization: 0 failed after reaching max submit (100):
ERROR    ert.scheduler.job:job.py:186 Realization: 1 failed after reaching max submit (100):
```

**Comment by xjules** [comment]
This one can be closed since the error is not an actual error.

**Comment by berland** [comment]
Still happening:
```

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++

~~~~~~~~~~~~~~~~~~~~ Stack of Thread-463 (140190978926336) ~~~~~~~~~~~~~~~~~~~~~
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)

~~~~~~~~~~~~~~~~~~ Stack of LegacyEnsemble (140190987319040) ~~~~~~~~~~~~~~~~~~~
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/ensemble_evaluator/_builder/_legacy.py", line 154, in _evaluate
    get_event_loop().run_until_complete(
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)

~~~~~~~~~~~~~~~~~ Stack of ert_ee_run_server (140191929267968) ~~~~~~~~~~~~~~~~~
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/ensemble_evaluator/evaluator.py", line 390, in _run_server
    loop.run_until_complete(self.evaluator_server())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)

~~~~~~~~~~~~~~ Stack of ert_ee_batch_dispatcher (140191913801472) ~~~~~~~~~~~~~~
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/ensemble_evaluator/dispatch.py", line 76, in run_dispatcher
    self._job()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/ensemble_evaluator/dispatch.py", line 99, in _job
    time.sleep(self._sleep_between_batches_seconds)

~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-2 (140193478723328) ~~~~~~~~~~~~~~~~~~~~~~
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/tqdm/_monitor.py", line 60, in run
    self.was_killed.wait(self.sleep_interval)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)

~~~~~~~~~~~~ Stack of OtelBatchLogRecordProcessor (140194796484352) ~~~~~~~~~~~~
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/opentelemetry/sdk/_logs/_internal/export/__init__.py", line 250, in worker
    self._condition.wait(timeout)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)

~~~~~~~~ Stack of FMUAzureMonitorLogExporter Storage (140194788091648) ~~~~~~~~~
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/azure/monitor/opentelemetry/exporter/_utils.py", line 123, in run
    while not self.finished.wait(wait_time):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)

~~~~~~~~~~~~~~~~~~~~~ Stack of <unknown> (140195164129024) ~~~~~~~~~~~~~~~~~~~~~
  File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/execnet/gateway_base.py", line 361, in _perform_spawn
    reply.run()
  File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/execnet/gateway_base.py", line 296, in run
    self._result = func(*args, **kwargs)
  File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/execnet/gateway_base.py", line 1049, in _thread_receiver
    msg = Message.from_io(io)
  File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/execnet/gateway_base.py", line 507, in from_io
    header = io.read(9)  # type 1, channel 4, payload 4
  File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/execnet/gateway_base.py", line 474, in read
    data = self._read(numbytes - len(buf))

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
   ERROR: ( 64.099s) 	Exception occurred during Task-7015
Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
[gw1] FAILED unit_tests/ensemble_evaluator/test_ensemble_legacy.py::test_run_and_cancel_legacy_ensemble[using_scheduler] 
```

**Comment by berland** [comment]
Reproducible on local iron with 
`pytest -sxv "tests/unit_tests/ensemble_evaluator/test_ensemble_legacy.py::test_run_and_cancel_legacy_ensemble" --count 500 -x -k using_scheduler -n 24`

**Comment by xjules** [comment]
Reproduced the same error with:
```sh
pytest -sxv "tests/unit_tests/scheduler/test_scheduler.py::test_max_runtime_while_killing" --count 500 -x -n 
```

**Comment by xjules** [comment]
Let's wait several days without failure before closing this one.
