### ISSUE TITLE
storage crashes on duplicate observation data

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#7028]
Change snake_oil and add the following instead of WPR_DIFF:

```
GENERAL_OBSERVATION WPR_DIFF_1 {
   DATA       = SNAKE_OIL_WPR_DIFF;
   INDEX_LIST = 400,800,1200,1800;
   DATE       = 2015-06-13;  -- (RESTART = 199)
   OBS_FILE   = wpr_diff_obs.txt;
};

GENERAL_OBSERVATION WPR_DIFF_2 {
   DATA       = SNAKE_OIL_WPR_DIFF;
   INDEX_LIST = 400,800,1200,1800;
   DATE       = 2015-06-13;  -- (RESTART = 199)
   OBS_FILE   = wpr_diff_obs.txt;
};
```
This results in the following crash:
```
Exception in thread ert_gui_simulation_thread:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "...ialog.py", line 273, in run
    self._run_model.startSimulations(
  File "...model.py", line 249, in startSimulations
    run_context = self.run_experiment(
                  ^^^^^^^^^^^^^^^^^^^^
  File "...smoother.py", li ne 123, in run_experiment
    smoother_snapshot = smoother_update(
                        ^^^^^^^^^^^^^^^^
  File "...py", line 982, i n smoother_update
    analysis_ES(
  File "...py", line 573, i n analysis_ES
    ) = _load_observations_and_responses(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...py", line 357, i n _load_observations_and_responses
    S, observations, errors, obs_keys = _get_obs_and_measure_data(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...py", line 316, i n _get_obs_and_measure_data
    filtered_ds = observation.merge(ds, join="left")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/xarray/core/dataset.py", line 5715, in merge
    merge_result = dataset_merge_method(
                   ^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/xarray/core/merge.py", line 1042, in dataset_merge_method
    return merge_core(
           ^^^^^^^^^^^
  File ".../python3.11/site-packages/xarray/core/merge.py", line 711, in merge_core
    aligned = deep_align(
              ^^^^^^^^^^^
  File ".../python3.11/site-packages/xarray/core/alignment.py", line 952, in deep_align
    aligned = align(
              ^^^^^^
  File ".../python3.11/site-packages/xarray/core/alignment.py", line 888, in align
    aligner.align()
  File ".../python3.11/site-packages/xarray/core/alignment.py", line 582, in align
    self.reindex_all()
  File ".../python3.11/site-packages/xarray/core/alignment.py", line 557, in reindex_all
    self.results = tuple(
                   ^^^^^^
  File ".../python3.11/site-packages/xarray/core/alignment.py", line 558, in <genexpr>
    self._reindex_one(obj, matching_indexes)
  File ".../python3.11/site-packages/xarray/core/alignment.py", line 544, in _reindex_one
    dim_pos_indexers = self._get_dim_pos_indexers(matching_indexes)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/xarray/core/alignment.py", line 510, in _get_dim_pos_indexers
    indexers = obj_idx.reindex_like(aligned_idx, **self.reindex_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/xarray/core/indexes.py", line 817, in reindex_like
    raise ValueError( ValueError: cannot reindex or align along dimension 'index' because the (pandas) index has duplicate values

```

**Comment by eivindjahren** [comment]
Note that report step does not need to match in order to trigger this error. The following gives the same error:
```python
    datasets = []
    datasets.append(
        xr.Dataset(
            {
                "observations": (["report_step", "index"], [np.array([0.0])]),
                "std": (["report_step", "index"], [np.array([1.0])]),
            },
            coords={"index": np.array([0]), "report_step": [0]},
        )
    )
    datasets.append(
        xr.Dataset(
            {
                "observations": (["report_step", "index"], [np.array([0.0, 0.0])]),
                "std": (["report_step", "index"], [np.array([1.0, 1.0])]),
            },
            coords={"index": np.array([0, 0]), "report_step": [1]},
        )
    )
    combined = xr.combine_by_coords(datasets)

```

**Comment by frode-aarstad** [comment]
Should we not try to catch this is the config parsing step? Is this not possible to catch there?
