### ISSUE TITLE
Flaky tests hangs during nightly tests

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#7310]
**Describe the bug**

The first run of the ert tests was hanging and as a result killed after 6 hours of execution, and while it's a little tricky to tell with the parallel execution it seems like it was test_read_mode that was hanging: https://github.com/equinor/komodo-releases/actions/runs/8088980330/job/22105480799#step:4:11911

When rerunning, the same test reported timeouts as well (in the logging), but it passed ([Complete logs](https://github.com/equinor/komodo-releases/actions/runs/8088980330/job/22120233675)):
```
unit_tests/storage/test_mode.py::test_read_mode 
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/opentelemetry/sdk/_logs/_internal/export/__init__.py", line 249, in worker
    self._condition.wait(timeout)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~ Stack of FMUAzureMonitorLogExporter Storage (139974384051968) ~~~~~~~~~
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/azure/monitor/opentelemetry/exporter/_utils.py", line 141, in run
    while not self.finished.wait(wait_time):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~~~~~ Stack of <unknown> (139974723196672) ~~~~~~~~~~~~~~~~~~~~~
  File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/execnet/gateway_base.py", line 361, in _perform_spawn
    reply.run()
  File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/execnet/gateway_base.py", line 296, in run
    self._result = func(*args, **kwargs)
  File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/execnet/gateway_base.py", line 1049, in _thread_receiver
    msg = Message.from_io(io)
  File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/execnet/gateway_base.py", line 507, in from_io
    header = io.read(9)  # type 1, channel 4, payload 4
  File "/tmp/f_scout_ci/actions-runner-01/_temp/test-kenv/root/lib64/python3.8/site-packages/execnet/gateway_base.py", line 474, in read
    data = self._read(numbytes - len(buf))
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
[gw1] PASSED unit_tests/storage/test_mode.py::test_read_mode 
```

**To reproduce**
TBD

**Expected behaviour**
Not hang

**Screenshots**

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: bleeding
 - Python version: 3.8
 - Remote/HPC execution involved: no

**Additional context**
N/A

**Comment by sondreso** [comment]
The following also appears in [the logs](https://github.com/equinor/komodo-releases/actions/runs/8088980330/job/22105480799#step:4:11911) of the first run that hangs: 
```
2024-02-29T01:29:51.5340103Z Exceptions caught in Qt event loop:
2024-02-29T01:29:51.5340884Z ________________________________________________________________________________
2024-02-29T01:29:51.5341544Z Traceback (most recent call last):
2024-02-29T01:29:51.5342826Z   File "/tmp/f_scout_ci/actions-runner-02/_temp/test_root/tests/unit_tests/gui/test_main_window.py", line 717, in <lambda>
2024-02-29T01:29:51.5352177Z     QTimer.singleShot(20000, lambda: handle_error_dialog(run_dialog))
2024-02-29T01:29:51.5353706Z   File "/tmp/f_scout_ci/actions-runner-02/_temp/test_root/tests/unit_tests/gui/test_main_window.py", line 695, in handle_error_dialog
2024-02-29T01:29:51.5354847Z     error_dialog = run_dialog.fail_msg_box
2024-02-29T01:29:51.5355636Z AttributeError: 'RunDialog' object has no attribute 'fail_msg_box'
2024-02-29T01:29:51.5356445Z ________________________________________________________________________________

...

[gw0] FAILED unit_tests/gui/test_main_window.py::test_that_a_failing_job_shows_error_message_with_context[using_job_queue]
```

**Comment by jonathan-eq** [comment]
This error happened because the simulation did not fail. Why that is, I will investigate🕵️.

**Comment by jonathan-eq** [comment]
Closing this as it has not been observed since this issue was created.
