### ISSUE TITLE
Exception in publisher_task: received 1011 (internal error)

### ISSUE THREAD

**Issue by berland** [equinor/ert#7603]
**Describe the bug**
When running bigpoly on py38-rhel7 in https://github.com/equinor/komodo-releases/actions/runs/8608382611/job/23600046726 we got the error:

```
Too many realizations have failed! Number of successful realizations: 20, expected minimal number of successful realizations: 100
 You can add/adjust MIN_REALIZATIONS to allow (more) failures in your experiments.
Exception in scheduler task publisher_task: received 1011 (internal error) keepalive ping timeout; then sent 1011 (internal error) keepalive ping timeout
Traceback: Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/scheduler/scheduler.py", line 198, in _publisher
    await conn.send(event)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/websockets/legacy/protocol.py", line 939, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1011 (internal error) keepalive ping timeout; then sent 1011 (internal error) keepalive ping timeout
```

**Comment by berland** [comment]
https://websockets.readthedocs.io/en/stable/faq/common.html#what-does-connectionclosederror-sent-1011-internal-error-keepalive-ping-timeout-no-close-frame-received-mean

**Comment by xjules** [comment]
> Might be related: #7608

Yes, I think it is the same `ConnectioClosed` group error.
