### ISSUE TITLE
Exception in scheduler task publisher_task: no close frame received or sent

### ISSUE THREAD

**Issue by larsevj** [equinor/ert#7608]
Failure on bigpoly py311-rhel8 onprem scheduler set to True: https://github.com/equinor/komodo-releases/actions/runs/8608382611/job/23601956502

```
Too many realizations have failed! Number of successful realizations: 11, expected minimal number of successful realizations: 50
 You can add/adjust MIN_REALIZATIONS to allow (more) failures in your experiments.
Exception in scheduler task publisher_task: no close frame received or sent
Traceback: Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-py311-rhel8/root/lib64/python3.11/site-packages/ert/async_utils.py", line 41, in _done_callback
    if (exc := task.exception()) is None:
               ^^^^^^^^^^^^^^^^
  File "/prog/res/komodo/bleeding-py311-rhel8/root/lib64/python3.11/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prog/res/komodo/bleeding-py311-rhel8/root/lib64/python3.11/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prog/res/komodo/bleeding-py311-rhel8/root/lib64/python3.11/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prog/res/komodo/bleeding-py311-rhel8/root/lib64/python3.11/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/prog/res/komodo/bleeding-py311-rhel8/root/lib64/python3.11/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/streams.py", line 733, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib64/python3.11/asyncio/streams.py", line 526, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError
```

**Comment by berland** [comment]
Should be covered by #7611
