### ISSUE TITLE
ERROR file XML parsing errors when failing realizations are resubmitted

### ISSUE THREAD

**Issue by berland** [equinor/ert#7634]
When say the RMS job fails, and there is an error message appended to the file `ERROR` and MAX_RESUBMIT is more than 1, a similar error might be appended to the file, yielding a file with the `<error>` tag repeated:

```
<error>
  <time>09:52:40</time>
  <job>RMS</job>
  <reason>Process exited with status code 1</reason>
  <stderr>
Traceback (most recent call last):
  File &quot;/prog/res/komodo/bleeding-py38-rhel7/root/bin/runrms&quot;, line 8, in &lt;module&gt;
    sys.exit(main())
  File &quot;/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/rms_sys/runrms/__main__.py&quot;, line 299, in main
    executor.run()
  File &quot;/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/rms_sys/runrms/executor/fm_rms_executor.py&quot;, line 121, in run
    raise RMSRuntimeError(f&quot;The RMS run failed with exit status: {exit_status}&quot;)
rms_sys.runrms.executor._rms_executor.RMSRuntimeError: The RMS run failed with exit status: 1
</stderr>
  <stderr_file>/scratch/xxxxx/realization-29/iter-0/RMS.stderr.118</stderr_file>
</error>
<error>
  <time>10:39:36</time>
  <job>RMS</job>
  <reason>Process exited with status code 1</reason>
  <stderr>
Traceback (most recent call last):
  File &quot;/prog/res/komodo/bleeding-py38-rhel7/root/bin/runrms&quot;, line 8, in &lt;module&gt;
    sys.exit(main())
  File &quot;/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/rms_sys/runrms/__main__.py&quot;, line 299, in main
    executor.run()
  File &quot;/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/rms_sys/runrms/executor/fm_rms_executor.py&quot;, line 121, in run
    raise RMSRuntimeError(f&quot;The RMS run failed with exit status: {exit_status}&quot;)
rms_sys.runrms.executor._rms_executor.RMSRuntimeError: The RMS run failed with exit status: 1
</stderr>
  <stderr_file>/scratch/xxxxxx/realization-29/iter-0/RMS.stderr.118</stderr_file>
</error>
```

An exception will then be triggered by the scheduler when picking up this error message:
```
2024-04-11 10:39:47,220 - ert.scheduler.scheduler - LegacyEnsemble - ERROR - Exception in scheduler task job-29_task: Extra content at the end of the document, line 17, column 1 (ERROR, line 17)
Traceback: Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/scheduler/job.py", line 115, in _submit_and_run_once
    await self.returncode
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/scheduler/job.py", line 131, in run
    await self._submit_and_run_once(sem)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/scheduler/job.py", line 122, in _submit_and_run_once
    await self._send(State.ABORTED)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/scheduler/job.py", line 210, in _send
    await self._handle_aborted()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/scheduler/job.py", line 202, in _handle_aborted
    log_info_from_exit_file(Path(self.real.run_arg.runpath) / ERROR_file)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/scheduler/job.py", line 233, in log_info_from_exit_file
    exit_file = etree.parse(exit_file_path)
  File "src/lxml/etree.pyx", line 3569, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1952, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1978, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1881, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1200, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 633, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 743, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 672, in lxml.etree._raiseParseError
  File "/scratch/xxxx/realization-29/iter-0/ERROR", line 17
lxml.etree.XMLSyntaxError: Extra content at the end of the document, line 17, column 1
```

**Comment by berland** [comment]
I suspect we are calling `_handle_failure` or `_handle_aborted` either twice, or both. There is also logged an error that realiztion 29 cannot be killed right after it fails, which is a bug we supposedly fixed earlier.

**Comment by berland** [comment]
Selected lines from jobqueue-log:
```
[havb@st-linrgsn110:/project/xxxxxx/ert/model/logs]$ grep 29 jobqueue-log-xxx_hist-ert-2024-04-11T0948.txt 
2024-04-11 09:50:24,411 - ert.scheduler.lsf_driver - LegacyEnsemble - DEBUG - Submitting to LSF with command /global/bin/bsub -q mr -R 'select[cs && x86_64Linux]' -J xxxx_BLEEDING-29 /scratch/xxxxxxd/realization-29/iter-0/.lsf_submit_58wzddof.sh /scratch/xxxxxxxxxxxxxxx/realization-29/iter-0
2024-04-11 09:50:24,921 - ert.scheduler.lsf_driver - LegacyEnsemble - INFO - Realization 29 accepted by LSF, got id 142761
2024-04-11 09:51:24,085 - ert.scheduler.lsf_driver - LegacyEnsemble - DEBUG - Realization 29 is running
2024-04-11 10:39:47,035 - ert.scheduler.lsf_driver - LegacyEnsemble - DEBUG - Realization 29 (LSF-id: 142761) failed
2024-04-11 10:39:47,037 - ert.scheduler.lsf_driver - LegacyEnsemble - ERROR - LSF kill failed due to missing jobid for realization 29

```

**Comment by xjules** [comment]
Yes, it's a bit weird:
```python
await self._send(State.ABORTING)
await self.driver.kill(self.iens)
with suppress(asyncio.CancelledError):
     self.returncode.cancel()
await self._send(State.ABORTED)
```
here both states (`ABORTING` and `ABORTED`) yield the same internal handling.
