### ISSUE TITLE
No running event loop error observed when doing heavy update

### ISSUE THREAD

**Issue by berland** [equinor/ert#7642]
Observed while running the poly-case on version 9.0.4 on 1000 realizations, during the update step:

```
(2024.04.rc0-py38) [havb@be-linrgsn001:~/projects/ert/test-data/poly_example] main$ ert gui --enable-scheduler poly.ert
Exception ignored in: <coroutine object WebSocketCommonProtocol.close_connection at 0x7f2c8c56c340>
Traceback (most recent call last):
  File "/prog/res/komodo/2024.04.rc0-py38-rhel7/root/lib64/python3.8/site-packages/websockets/legacy/protocol.py", line 1337, in close_connection
    await self.close_transport()
  File "/prog/res/komodo/2024.04.rc0-py38-rhel7/root/lib64/python3.8/site-packages/websockets/legacy/protocol.py", line 1355, in close_transport
    if await self.wait_for_connection_lost():
  File "/prog/res/komodo/2024.04.rc0-py38-rhel7/root/lib64/python3.8/site-packages/websockets/legacy/protocol.py", line 1379, in wait_for_connection_lost
    async with asyncio_timeout(self.close_timeout):
  File "/prog/res/komodo/2024.04.rc0-py38-rhel7/root/lib64/python3.8/site-packages/websockets/legacy/async_timeout.py", line 74, in timeout
    loop = asyncio.get_running_loop()
RuntimeError: no running event loop
```

This is probably the Ensemble Evaluator that is too busy doing the maths for the update from an iteration to the next, and not setting aside time to maintain the websocket connection, and then some bad handling of this problem. 

The poly case progresses fine so this is not an Error, just a Warning. But this should not be shown to users.

**Comment by berland** [comment]
Related to #7275

**Comment by xjules** [comment]
Might be related to this one: https://github.com/equinor/komodo-releases/actions/runs/9105017015/job/25030169047
```
File "/prog/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/job_queue/queue.py", line 277, in _jobqueue_publisher
    change = await self._changes_to_publish.get()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/queues.py", line 165, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by xjules** [comment]
Now I start to understand why this happens. Not sure if this is an inherit flakiness of checking `self._connection.open`which should be the proper way of testing it before calling connection.close() in monitor. However, when having this extra check then all hell got loose: https://github.com/equinor/ert/actions/runs/9284739204/job/25547764539#step:7:541

**Comment by xjules** [comment]
Closing this issue as this has been not observed in last two weeks.
