### ISSUE TITLE
`ert api config.ert` raises an exception when `ENSPATH` does not exist

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#7970]
**To reproduce**
Run `ert api test-data/poly_example/poly.ert` without having created storage.

```
user@host$ ert api test-data/poly_example/poly.ert
Storage server is ready to accept requests. Listening on:
  http://127.0.0.1:1111

OpenAPI Docs: http:/host:1111/docs
  http://host:1111

OpenAPI Docs: http://host:1111/docs
  http://host:1111

OpenAPI Docs: http://host:1111/docs
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File ".../src/ert/services/_base_service.py", line 146, in run
    self._set_conn_info(conn_info)
  File ".../src/ert/services/_base_service.py", line 342, in set_conn_info
    with open(path, "w", encoding="utf-8") as f:

```

**Comment by frode-aarstad** [comment]
What should be the correct behavior here? Raise a better exception stating that no storage existes for the given configuration or should we create an empty storage and start with no data?

**Comment by eivindjahren** [comment]
@frode-aarstad All other commands create an empty storage when not present. That could also be acceptable behavior.
