### ISSUE TITLE
Clicking observations in Experiment manager crashes ert

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#8081]
**To reproduce**
Steps to reproduce the behaviour:
1. Run an experiment
2. Open Experiment manager
3. Select and experiment and click `Observations`

**Expected behaviour**
For ert to not crash, get:

```
Traceback (most recent call last):
  File "/Users/OYVEID/projects/ert/ert/src/ert/gui/ertwidgets/storage_info_widget.py", line 210, in _currentItemChanged
    ax.errorbar(
  File "/Users/OYVEID/projects/ert/arm_env/lib/python3.11/site-packages/matplotlib/__init__.py", line 1465, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/OYVEID/projects/ert/arm_env/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 3572, in errorbar
    raise ValueError("'x' and 'y' must have the same size")
ValueError: 'x' and 'y' must have the same size
[1]    2770 abort      ert gui snake_oil.ert
```

**Comment by dafeda** [comment]
I tried this and got no error, but if I select an ensemble and then click `Observations`, I get the following:

```
Traceback (most recent call last):
  File "/Users/FCUR/git/ert/src/ert/gui/ertwidgets/storage_info_widget.py", line 210, in _currentItemChanged
    ax.errorbar(
  File "/Users/FCUR/envs/arm/.venvfmu/lib/python3.10/site-packages/matplotlib/__init__.py", line 1465, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/FCUR/envs/arm/.venvfmu/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 3583, in errorbar
    (data_line, base_style), = self._get_lines._plot_args(
  File "/Users/FCUR/envs/arm/.venvfmu/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 502, in _plot_args
    raise ValueError(f"x and y can be no greater than 2D, but have "
ValueError: x and y can be no greater than 2D, but have shapes (1,) and (1, 1, 1)
```
