### ISSUE TITLE
test_that_all_snake_oil_visualisations_matches_snapshot is flaky

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#8427]
`test_that_all_snake_oil_visualisations_matches_snapshot` fails on nightly tests ([logs for failing run](https://github.com/equinor/komodo-releases/actions/runs/10311505044/job/28545872626)) but passes when restarted ([logs for successful run](https://github.com/equinor/komodo-releases/actions/runs/10311505044))

The same happened the day before: ([fail](https://github.com/equinor/komodo-releases/actions/runs/10293746068/job/28491334497) -> [success](https://github.com/equinor/komodo-releases/actions/runs/10293746068))

```
ERROR unit_tests/gui/plottery/test_plotting_of_snake_oil.py::test_that_all_snake_oil_visualisations_matches_snapshot[plot_figure5] - Failed: SETUP ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/ertwidgets/__init__.py", line 14, in wrapper
    res = func(*arg)
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_window.py", line 361, in keySelected
    self.updatePlot()
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_window.py", line 186, in updatePlot
    ensemble_to_data_map[ensemble] = self._api.data_for_key(
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_api.py", line 158, in data_for_key
    response = client.get(
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/pytest_timeout.py", line 313, in handler
    timeout_sigalrm(item, settings)
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/pytest_timeout.py", line 498, in timeout_sigalrm
    pytest.fail("Timeout >%ss" % settings.timeout)
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/outcomes.py", line 178, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: Timeout >360.0s
________________________________________________________________________________
ERROR unit_tests/gui/plottery/test_plotting_of_snake_oil.py::test_that_all_snake_oil_visualisations_matches_snapshot[plot_figure2] - Failed: SETUP ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/ertwidgets/__init__.py", line 14, in wrapper
    res = func(*arg)
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_window.py", line 361, in keySelected
    self.updatePlot()
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_window.py", line 255, in updatePlot
    plot_widget.updatePlot(
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_widget.py", line 157, in updatePlot
    self._canvas.draw()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 400, in draw
    self.figure.draw(self.renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/figure.py", line 3175, in draw
    mimage._draw_list_compositing_images(
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axes/_base.py", line 3064, in draw
    mimage._draw_list_compositing_images(
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axis.py", line 1392, in draw
    tick.draw(renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axis.py", line 301, in draw
    artist.draw(renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/lines.py", line 836, in draw
    tpath, affine = (self._get_transformed_path()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/transforms.py", line 2781, in get_transformed_points_and_affine
    return self._transformed_points, self.get_affine()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/transforms.py", line 2799, in get_affine
    def get_affine(self):
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/pytest_timeout.py", line 313, in handler
    timeout_sigalrm(item, settings)
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/pytest_timeout.py", line 498, in timeout_sigalrm
    pytest.fail("Timeout >%ss" % settings.timeout)
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/outcomes.py", line 178, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: Timeout >360.0s
________________________________________________________________________________
ERROR unit_tests/gui/plottery/test_plotting_of_snake_oil.py::test_that_all_snake_oil_visualisations_matches_snapshot[plot_figure0] - Failed: TEARDOWN ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/ertwidgets/__init__.py", line 14, in wrapper
    res = func(*arg)
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_window.py", line 361, in keySelected
    self.updatePlot()
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_window.py", line 255, in updatePlot
    plot_widget.updatePlot(
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_widget.py", line 157, in updatePlot
    self._canvas.draw()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 400, in draw
    self.figure.draw(self.renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/figure.py", line 3169, in draw
    self.get_layout_engine().execute(self)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/layout_engine.py", line 184, in execute
    kwargs = get_tight_layout_figure(
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/_tight_layout.py", line 266, in get_tight_layout_figure
    kwargs = _auto_adjust_subplotpars(fig, renderer,
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/_tight_layout.py", line 82, in _auto_adjust_subplotpars
    bb += [martist._get_tightbbox_for_layout_only(ax, renderer)]
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/artist.py", line 1415, in _get_tightbbox_for_layout_only
    return obj.get_tightbbox(*args, **{**kwargs, "for_layout_only": True})
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axes/_base.py", line 4387, in get_tightbbox
    ba = martist._get_tightbbox_for_layout_only(axis, renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/artist.py", line 1415, in _get_tightbbox_for_layout_only
    return obj.get_tightbbox(*args, **{**kwargs, "for_layout_only": True})
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axis.py", line 1337, in get_tightbbox
    self._update_label_position(renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axis.py", line 2614, in _update_label_position
    bboxes, bboxes2 = self._get_tick_boxes_siblings(renderer=renderer)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axis.py", line 2148, in _get_tick_boxes_siblings
    ticks_to_draw = axis._update_ticks()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axis.py", line 1282, in _update_ticks
    minor_locs = self.get_minorticklocs()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axis.py", line 1503, in get_minorticklocs
    major_locs = self.major.locator()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/ticker.py", line 2135, in __call__
    vmin, vmax = self.axis.get_view_interval()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axis.py", line 2255, in getter
    return getattr(getattr(self.axes, lim_name), attr_name)
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axes/_base.py", line 857, in viewLim
    self._unstale_viewLim()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axes/_base.py", line 844, in _unstale_viewLim
    need_scale = {
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/axes/_base.py", line 845, in <dictcomp>
    name: any(ax._stale_viewlims[name]
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/pytest_timeout.py", line 313, in handler
    timeout_sigalrm(item, settings)
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/pytest_timeout.py", line 498, in timeout_sigalrm
    pytest.fail("Timeout >%ss" % settings.timeout)
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/outcomes.py", line 178, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: Timeout >360.0s
```

**Comment by eivindjahren** [comment]
Seems like its simply a timeout. I will try to see what we can do to speed it up

**Comment by sondreso** [comment]
This still happens: https://github.com/equinor/komodo-releases/actions/runs/10396658076/job/28791758605

**Comment by eivindjahren** [comment]
Alright, I will try to reproduce this on rgs again.

**Comment by eivindjahren** [comment]
I have been able to reproduce this on rgs, and seems to be due to slow hardware. Will try to just increaste the timelimit.
