### ISSUE TITLE
KeyError opening plotter for not run case

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#855]
Opening ert with a config file and then pressing create plot will:

Not provide any results for `GEN_KW` parameters (Seems like data from storage is empty, unsure if storage is populated, but I thought that was supposed to happen on startup?)

Crash when trying to plot a `GEN_DATA` keyword (in this case it has observations, unsure if that is required)

```
ert gui poly.ert 
Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-py36/root/lib/python3.6/site-packages/ert_gui/tools/plot/plot_window.py", line 95, in currentPlotChanged
    case_to_data_map = {case: self._api.data_for_key(case, key)[key] for case in cases}
  File "/prog/res/komodo/bleeding-py36/root/lib/python3.6/site-packages/ert_gui/tools/plot/plot_window.py", line 95, in <dictcomp>
    case_to_data_map = {case: self._api.data_for_key(case, key)[key] for case in cases}
  File "/prog/res/komodo/bleeding-py36/root/lib/python3.6/site-packages/pandas/core/frame.py", line 2926, in __getitem__
    return self._getitem_multilevel(key)
  File "/prog/res/komodo/bleeding-py36/root/lib/python3.6/site-packages/pandas/core/frame.py", line 2972, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "/prog/res/komodo/bleeding-py36/root/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2397, in get_loc
    loc = self._get_level_indexer(key, level=0)
  File "/prog/res/komodo/bleeding-py36/root/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2666, in _get_level_indexer
    raise KeyError(key)
KeyError: 'POLY_RES@0'

Error message: Program received signal:6

See file: /tmp/ert_abort_dump.lpha.20200428-091012.log for more details of the crash.
Setting the environment variable "ERT_SHOW_BACKTRACE" will show the backtrace on stderr.
Aborted (core dumped)
```
Issue recreated also on testing-py36/testing-py27

**Comment by lars-petter-hauge** [comment]
Likely related to https://github.com/equinor/ert/issues/849
