### ISSUE TITLE
Assertion error happening in storage migration

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#8585]
```
Traceback (most recent call last):
File ".../lib64/python3.8/site-packages/ert/__main__.py", line 683, in main
args.func(args, context.plugin_manager)
File ".../python3.8/site-packages/ert/__main__.py", line 190, in run_gui_wrapper
run_gui(args, ert_plugin_manager)
File ".../python3.8/site-packages/ert/gui/main.py", line 65, in run_gui
window, ens_path, ensemble_size, parameter_config = _start_initial_gui_window(
File ".../python3.8/site-packages/ert/gui/main.py", line 163, in _start_initial_gui_window
storage = open_storage(ert_config.ens_path, mode="w")
File ".../python3.8/site-packages/ert/storage/__init__.py", line 34, in open_storage
return LocalStorage(Path(path), Mode(mode))
File ".../python3.8/site-packages/ert/storage/local_storage.py", line 104, in __init__
self._migrate()
File ".../python3.8/site-packages/ert/storage/mode.py", line 105, in inner
return func(self_, *args, **kwargs)
File ".../site-packages/ert/storage/local_storage.py", line 474, in _migrate
raise e
File ".../python3.8/site-packages/ert/storage/local_storage.py", line 450, in _migrate
assert isinstance(version, int)
AssertionError
```

**Comment by oyvindeide** [comment]
In this case, version should never be zero though, as we should not try to migrate if there is nothing to migrate, so there might be a race condition somewhere.

**Comment by eivindjahren** [comment]
None is possible when [open](https://docs.python.org/3/library/functions.html#open) throws other errors, such as IsADirectoryError, PermissionError, TimeoutErrr, and InterruptError.
