### ISSUE TITLE
Handle missing path to runpath gracefully in scheduler

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#8866]
```
File "...site-packages/ert/ensemble_evaluator/_ensemble.py", line 270, in _evaluate_inner
    result = await self._scheduler.execute(min_required_realizations)
Unexpected exception in ensemble: 
  File "...site-packages/ert/scheduler/scheduler.py", line 288, in execute
    await self._monitor_and_handle_tasks(scheduling_tasks)
Unexpected exception in ensemble: 
  File "...site-packages/ert/scheduler/scheduler.py", line 251, in _monitor_and_handle_tasks
    raise task_exception
Unexpected exception in ensemble: 
  File "...site-packages/ert/scheduler/job.py", line 147, in run
    await self._submit_and_run_once(sem)
Unexpected exception in ensemble: 
  File "...site-packages/ert/scheduler/job.py", line 108, in _submit_and_run_once
    await self.driver.submit(
Unexpected exception in ensemble: 
  File "...site-packages/ert/scheduler/lsf_driver.py", line 301, in submit
    with tempfile.NamedTemporaryFile(
Unexpected exception in ensemble: 
  File "/usr/lib64/python3.8/tempfile.py", line 540, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
Unexpected exception in ensemble: 
  File "/usr/lib64/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
Unexpected exception in ensemble: 
FileNotFoundError: [Errno 2] No such file or directory: '/<DOES_NOT_EXIST>/realization-257/iter-0/.lsf_submit_uho0blrg.sh'
```

**Comment by berland** [comment]
Probably the same scenario as observed in:

```
Traceback (most recent call last):
Unexpected exception in ensemble:
File "/prog/res/komodo/2024.09.03-py38-rhel8/root/lib64/python3.8/site-packages/ert/ensemble_evaluator/_ensemble.py", line 269, in _evaluate_inner
self._scheduler.add_dispatch_information_to_jobs_file()
Unexpected exception in ensemble:
File "/prog/res/komodo/2024.09.03-py38-rhel8/root/lib64/python3.8/site-packages/ert/scheduler/scheduler.py", line 209, in add_dispatch_information_to_jobs_file
self._update_jobs_json(job.iens, job.real.run_arg.runpath)
Unexpected exception in ensemble:
File "/prog/res/komodo/2024.09.03-py38-rhel8/root/lib64/python3.8/site-packages/ert/scheduler/scheduler.py", line 323, in _update_jobs_json
Path(cert_path).write_text(self._ee_cert, encoding="utf-8")
Unexpected exception in ensemble:
File "/usr/lib64/python3.8/pathlib.py", line 1255, in write_text
with self.open(mode='w', encoding=encoding, errors=errors) as f:
Unexpected exception in ensemble:
File "/usr/lib64/python3.8/pathlib.py", line 1222, in open
return io.open(self, mode, buffering, encoding, errors, newline,
Unexpected exception in ensemble:
File "/usr/lib64/python3.8/pathlib.py", line 1078, in _opener
return self._accessor.open(self, flags, mode)
Unexpected exception in ensemble:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/xxxxx/realization-6/pred_ior_xxxxxx/.ee.pem'

```

**Comment by berland** [comment]
This can perhaps be mitigated by some code that will wait if the runpath does not exist yet.

**Comment by berland** [comment]
In theory, this should be possible to reproduce by issuing a `rm` call while running, and it is thinkable that users can do this.

**Comment by eivindjahren** [comment]
From what I understand, any exception raised during submit will bubble up to `_evaluate_inner` in `/ert/ensemble_evaluator/_ensemble.py`. Would it make sense to have an exception type that just marks the realization as failed due to a failed submit? Something like this:

```python 
        try:
            with tempfile.NamedTemporaryFile(
                dir=runpath,
                prefix=".lsf_submit_",
                suffix=".sh",
                mode="w",
                encoding="utf-8",
                delete=False,
            ) as script_handle:
                script_handle.write(script)
                script_path = Path(script_handle.name)
        except OSError as err:
            error_message = "Could not write submit command to runpath " + str(err)
            self._job_error_message_by_iens[iens] = error_message
            raise FailedSubmit(error_message) from err
```
instead of https://github.com/equinor/ert/blob/810bda726444499f0bbc4f65f469936f61f90b49/src/ert/scheduler/lsf_driver.py#L312
