### ISSUE TITLE
Investigate / resolve memory issues wrt large responses

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#9063]
Large datasets currently use a lot of memory when it comes to joining / viewing across realizations. This should be investigated. We know the data type of the dimensions/columns of these datasets, and the number of realizations (tenatively). This should be tested as follows:

1. Create a script to mock up some datasets, amounting up to a total of 50GiB across 200 files (one per realization), and do a "join across realizations" and check the memory usage.
2. If it is a problem, investigate ways to workaround this. It likely involves splitting it up into smaller parts, using more time/cpu traded for less memory usage. Some possible starting points: https://docs.pola.rs/api/python/stable/reference/api/polars.LazyFrame.sink_parquet.html . The problem mainly boils down to how to concatenate / join larger-than-RAM multiple parquet datasets, likely there are examples of this being already done/solved available on the web.

Example fail (with xarray, not Polars)
```
Traceback (most recent call last):
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/ert/gui/tools/manage_experiments/storage_info_widget.py", line 195, in _currentItemChanged
    response_ds = self._ensemble.load_responses(
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/ert/storage/local_ensemble.py", line 654, in load_responses
    return xr.combine_nested(loaded, concat_dim="realization")
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/xarray/core/combine.py", line 587, in combine_nested
    return _nested_combine(
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/xarray/core/combine.py", line 365, in _nested_combine
    combined = _combine_nd(
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/xarray/core/combine.py", line 239, in _combine_nd
    combined_ids = _combine_all_along_first_dim(
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/xarray/core/combine.py", line 275, in _combine_all_along_first_dim
    new_combined_ids[new_id] = _combine_1d(
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/xarray/core/combine.py", line 298, in _combine_1d
    combined = concat(
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/xarray/core/concat.py", line 248, in concat
    return _dataset_concat(
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/xarray/core/concat.py", line 589, in _dataset_concat
    combined_var = concat_vars(
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/xarray/core/variable.py", line 3194, in concat
    return Variable.concat(variables, dim, positions, shortcut, combine_attrs)
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/xarray/core/variable.py", line 2055, in concat
    data = duck_array_ops.concatenate(arrays, axis=axis)
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/xarray/core/duck_array_ops.py", line 322, in concatenate
    return _concatenate(as_shared_dtype(arrays), axis=axis)
  File "<__array_function__ internals>", line 200, in concatenate
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 52.8 GiB for an array with shape (207, 11796, 5803) and data type float32
Killed
```

**Comment by yngve-sk** [comment]
Resolved by https://github.com/equinor/ert/pull/9418
