### ISSUE TITLE
ERT hangs on mac when not given firewall permissions

### ISSUE THREAD

**Issue by jonathan-eq** [equinor/ert#9124]
### What happened? (You can include a screenshot if it helps explain)
ERT hangs often on mac sequoia 15.1 w/firewall enabled
After updating my mac, the test suddenly stopped working. It turns out ert completely hangs, with none of the realization boxes being drawn all. For some reason, this problem disappears when you disable the firewall. 
The issue occurs when you press Deny on this dialog:
![Image](https://github.com/user-attachments/assets/dc3e610d-6f43-477e-a061-2b11946f24a8)

Then ert will hang here:
![Image](https://github.com/user-attachments/assets/d759e359-e13d-4fad-8c8a-88935d51acda)

### What did you expect to happen?

Ert is not hanging, and instead displays an error message when this error occurs. 

### steps to reproduce

Start any ert experiment

### Environment where bug has been observed

- [ ] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [ ] python 3.11
- [x] python 3.12
- [x] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by jonathan-eq** [comment]
Logs:
```
2024-11-01 09:49:34,470 - ert.ensemble_evaluator.evaluator - ert_gui_simulation_thread - ERROR - Exception in evaluator task ensemble_task: Connection timeout to host wss://10.142.4.59:50133/healthcheck
Traceback: Traceback (most recent call last):
  File "/Users/JONAK/Documents/FMU/SCOUT/py312-arm-venv/lib/python3.12/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JONAK/Documents/FMU/SCOUT/py312-arm-venv/lib/python3.12/site-packages/aiohttp/connector.py", line 563, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JONAK/Documents/FMU/SCOUT/py312-arm-venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1032, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JONAK/Documents/FMU/SCOUT/py312-arm-venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JONAK/Documents/FMU/SCOUT/py312-arm-venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1098, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1148, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1181, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/JONAK/Documents/FMU/SCOUT/py312-arm-venv/lib/python3.12/site-packages/aiohttp/client.py", line 659, in _request
    async with ceil_timeout(
               ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/JONAK/Documents/FMU/SCOUT/ert/src/ert/ensemble_evaluator/_ensemble.py", line 195, in evaluate
    await wait_for_evaluator(
  File "/Users/JONAK/Documents/FMU/SCOUT/ert/src/ert/ensemble_evaluator/_wait_for_evaluator.py", line 70, in wait_for_evaluator
    await attempt_connection(
  File "/Users/JONAK/Documents/FMU/SCOUT/ert/src/ert/ensemble_evaluator/_wait_for_evaluator.py", line 30, in attempt_connection
    async with aiohttp.ClientSession() as session, session.request(
                                                   ^^^^^^^^^^^^^^^^
  File "/Users/JONAK/Documents/FMU/SCOUT/py312-arm-venv/lib/python3.12/site-packages/aiohttp/client.py", line 1359, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/Users/JONAK/Documents/FMU/SCOUT/py312-arm-venv/lib/python3.12/site-packages/aiohttp/client.py", line 667, in _request
    raise ConnectionTimeoutError(
aiohttp.client_exceptions.ConnectionTimeoutError: Connection timeout to host wss://10.142.4.59:50133/healthcheck

2024-11-01 09:49:34,471 - websockets.server - ert_gui_simulation_thread - INFO - server closing
2024-11-01 09:49:34,477 - websockets.server - ert_gui_simulation_thread - INFO - server closed
2024-11-01 09:49:34,477 - ert.ensemble_evaluator.evaluator - ert_gui_simulation_thread - ERROR - Connection timeout to host wss://10.142.4.59:50133/healthchec
```

**Comment by jonathan-eq** [comment]
```
2024-11-01 10:07:16,509 - ert.services.storage_service - MainThread - INFO - Could not connect to http://AC-MY_MAC:51828: HTTPConnectionPool(host='ac-MY_MAC', port=51828): Max retries exceeded with url: /healthcheck (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x325699460>: Failed to resolve 'ac-MY_MAC' ([Errno 8] nodename nor servname provided, or not known)"))
```

**Comment by sondreso** [comment]
While this happens due to firewall settings on mac, the general fix to this problem is to give nice error feedback to the user if we are unable to connect at all. It should not result in a traceback in the terminal.
