### ISSUE TITLE
Bad UX for permission errors occuring in storage

### ISSUE THREAD

**Issue by berland** [equinor/ert#9169]
### What happened? (You can include a screenshot if it helps explain)

Doing
```
$ git clean -xfd
$ ert ensemble_experiment poly.ert
$ chmod 000 storage/ensemble/*/realization-*/*nc
$ ert gui poly.ert
```

Then click 'Create plot' and try to plot something

This gives a popup window with a very long exception (see below). Parent directories with 000-mode gives a nice hard error when starting up Ert.  It is maybe far fetched to provide a good UX in this scenario, but there are logged exceptions implying this could be one realistic scenario.

```
 Please report this error and try restarting the application.Traceback (most recent call last):
  File "/private/havb/venv/lib64/python3.11/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
           ~~~~~~~~~~~^^^^^^^^^^^
  File "/private/havb/venv/lib64/python3.11/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
            ~~~~~~~~~~~^^^^^
KeyError: [<function _open_scipy_netcdf at 0x7f1c00db60c0>, ('/private/havb/projects/ert/test-data/ert/poly_example/storage/ensembles/a5cc054b-a485-4b56-b1d7-b90776faaa43/realization-0/COEFFS.nc',), 'r', (('mmap', None), ('version', 2)), '27097ab6-cb8c-460d-85fc-861630c567c7']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/havb/venv/lib64/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/private/havb/venv/lib64/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/private/havb/venv/lib64/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/private/havb/venv/lib64/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/private/havb/venv/lib64/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/private/havb/venv/lib64/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/private/havb/venv/lib64/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/private/havb/venv/lib64/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/private/havb/venv/lib64/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/private/havb/venv/lib64/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/private/havb/venv/lib64/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/private/havb/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/venv/lib64/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/projects/ert/src/ert/dark_storage/endpoints/records.py", line 80, in get_ensemble_record
    dataframe = data_for_key(storage.get_ensemble(ensemble_id), name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/projects/ert/src/ert/dark_storage/common.py", line 135, in data_for_key
    data = ensemble.load_parameters(group)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/projects/ert/src/ert/storage/local_ensemble.py", line 583, in load_parameters
    return self._load_dataset(group, realizations)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/projects/ert/src/ert/storage/local_ensemble.py", line 554, in _load_dataset
    datasets = [
               ^
  File "/private/havb/projects/ert/src/ert/storage/local_ensemble.py", line 555, in <listcomp>
    xr.open_dataset(p, engine="scipy")
  File "/private/havb/venv/lib64/python3.11/site-packages/xarray/backends/api.py", line 588, in open_dataset
    backend_ds = backend.open_dataset(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/venv/lib64/python3.11/site-packages/xarray/backends/scipy_.py", line 332, in open_dataset
    ds = store_entrypoint.open_dataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/venv/lib64/python3.11/site-packages/xarray/backends/store.py", line 43, in open_dataset
    vars, attrs = filename_or_obj.load()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/venv/lib64/python3.11/site-packages/xarray/backends/common.py", line 221, in load
    (_decode_variable_name(k), v) for k, v in self.get_variables().items()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/venv/lib64/python3.11/site-packages/xarray/backends/scipy_.py", line 198, in get_variables
    (k, self.open_store_variable(k, v)) for k, v in self.ds.variables.items()
                                                    ^^^^^^^
  File "/private/havb/venv/lib64/python3.11/site-packages/xarray/backends/scipy_.py", line 187, in ds
    return self._manager.acquire()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/venv/lib64/python3.11/site-packages/xarray/backends/file_manager.py", line 193, in acquire
    file, _ = self._acquire_with_cache_info(needs_lock)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/venv/lib64/python3.11/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/venv/lib64/python3.11/site-packages/xarray/backends/scipy_.py", line 126, in _open_scipy_netcdf
    return scipy.io.netcdf_file(filename, mode=mode, mmap=mmap, version=version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/havb/venv/lib64/python3.11/site-packages/scipy/io/_netcdf.py", line 247, in __init__
    self.fp = open(self.filename, '%sb' % omode)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/private/havb/projects/ert/test-data/ert/poly_example/storage/ensembles/a5cc054b-a485-4b56-b1d7-b90776faaa43/realization-0/COEFFS.nc'
 from url: http://127.0.0.1:51824/ensembles/a5cc054b-a485-4b56-b1d7-b90776faaa43/records/COEFFS%253Ac.
```

### steps to reproduce

```Python

```

### Environment where bug has been observed

- [ ] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [x] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [x] rhel8
- [x] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by berland** [comment]
This issue is an attempt at reproducing the following exception found in the log:
```
Traceback (most recent call last):
Unexpected exception in ensemble: 
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/ert/ensemble_evaluator/_ensemble.py", line 259, in _evaluate_inner
    result = await self._scheduler.execute(min_required_realizations)
Unexpected exception in ensemble: 
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/ert/scheduler/scheduler.py", line 302, in execute
    await self._monitor_and_handle_tasks(scheduling_tasks)
Unexpected exception in ensemble: 
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/ert/scheduler/scheduler.py", line 248, in _monitor_and_handle_tasks
    raise task_exception
Unexpected exception in ensemble: 
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/ert/scheduler/job.py", line 159, in run
    await self._handle_finished_forward_model()
Unexpected exception in ensemble: 
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/ert/scheduler/job.py", line 231, in _handle_finished_forward_model
    callback_status, status_msg = await forward_model_ok(self.real.run_arg)
Unexpected exception in ensemble: 
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/ert/callbacks.py", line 127, in forward_model_ok
    elif run_arg.ensemble_storage.has_failure(run_arg.iens):
Unexpected exception in ensemble: 
  File "/prog/res/komodo/2024.10.06-py38-rhel8/root/lib64/python3.8/site-packages/ert/storage/local_ensemble.py", line 444, in has_failure
    return (self._realization_dir(realization) / self._error_log_name).exists()
Unexpected exception in ensemble: 
  File "/usr/lib64/python3.8/pathlib.py", line 1407, in exists
    self.stat()
Unexpected exception in ensemble: 
  File "/usr/lib64/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
Unexpected exception in ensemble: 
PermissionError: [Errno 13] Permission denied: '/project/xxxxxx025_pred/ert/output/storage/pred_24_0xxxxxxx_mf_recirc/ensembles/eceef585-xxxx-xxxx-b9b4-f23812092e4f/realization-0/error.json'
```

This exception occurs if the `realization-0` directory is not readable.
