### ISSUE TITLE
Configuration not fully validated before starting the experiment

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#9200]
Currently, when we start the Everest server we also start the optimization process, and the path of the main config file is passed to the server. This means that parts of the config is only validated on the server, we should instead pass the complete, validated, configuration to the server to start the experiment.

**Comment by oyvindeide** [comment]
Blocked by: https://github.com/equinor/ert/issues/8905

**Comment by oyvindeide** [comment]
Another side effect of this is that an empty configuration file is considered valid in Everest, but fails once submitted to the server, take this test:

```python
@pytest.mark.timeout(60)  # Simulation might not finish
@pytest.mark.integration_test
@pytest.mark.xdist_group(name="starts_everest")
async def test_starting_not_in_folder(tmp_path, monkeypatch):
    async def server_running():
        while True:
            event = await driver.event_queue.get()
            if isinstance(event, FinishedEvent) and event.iens == 0:
                return event

    os.makedirs(tmp_path / "new_folder")
    monkeypatch.chdir(tmp_path / "new_folder")
    everest_config = EverestConfig.with_defaults()
    everest_config.dump("minimal_config.yml")
    everest_config.config_path = Path("minimal_config.yml").absolute()
    makedirs_if_needed(everest_config.output_dir, roll_if_exists=True)
    driver = await start_server(everest_config, debug=True)
    final_state = await server_running()
    assert final_state.returncode == 0
    status = everserver_status(everest_config)
    assert status["status"] == ServerStatus.completed
```

which failed on the server with:
```
Optimization run failed, with error: Traceback (most recent call last):
  File "/data/projects/ert/src/everest/detached/jobs/everserver.py", line 278, in main
    run_model = EverestRunModel.create(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/ert/src/ert/run_models/everest_run_model.py", line 381, in create
    ert_config = everest_to_ert_config(cls._add_defaults(ever_config))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/ert/src/everest/simulator/everest_to_ert.py", line 510, in everest_to_ert_config
    config_dict = _everest_to_ert_config_dict(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/ert/src/everest/simulator/everest_to_ert.py", line 496, in _everest_to_ert_config_dict
    _extract_forward_model(ever_config, ert_config)
  File "/data/projects/ert/src/everest/simulator/everest_to_ert.py", line 434, in _extract_forward_model
    forward_model = _extract_data_operations(ever_config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/ert/src/everest/simulator/everest_to_ert.py", line 371, in _extract_data_operations
    is_dir = _is_dir_all_geo(source, ever_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/ert/src/everest/simulator/everest_to_ert.py", line 329, in _is_dir_all_geo
    raise AssertionError(msg)
AssertionError: Expected realizations when analysing data installation source
```

I would expect this to be validated up front, and never dispatched to the server.

**Comment by DanSava** [comment]
I agree we should validate/create the ert config before we start the server but this error might also be a bug. We should be able to create an ert config with a default everest config.
