### ISSUE TITLE
plugin_manager.__exit__ can result in FileNotFoundError when directory does not exist

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#9224]
```
Traceback (most recent call last):
  File ".../ert/__main__.py", line 681, in main
    args.func(args, context.plugin_manager)
  File ".../ert/plugins/plugin_manager.py", line 394, in __exit__
    shutil.rmtree(self.tmp_dir)
  File "/usr/lib64/python3.8/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib64/python3.8/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc_72f9i_'
```

**Comment by eivindjahren** [comment]
Fixed in eab23bc231e73deeaf72de6bde916b4d4dfeada7
