### ISSUE TITLE
Not possible to submit Everserver to lsf

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#9291]
### What happened? (You can include a screenshot if it helps explain)

A user got a everest server error when tying to run with `lsf`, the traceback was:
```
Traceback (most recent call last):
  File "/path/to/root/bin/everserver", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/path/to/root/lib64/python3.11/site-packages/everest/detached/jobs/everserver.py", line 230, in main
    config = EverestConfig.load_file(options.config_file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/root/lib64/python3.11/site-packages/everest/config/everest_config.py", line 729, in load_file
    return EverestConfig.model_validate(config_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/root/lib64/python3.11/site-packages/pydantic/main.py", line 593, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/root/lib64/python3.11/site-packages/everest/config/everest_config.py", line 294, in validate_forward_model_job_name_installed
    installed_jobs_name += get_system_installed_jobs()  # system jobs
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/root/lib64/python3.11/site-packages/everest/config/everest_config.py", line 81, in get_system_installed_jobs
    return list(_dummy_ert_config().installed_forward_model_steps.keys())
                ^^^^^^^^^^^^^^^^^^^
  File "/path/to/root/lib64/python3.11/site-packages/everest/config/everest_config.py", line 73, in _dummy_ert_config
    site_config = ErtConfig.read_site_config()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/root/lib64/python3.11/site-packages/ert/config/ert_config.py", line 604, in read_site_config
    read_file(site_config_file),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/root/lib64/python3.11/site-packages/ert/config/parsing/lark_parser.py", line 442, in read_file
    with open(file, encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc7as9m8b/site-config'
```

### steps to reproduce

No steps to reproduce at the moment, but testing a model using lsf will be a good starting point. Experienced with Everest==11.1.2

### Environment where bug has been observed

- [ ] python 3.10
- [x] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [x] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by oyvindeide** [comment]
Not able to reproduce this, and a new version has also released now. Could have been a temporary problem with lsf.
