### ISSUE TITLE
Disk issues appear as JSON read errors

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#933]
A user got

```
Traceback (most recent call last):
  File "/prog/res/komodo/2020.07.rc1-py36/root/lib/python3.6/site-packages/ert_shared/tracker/qt.py", line 61, in _detailed
    self._event_handler(self._detailed_event())
  File "/prog/res/komodo/2020.07.rc1-py36/root/lib/python3.6/site-packages/ert_shared/tracker/base.py", line 154, in _detailed_event
    return DetailedEvent(*self._model.getDetailedProgress())
  File "/prog/res/komodo/2020.07.rc1-py36/root/lib/python3.6/site-packages/ert_shared/models/base_run_model.py", line 267, in getDetailedProgress
    self.updateDetailedProgress()
  File "/prog/res/komodo/2020.07.rc1-py36/root/lib/python3.6/site-packages/ert_shared/models/base_run_model.py", line 23, in dispatch
    return method( self, *args , **kwargs)
  File "/prog/res/komodo/2020.07.rc1-py36/root/lib/python3.6/site-packages/ert_shared/models/base_run_model.py", line 255, in updateDetailedProgress
    self.update_progress_for_index(iteration, idx, run_arg)
  File "/prog/res/komodo/2020.07.rc1-py36/root/lib/python3.6/site-packages/ert_shared/models/base_run_model.py", line 234, in update_progress_for_index
    fms = ForwardModelStatus.load(run_arg.runpath, num_retry=1)
  File "/prog/res/komodo/2020.07.rc1-py36/root/lib/python3.6/site-packages/res/job_queue/forward_model_status.py", line 135, in load
    status = cls.try_load(path)
  File "/prog/res/komodo/2020.07.rc1-py36/root/lib/python3.6/site-packages/res/job_queue/forward_model_status.py", line 124, in try_load
    status.add_job(ForwardModelJobStatus.load(job, state, path))
  File "/prog/res/komodo/2020.07.rc1-py36/root/lib/python3.6/site-packages/res/job_queue/forward_model_status.py", line 65, in load
    end_time = _deserialize_date(data["end_time"])
KeyError: 'end_time'
```

We should catch the exception and

1. inform the user that we failed to read a file on **disk** (pointing to potential disk issues, which is common)
1. tell the user **what** file we failed to read, so that the user can take a look at this file. Maybe the user is proficient and sees that the file is valid JSON. Disk issues then become a likely suspect.
1. show the exception—maybe the JSON indeed is bad (like in the case of poorly serialized data)

**Comment by jondequinor** [comment]
Will also be mitigated largely after killing the shared disk assumption, since this error is most likely either an actual NFS failure, or a read in the middle of the `status.json` write. See #1032

**Comment by sondreso** [comment]
> Will also be mitigated largely after killing the shared disk assumption

This has now happened, so closing this issue
