### ISSUE TITLE
Missing responses.json when opening ert

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#9493]
### What happened? (You can include a screenshot if it helps explain)

The following exception was found in the logs: 

```
Traceback (most recent call last):
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/__main__.py", line 690, in main
args.func(args, context.plugin_manager)
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/__main__.py", line 195, in run_gui_wrapper
run_gui(args, ert_plugin_manager)
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/gui/main.py", line 55, in run_gui
window, ens_path = _start_initial_gui_window(args, log_handler, plugin_manager)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/gui/main.py", line 128, in _start_initial_gui_window
_main_window = _setup_main_window(
^^^^^^^^^^^^^^^^^^^
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/gui/main.py", line 169, in _setup_main_window
window.post_init()
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/gui/main_window.py", line 231, in post_init
experiment_panel = ExperimentPanel(
^^^^^^^^^^^^^^^^
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/gui/simulation/experiment_panel.py", line 152, in __init__
EvaluateEnsemblePanel(ensemble_size, run_path, notifier),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/gui/simulation/evaluate_ensemble_panel.py", line 54, in __init__
self._realizations_from_fs()
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/gui/simulation/evaluate_ensemble_panel.py", line 88, in _realizations_from_fs
missing_responses = ~ensemble.get_realization_mask_with_responses()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/storage/local_ensemble.py", line 251, in get_realization_mask_with_responses
[
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/storage/local_ensemble.py", line 252, in <listcomp>
self._responses_exist_for_realization(i, key)
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/storage/local_ensemble.py", line 300, in _responses_exist_for_realization
if not self.experiment.response_configuration:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/storage/local_experiment.py", line 300, in response_configuration
for data in self.response_info.values():
^^^^^^^^^^^^^^^^^^
File "/prog/res/komodo/2024.11.11-py311-rhel8/root/lib64/python3.11/site-packages/ert/storage/local_experiment.py", line 263, in response_info
raise ValueError(f"{self._responses_file!s} does not exist")
ValueError: responses.json does not exist
```

Link to trace: https://fmu-dashboard-fdeqekb8chekcqhu.neu.grafana.azure.com/d/ae0bpm0169ou8e/traces?from=now-30d&to=now&var-operation_id=352106f845ac2bdc5ffc781da018384c

### What did you expect to happen?

Not crash

### steps to reproduce

```Python
TBD
```

### Environment where bug has been observed

- [x] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [x] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by jonathan-eq** [comment]
This was fixed by e48000189c43824c95b4daea5de139435394b056. Will backport

**Comment by jonathan-eq** [comment]
I want to disable the buttons for ensembles on an invalid experiment, so the user won't be able to interact with those.

**Comment by jonathan-eq** [comment]
The error can also come from `forward_model_ok`

**Comment by jonathan-eq** [comment]
@berland and I looked thoroughly through the logs, and found out that most of those errors occur when the user deletes the storage in the midst of a run. It was easily reproducable, and the best solution would be to not run forward_model_ok if this error has occured for a previous realization.

**Comment by xjules** [comment]
Could you @jonathan-eq test it with cli when running from a particular "invalid" experiment?

**Comment by eivindjahren** [comment]
Turns out this has to do with the user wishing to delete experiments/ensembles and not having any good way of doing so. We will solve this by implementing https://github.com/equinor/ert/issues/7043
