### ISSUE TITLE
Uncaught exception in update

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#9542]
The following exception can occurr
```
E        Traceback (most recent call last):
E         File "/.../src/ert/run_models/base_run_model.py", line 339, in start_simulations_thread
E           self.run_experiment(
E         File "/usr/lib/python3.12/contextlib.py", line 81, in inner
E           return func(*args, **kwds)
E                  ^^^^^^^^^^^^^^^^^^^
E         File "/.../src/ert/run_models/multiple_data_assimilation.py", line 144, in run_experiment
E           posterior = self.update(
E                       ^^^^^^^^^^^^
E         File "/.../src/ert/run_models/base_run_model.py", line 800, in update
E           smoother_update(
E         File "/.../src/ert/analysis/_es_update.py", line 808, in smoother_update
E           raise e
E         File "/.../src/ert/analysis/_es_update.py", line 782, in smoother_update
E           analysis_ES(
E         File "/.../src/ert/analysis/_es_update.py", line 528, in analysis_ES
E           T = smoother_es.compute_transition_matrix(Y=S, alpha=1.0, truncation=truncation)
E               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E         File "/.../iterative_ensemble_smoother/esmda.py", line 350, in compute_transition_matrix
E           return inversion_func(
E                  ^^^^^^^^^^^^^^^
E         File "/.../iterative_ensemble_smoother/esmda_inversion.py", line 229, in inversion_exact_cholesky
E           T = sp.linalg.solve(C_DD, D - Y, **solver_kwargs)
E               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E         File "/.../scipy/linalg/_basic.py", line 147, in solve
E           a1 = atleast_2d(_asarray_validated(a, check_finite=check_finite))
E                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E         File "/.../scipy/_lib/_util.py", line 321, in _asarray_validated
E           a = toarray(a)
E               ^^^^^^^^^^
E         File "/.../numpy/lib/function_base.py", line 630, in asarray_chkfinite
E           raise ValueError(
E       ValueError: array must not contain infs or NaNs
```

In `_es_update` the `S` matrix given to `compute_transition_matrix` was
```
[[1.6195932e+38 1.4486901e+38 1.3988991e+38 1.3017426e+38 1.0995318e+38
  9.7001770e+37 9.4424200e+37 1.3988531e+38 1.3840539e+38 1.2094726e+38
  2.0533039e+38 1.0281358e+38 1.3905423e+38 1.0772866e+38 1.0705529e+38
  1.8563062e+38 1.2991961e+38 1.5852976e+38 1.6405926e+38 1.0221135e+38
  1.3977443e+38 9.4329532e+37 1.2275534e+38 1.3926355e+38]]
```

This can be provoked by changing `test-data/ert/poly_example/coeff_priors` to
```
a UNIFORM 0 1
b UNIFORM 0 2
c LOGNORMAL 87.69503878043986 0.32072337557935304
```

and running `ert es_mda test-data/ert/poly_example/poly.ert`

**Comment by eivindjahren** [comment]
This is just an overflow of float32 values, and we should probably not consider it further.
