### ISSUE TITLE
Uninformative error message in update: "Matrix is singular."

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#9581]
![Image](https://github.com/user-attachments/assets/563f25df-2f22-4a17-ae1a-29d5167c09ca)

This behavior can be reproduced with this setup: https://github.com/eivindjahren/ert/tree/update_err_msgs/test-data/ert/counter_examples/matrix-is-singular-0

This is the traceback of the thrown error: 
```

Traceback (most recent call last):
  File "/../ert/src/ert/gui/simulation/run_dialog.py", line 426, in _on_event
    @Slot(object)

  File "/../ert/src/_ert/threading.py", line 85, in _handler
    raise current_exception
_ert.threading.ErtThreadError: Matrix is singular. in thread 'ert_gui_simulation_thread'
 Traceback (most recent call last):
  File "/../ert/src/_ert/threading.py", line 57, in run
    super().run()
  File "/.../opentelemetry/instrumentation/threading/__init__.py", line 129, in __wrap_threading_run
    return call_wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/../ert/src/ert/gui/simulation/run_dialog.py", line 354, in run
    self._run_model.start_simulations_thread(
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/../ert/src/ert/run_models/base_run_model.py", line 355, in start_simulations_thread
    raise e
  File "/../ert/src/ert/run_models/base_run_model.py", line 331, in start_simulations_thread
    self.run_experiment(
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/../ert/src/ert/run_models/ensemble_smoother.py", line 98, in run_experiment
    posterior = self.update(prior, ensemble_format % 1)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/../ert/src/ert/run_models/base_run_model.py", line 792, in update
    smoother_update(
  File "/../ert/src/ert/analysis/_es_update.py", line 798, in smoother_update
    raise e
  File "/../ert/src/ert/analysis/_es_update.py", line 772, in smoother_update
    analysis_ES(
  File "/../ert/src/ert/analysis/_es_update.py", line 518, in analysis_ES
    T = smoother_es.compute_transition_matrix(Y=S, alpha=1.0, truncation=truncation)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../iterative_ensemble_smoother/esmda.py", line 350
, in compute_transition_matrix
    return inversion_func(
           ^^^^^^^^^^^^^^^
  File "/.../iterative_ensemble_smoother/esmda_inversion.py"
, line 229, in inversion_exact_cholesky
    T = sp.linalg.solve(C_DD, D - Y, **solver_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../scipy/linalg/_basic.py", line 253, in solve
    _solve_check(n, info)
  File "/.../scipy/linalg/_basic.py", line 40, in _solve_che
ck
    raise LinAlgError('Matrix is singular.')
```
On the 518 in analysis_ES you have
```
S = [[ 5.41128099e-01  4.18017358e-01  1.92616379e+00 -1.80390090e-01
   4.79791343e-01  3.51417333e-01  5.72160304e-01  1.65839744e+00
   9.23609674e-01  2.91104484e+00  1.09367836e+00  4.90967691e-01
   1.87923205e+00  9.95449364e-01  6.24057531e-01  1.35721266e+00
  -7.94656456e-01  1.37885749e+00  7.49641955e-01  9.03066397e-01
   1.58006716e+00  3.82257372e-01]
 [ 2.77997760e+08  5.91964672e+08  1.09535437e+09  1.48903536e+08
   1.00341152e+08  1.57205338e+09  4.48524000e+08  9.86359360e+07
   3.28304384e+08  7.94838208e+08  3.76733152e+08  9.74643392e+08
   1.11974502e+09  8.17807680e+08  2.74955712e+08  5.33210240e+08
   6.61867840e+08  1.14594086e+09  5.09797536e+08  9.99212928e+08
   3.51346592e+08  2.21797424e+08]
 [ 1.00931052e+10  2.23225262e+10  4.19394396e+10  5.60238643e+09
   3.69361818e+09  5.97852160e+10  1.70850345e+10  3.51172096e+09
   1.24107284e+10  3.04161116e+10  1.42555617e+10  3.72751770e+10
   4.28353290e+10  3.12921764e+10  1.03405097e+10  2.02449121e+10
   2.52121620e+10  4.38122045e+10  1.93796137e+10  3.80739338e+10
   1.32994703e+10  8.34008525e+09]
 [ 3.77409110e+11  8.50411651e+11  1.60873500e+12  2.12931674e+11
   1.39139908e+11  2.28663545e+12  6.53376815e+11  1.29543733e+11
   4.73087902e+11  1.16628783e+12  5.43908987e+11  1.42915994e+12
   1.64223163e+12  1.20003769e+12  3.93054978e+11  7.73479727e+11
   9.64750213e+11  1.67967641e+12  7.40934681e+11  1.45756429e+12
   5.07085226e+11  3.16807774e+11]
 [ 4.65437184e+09  1.02317496e+10  1.91785513e+10  2.56923443e+09
   1.69939136e+09  2.73671209e+10  7.81974528e+09  1.62531008e+09
   5.68678963e+09  1.39104440e+10  6.53071002e+09  1.70484900e+10
   1.95912069e+10  1.43109571e+10  4.74228019e+09  9.26996378e+09
   1.15385518e+10  2.00390758e+10  8.87192576e+09  1.74233395e+10
   6.09307494e+09  3.82526259e+09]
 [ 8.60995840e+07  1.79823568e+08  3.29989568e+08  4.52595800e+07
   3.08716100e+07  4.75385248e+08  1.35451952e+08  3.07952080e+07
   9.95744400e+07  2.39512256e+08  1.14232136e+08  2.93812064e+08
   3.37481696e+08  2.46472960e+08  8.36006080e+07  1.61361808e+08
   1.99943424e+08  3.45533216e+08  1.54185536e+08  3.01849184e+08
   1.06465592e+08  6.74196400e+07]
 [ 1.31548840e+11  2.95199343e+11  5.57617578e+11  7.39624223e+10
   4.84162888e+10  7.93066537e+11  2.26636710e+11  4.53080556e+10
   1.64210164e+11  4.04293943e+11  1.88745990e+11  4.95419228e+11
   5.69301271e+11  4.15974031e+11  1.36520368e+11  2.68337054e+11
   3.34579040e+11  5.82265864e+11  2.57004028e+11  5.05421922e+11
   1.76009200e+11  1.10059749e+11]
 [ 2.26263925e+11  5.08874523e+11  9.62003665e+11  1.27455412e+11
   8.33517650e+10  1.36775192e+12  3.90843400e+11  7.77890775e+10
   2.83082654e+11  6.97455542e+11  3.25421990e+11  8.54655435e+11
   9.82093332e+11  7.17621887e+11  2.35265032e+11  4.62717092e+11
   5.77050116e+11  1.00447067e+12  4.43213578e+11  8.71763280e+11
   3.03425782e+11  1.89645685e+11]
 [ 1.99709594e+09  4.35621427e+09  8.14041242e+09  1.09446925e+09
   7.27072128e+08  1.16317553e+10  3.32274714e+09  7.00407872e+08
   2.42006451e+09  5.90506496e+09  2.77853875e+09  7.23792742e+09
   8.31712205e+09  6.07510477e+09  2.02030746e+09  3.94136678e+09
   4.90267648e+09  8.50806323e+09  3.77116416e+09  7.40246835e+09
   2.59234534e+09  1.62977203e+09]
 [ 7.38812232e+10  1.65353079e+11  3.12045240e+11  4.14447043e+10
   2.71628390e+10  4.43981169e+11  1.26883348e+11  2.54982267e+10
   9.19746642e+10  2.26257109e+11  1.05702236e+11  2.77256208e+11
   3.18608376e+11  2.32788197e+11  7.64970435e+10  1.50247195e+11
   1.87296367e+11  3.25861605e+11  1.43886959e+11  2.82913079e+11
   9.85812582e+10  6.16770273e+10]
 [ 4.66302350e+06  9.06790600e+06  1.60948450e+07  2.28480200e+06
   1.63513250e+06  2.35429880e+07  6.66429600e+06  1.70922450e+06
   4.98877700e+06  1.16907530e+07  5.72176200e+06  1.43680950e+07
   1.64875590e+07  1.20435440e+07  4.22478000e+06  8.01401750e+06
   9.85947900e+06  1.69188160e+07  7.64116600e+06  1.48894720e+07
   5.31148250e+06  3.39925275e+06]
 [ 7.85752320e+08  1.69649178e+09  3.15718246e+09  4.26481536e+08
   2.85003776e+08  4.51954432e+09  1.29047693e+09  2.77013568e+08
   9.41835264e+08  2.29056614e+09  1.08106419e+09  2.80802790e+09
   3.22648218e+09  2.35658931e+09  7.87350848e+08  1.53209178e+09
   1.90409178e+09  3.30108186e+09  1.46545075e+09  2.87473792e+09
   1.00851418e+09  6.35172288e+08]
 [ 7.02826250e+05  1.27394200e+06  2.17887075e+06  3.21551000e+05
   2.42134266e+05  3.24192325e+06  9.10475875e+05  2.63179281e+05
   6.96406438e+05  1.58382438e+06  7.99019062e+05  1.95100225e+06
   2.23651450e+06  1.63456612e+06  5.94494375e+05  1.10744238e+06
   1.35145800e+06  2.30163900e+06  1.05368700e+06  2.04182600e+06
   7.37574625e+05  4.76497062e+05]
 [ 3.98951916e+10  8.90050806e+10  1.67769326e+11  2.23175619e+10
   1.46491320e+10  2.38821851e+11  6.82534543e+10  1.38008986e+10
   4.95024988e+10  1.21653518e+11  5.68819753e+10  1.49076951e+11
   1.71313463e+11  1.25162275e+11  4.11921654e+10  8.08344207e+10
   1.00740653e+11  1.75213462e+11  7.74033572e+10  1.52158011e+11
   5.30562171e+10  3.32156723e+10]
 [ 6.12493361e+11  1.38236422e+12  2.61651222e+12  3.46025034e+11
   2.25962197e+11  3.71823005e+12  1.06236156e+12  2.09932108e+11
   7.69023082e+11  1.89682575e+12  8.84239827e+11  2.32436479e+12
   2.67084995e+12  1.95175920e+12  6.38756192e+11  1.25758603e+12
   1.56877980e+12  2.73179581e+12  1.20475340e+12  2.37028639e+12
   8.24281793e+11  5.14798387e+11]
 [ 2.05953495e+10  4.57694863e+10  8.61480878e+10  1.14814996e+10
   7.55092838e+09  1.22708763e+11  3.50689403e+10  7.14360269e+09
   2.54521201e+10  6.24725934e+10  2.92412211e+10  7.65573612e+10
   8.79772877e+10  6.42730803e+10  2.11915878e+10  4.15422669e+10
   5.17557494e+10  8.99811164e+10  3.97733929e+10  7.81651558e+10
   2.72775332e+10  1.70900132e+10]
 [ 2.24653860e+07  4.56151720e+07  8.26541440e+07  1.14869950e+07
   7.98117900e+06  1.19762112e+08  3.40444240e+07  8.11914100e+06
   2.51962980e+07  6.00107160e+07  2.88991920e+07  7.36655280e+07
   8.45839120e+07  6.17756320e+07  2.12282100e+07  4.06952080e+07
   5.02895560e+07  8.66703440e+07  3.88523520e+07  7.59269600e+07
   2.68988760e+07  1.71077160e+07]]
truncation=0.98
smoother_es= ies.ESMDA(
  covariance = array([0.11111112, 0.02      , 0.11000001, 2.7500002 , 2.7500002 ,
       0.49999997, 2.7500002 , 0.11000001, 0.43943575, 2.7500002 ,
       0.09913385, 0.11000001, 0.11111112, 2.7500002 , 0.17321391,
       0.8956781 , 0.49999997], dtype=float32),
observation_values=array([-1.5000000e+00,  5.9604645e-08,  0.0000000e+00,  0.0000000e+00,
       -2.4827461e+00,  9.9999997e-06,  0.0000000e+00,  0.0000000e+00,
        5.9604645e-08,  1.4012985e-45,  1.1000000e+00,  9.3329525e+00,
        1.9000000e+00,  1.4012985e-45, -1.1754944e-38, -3.0593535e-01,
        1.1754944e-38], dtype=float32),
rng=np.random.default_rng(1234),
alpha=1,
inversion='exact',
)
```

**Comment by eivindjahren** [comment]
The smallest example I have gotten for creating the error message is this:

```python
import iterative_ensemble_smoother as ies
import numpy as np

ies.ESMDA(
 covariance=np.array([0.11111112, 0.02, 0.11000001], dtype=np.float32),
 observations=np.array([-1.5000000e+00,  5.9604645e-08,  0.0000000e+00], dtype=np.float32),
 seed=np.random.default_rng(1234),
 alpha=1,
 inversion='exact'
).compute_transition_matrix(Y=np.array([[5.4112810e-01, 4.1801736e-01], [2.7799776e+08, 5.9196467e+08],[1.0093105e+10, 2.2322526e+10]], dtype=float32), alpha=1, truncation=0.98)
```
