### ISSUE TITLE
uninformative error message when writing updated zero values of  logarithmic data

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#9585]
![Image](https://github.com/user-attachments/assets/f340bba1-b709-47a8-a951-b72625778243)

Can be reproduced with https://github.com/eivindjahren/ert/tree/update_err_msgs/test-data/ert/counter_examples/math_domain_error_0

traceback of error is:

```
Traceback (most recent call last):
  File "/.../ert/src/ert/gui/simulation/run_dialog.py", line 426, in _on_event
    @Slot(object)

  File "/.../ert/src/_ert/threading.py", line 85, in _handler
    raise current_exception
_ert.threading.ErtThreadError: math domain error in thread 'ert_gui_simulation_thread'
 Traceback (most recent call last):
  File "/.../ert/src/_ert/threading.py", line 57, in run
    super().run()
  File "/.../opentelemetry_.py", line 129, in __wrap_threading_run
    return call_wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/.../ert/src/ert/gui/simulation/run_dialog.py", line 354, in run
    self._run_model.start_simulations_thread(
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/.../ert/src/ert/run_models/base_run_model.py", line 355, in start_simulati
    raise e
  File "/.../ert/src/ert/run_models/base_run_model.py", line 331, in start_simulati
    self.run_experiment(
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/.../ert/src/ert/run_models/ensemble_smoother.py", line 106, in run_experim
    self._evaluate_and_postprocess(
  File "/.../ert/src/ert/run_models/base_run_model.py", line 693, in _evaluate_and_
    create_run_path(
  File "/.../ert/src/ert/enkf_main.py", line 263, in create_run_path
    _generate_parameter_files(
  File "/.../ert/src/ert/enkf_main.py", line 111, in _generate_parameter_files
    export_values = node.write_to_runpath(Path(run_path), iens, fs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../ert/src/ert/config/gen_kw_config.py", line 293, in write_to_runpath
    b = math.log(data[tf.name], 10)
```

**Comment by xjules** [comment]
We can discuss if this LOG10_ prefix is still needed.

**Comment by berland** [comment]
Hard to say if it is still needed. It might have been me that requested it in the days of Spotfire as the analysing software for CSV dumps from FMU runs. When using Spotfire it was immensely nice to have the logarithmic values available to "colour by" in line plots (if not, you would have to add custom columns doing the log10 transformation for all tens/hundreds of parameters that are logarithmic-like)

**Comment by eivindjahren** [comment]
Searching for "LOG10" in our logs seem to show usage.

**Comment by xjules** [comment]
> This requires discussion on the actual usage of LOG10_ values, since when plotting the data all genkw can be math.log on the fly.

Currently the only usage of `LOG10_` prefix values is when exporting data into `parameters.txt`, since parameters transformation for the plotting purpose is done on the fly. The question is what should we export when log is not defined (eg. parameter gets 0 after the update), cc. @oyvindeide?
