### ISSUE TITLE
ssl.SSLError: Fix everest flaky tests

### ISSUE THREAD

**Issue by xjules** [equinor/ert#9623]
In komodo bleeding ert tests this error tends to popup regularly:

```sh
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.11/site-packages/everest/detached/jobs/everserver.py", line 156, in _everserver_thread
    uvicorn.run(
  File "/prog/res/komodo/bleeding-20241224-0207-py311-rhel8/root/lib64/python3.11/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/prog/res/komodo/bleeding-20241224-0207-py311-rhel8/root/lib64/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/prog/res/komodo/bleeding-20241224-0207-py311-rhel8/root/lib64/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/prog/res/komodo/bleeding-20241224-0207-py311-rhel8/root/lib64/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/prog/res/komodo/bleeding-20241224-0207-py311-rhel8/root/lib64/python3.11/site-packages/uvicorn/config.py", line 400, in load
    self.ssl: ssl.SSLContext | None = create_ssl_context(
                                      ^^^^^^^^^^^^^^^^^^^
  File "/prog/res/komodo/bleeding-20241224-0207-py311-rhel8/root/lib64/python3.11/site-packages/uvicorn/config.py", line 113, in create_ssl_context
    ctx.load_cert_chain(certfile, keyfile, get_password)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3938)
```

https://github.com/equinor/komodo-releases/actions/runs/12475212781/job/34818748086

**Comment by yngve-sk** [comment]
Can be reproduced by running everest tests on TGX/RGS, with `-n auto`, did not try enough to find any test that fails in isolation though

**Comment by xjules** [comment]
Another occurrence:
https://github.com/equinor/komodo-releases/actions/runs/12926495191/job/36051076492

**Comment by xjules** [comment]
And another one: https://github.com/equinor/komodo-releases/actions/runs/12970037639/job/36175136874
