### ISSUE TITLE
GUI crashes when clicking on 'Export data'

### ISSUE THREAD

**Issue by berland** [equinor/ert#989]
Clicking on 'Export data' button for a test case (Reek in py3 version) gives the following crash:

```
Traceback (most recent call last):
  File "/prog/res/komodo/2020.08.01-py36/root/lib/python3.6/site-packages/ert_gui/tools/export/export_tool.py", line 35, in trigger
    self.__export_widget = ref(ExportPanel(self.parent()))
  File "/prog/res/komodo/2020.08.01-py36/root/lib/python3.6/site-packages/ert_gui/tools/export/export_panel.py", line 102, in __init__
    self.keywordSelected()
  File "/prog/res/komodo/2020.08.01-py36/root/lib/python3.6/site-packages/ert_gui/tools/export/export_panel.py", line 166, in keywordSelected
    self._dynamic = self._export_keyword_model.isDynamicField(key)
  File "/prog/res/komodo/2020.08.01-py36/root/lib/python3.6/site-packages/ert_gui/tools/export/export_keyword_model.py", line 36, in isDynamicField
    return self.getVarType(key) == EnkfVarType.DYNAMIC_STATE
AttributeError: type object 'EnkfVarType' has no attribute 'DYNAMIC_STATE'
/prog/res/komodo/2020.08.01-py36/root/bin/python: line 5:  4506 Killed                  $root/libexec/$prog "$@"
```

**Comment by markusdregi** [comment]
Thanks for the bug report 🐛 This is a known issue; for which our conclusion is to turn the `Data Export` button into a CSV-export. See https://github.com/equinor/ert/issues/956.

If you disagree, feel free to reopen the issue! :)
